//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIKeyCredentialProviderBinding) DeepCopyInto(out *APIKeyCredentialProviderBinding) {
	*out = *in
	out.CredentialProviderRef = in.CredentialProviderRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIKeyCredentialProviderBinding.
func (in *APIKeyCredentialProviderBinding) DeepCopy() *APIKeyCredentialProviderBinding {
	if in == nil {
		return nil
	}
	out := new(APIKeyCredentialProviderBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIKeyCredentialProviderConfig) DeepCopyInto(out *APIKeyCredentialProviderConfig) {
	*out = *in
	in.SecretRef.DeepCopyInto(&out.SecretRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIKeyCredentialProviderConfig.
func (in *APIKeyCredentialProviderConfig) DeepCopy() *APIKeyCredentialProviderConfig {
	if in == nil {
		return nil
	}
	out := new(APIKeyCredentialProviderConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BaseMyceliumResourceStatus) DeepCopyInto(out *BaseMyceliumResourceStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BaseMyceliumResourceStatus.
func (in *BaseMyceliumResourceStatus) DeepCopy() *BaseMyceliumResourceStatus {
	if in == nil {
		return nil
	}
	out := new(BaseMyceliumResourceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialProviderBinding) DeepCopyInto(out *CredentialProviderBinding) {
	*out = *in
	if in.OAuth != nil {
		in, out := &in.OAuth, &out.OAuth
		*out = new(OAuthCredentialProviderBinding)
		(*in).DeepCopyInto(*out)
	}
	if in.APIKey != nil {
		in, out := &in.APIKey, &out.APIKey
		*out = new(APIKeyCredentialProviderBinding)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialProviderBinding.
func (in *CredentialProviderBinding) DeepCopy() *CredentialProviderBinding {
	if in == nil {
		return nil
	}
	out := new(CredentialProviderBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialProviderBindingsStatus) DeepCopyInto(out *CredentialProviderBindingsStatus) {
	*out = *in
	if in.CredentialProviders != nil {
		in, out := &in.CredentialProviders, &out.CredentialProviders
		*out = make([]ReferencedResourceStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialProviderBindingsStatus.
func (in *CredentialProviderBindingsStatus) DeepCopy() *CredentialProviderBindingsStatus {
	if in == nil {
		return nil
	}
	out := new(CredentialProviderBindingsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialProviderRef) DeepCopyInto(out *CredentialProviderRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialProviderRef.
func (in *CredentialProviderRef) DeepCopy() *CredentialProviderRef {
	if in == nil {
		return nil
	}
	out := new(CredentialProviderRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JWTAuthorizerConfig) DeepCopyInto(out *JWTAuthorizerConfig) {
	*out = *in
	if in.Audiences != nil {
		in, out := &in.Audiences, &out.Audiences
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowedClients != nil {
		in, out := &in.AllowedClients, &out.AllowedClients
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowedScopes != nil {
		in, out := &in.AllowedScopes, &out.AllowedScopes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JWTAuthorizerConfig.
func (in *JWTAuthorizerConfig) DeepCopy() *JWTAuthorizerConfig {
	if in == nil {
		return nil
	}
	out := new(JWTAuthorizerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MyceliumAgent) DeepCopyInto(out *MyceliumAgent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MyceliumAgent.
func (in *MyceliumAgent) DeepCopy() *MyceliumAgent {
	if in == nil {
		return nil
	}
	out := new(MyceliumAgent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MyceliumAgent) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MyceliumAgentList) DeepCopyInto(out *MyceliumAgentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MyceliumAgent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MyceliumAgentList.
func (in *MyceliumAgentList) DeepCopy() *MyceliumAgentList {
	if in == nil {
		return nil
	}
	out := new(MyceliumAgentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MyceliumAgentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MyceliumAgentSpec) DeepCopyInto(out *MyceliumAgentSpec) {
	*out = *in
	if in.ToolBindings != nil {
		in, out := &in.ToolBindings, &out.ToolBindings
		*out = make([]ToolBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.SandboxPool.DeepCopyInto(&out.SandboxPool)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MyceliumAgentSpec.
func (in *MyceliumAgentSpec) DeepCopy() *MyceliumAgentSpec {
	if in == nil {
		return nil
	}
	out := new(MyceliumAgentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MyceliumAgentStatus) DeepCopyInto(out *MyceliumAgentStatus) {
	*out = *in
	in.BaseMyceliumResourceStatus.DeepCopyInto(&out.BaseMyceliumResourceStatus)
	if in.ToolBindings != nil {
		in, out := &in.ToolBindings, &out.ToolBindings
		*out = make([]ToolBindingStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MyceliumAgentStatus.
func (in *MyceliumAgentStatus) DeepCopy() *MyceliumAgentStatus {
	if in == nil {
		return nil
	}
	out := new(MyceliumAgentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MyceliumAuthorizer) DeepCopyInto(out *MyceliumAuthorizer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MyceliumAuthorizer.
func (in *MyceliumAuthorizer) DeepCopy() *MyceliumAuthorizer {
	if in == nil {
		return nil
	}
	out := new(MyceliumAuthorizer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MyceliumAuthorizer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MyceliumAuthorizerList) DeepCopyInto(out *MyceliumAuthorizerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MyceliumAuthorizer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MyceliumAuthorizerList.
func (in *MyceliumAuthorizerList) DeepCopy() *MyceliumAuthorizerList {
	if in == nil {
		return nil
	}
	out := new(MyceliumAuthorizerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MyceliumAuthorizerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MyceliumAuthorizerSpec) DeepCopyInto(out *MyceliumAuthorizerSpec) {
	*out = *in
	if in.JWT != nil {
		in, out := &in.JWT, &out.JWT
		*out = new(JWTAuthorizerConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MyceliumAuthorizerSpec.
func (in *MyceliumAuthorizerSpec) DeepCopy() *MyceliumAuthorizerSpec {
	if in == nil {
		return nil
	}
	out := new(MyceliumAuthorizerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MyceliumAuthorizerStatus) DeepCopyInto(out *MyceliumAuthorizerStatus) {
	*out = *in
	in.BaseMyceliumResourceStatus.DeepCopyInto(&out.BaseMyceliumResourceStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MyceliumAuthorizerStatus.
func (in *MyceliumAuthorizerStatus) DeepCopy() *MyceliumAuthorizerStatus {
	if in == nil {
		return nil
	}
	out := new(MyceliumAuthorizerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MyceliumCredentialProvider) DeepCopyInto(out *MyceliumCredentialProvider) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MyceliumCredentialProvider.
func (in *MyceliumCredentialProvider) DeepCopy() *MyceliumCredentialProvider {
	if in == nil {
		return nil
	}
	out := new(MyceliumCredentialProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MyceliumCredentialProvider) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MyceliumCredentialProviderList) DeepCopyInto(out *MyceliumCredentialProviderList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MyceliumCredentialProvider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MyceliumCredentialProviderList.
func (in *MyceliumCredentialProviderList) DeepCopy() *MyceliumCredentialProviderList {
	if in == nil {
		return nil
	}
	out := new(MyceliumCredentialProviderList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MyceliumCredentialProviderList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MyceliumCredentialProviderSpec) DeepCopyInto(out *MyceliumCredentialProviderSpec) {
	*out = *in
	if in.OAuth != nil {
		in, out := &in.OAuth, &out.OAuth
		*out = new(OAuthCredentialProviderConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.APIKey != nil {
		in, out := &in.APIKey, &out.APIKey
		*out = new(APIKeyCredentialProviderConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MyceliumCredentialProviderSpec.
func (in *MyceliumCredentialProviderSpec) DeepCopy() *MyceliumCredentialProviderSpec {
	if in == nil {
		return nil
	}
	out := new(MyceliumCredentialProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MyceliumCredentialProviderStatus) DeepCopyInto(out *MyceliumCredentialProviderStatus) {
	*out = *in
	in.BaseMyceliumResourceStatus.DeepCopyInto(&out.BaseMyceliumResourceStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MyceliumCredentialProviderStatus.
func (in *MyceliumCredentialProviderStatus) DeepCopy() *MyceliumCredentialProviderStatus {
	if in == nil {
		return nil
	}
	out := new(MyceliumCredentialProviderStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MyceliumEcosystem) DeepCopyInto(out *MyceliumEcosystem) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MyceliumEcosystem.
func (in *MyceliumEcosystem) DeepCopy() *MyceliumEcosystem {
	if in == nil {
		return nil
	}
	out := new(MyceliumEcosystem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MyceliumEcosystem) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MyceliumEcosystemList) DeepCopyInto(out *MyceliumEcosystemList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MyceliumEcosystem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MyceliumEcosystemList.
func (in *MyceliumEcosystemList) DeepCopy() *MyceliumEcosystemList {
	if in == nil {
		return nil
	}
	out := new(MyceliumEcosystemList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MyceliumEcosystemList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MyceliumEcosystemSpec) DeepCopyInto(out *MyceliumEcosystemSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MyceliumEcosystemSpec.
func (in *MyceliumEcosystemSpec) DeepCopy() *MyceliumEcosystemSpec {
	if in == nil {
		return nil
	}
	out := new(MyceliumEcosystemSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MyceliumEcosystemStatus) DeepCopyInto(out *MyceliumEcosystemStatus) {
	*out = *in
	in.BaseMyceliumResourceStatus.DeepCopyInto(&out.BaseMyceliumResourceStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MyceliumEcosystemStatus.
func (in *MyceliumEcosystemStatus) DeepCopy() *MyceliumEcosystemStatus {
	if in == nil {
		return nil
	}
	out := new(MyceliumEcosystemStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MyceliumTool) DeepCopyInto(out *MyceliumTool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MyceliumTool.
func (in *MyceliumTool) DeepCopy() *MyceliumTool {
	if in == nil {
		return nil
	}
	out := new(MyceliumTool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MyceliumTool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MyceliumToolList) DeepCopyInto(out *MyceliumToolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MyceliumTool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MyceliumToolList.
func (in *MyceliumToolList) DeepCopy() *MyceliumToolList {
	if in == nil {
		return nil
	}
	out := new(MyceliumToolList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MyceliumToolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MyceliumToolSpec) DeepCopyInto(out *MyceliumToolSpec) {
	*out = *in
	if in.CredentialProviderBindings != nil {
		in, out := &in.CredentialProviderBindings, &out.CredentialProviderBindings
		*out = make([]CredentialProviderBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.InputSchema != nil {
		in, out := &in.InputSchema, &out.InputSchema
		*out = new(apiextensionsv1.JSON)
		(*in).DeepCopyInto(*out)
	}
	in.WorkerPool.DeepCopyInto(&out.WorkerPool)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MyceliumToolSpec.
func (in *MyceliumToolSpec) DeepCopy() *MyceliumToolSpec {
	if in == nil {
		return nil
	}
	out := new(MyceliumToolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MyceliumToolStatus) DeepCopyInto(out *MyceliumToolStatus) {
	*out = *in
	in.BaseMyceliumResourceStatus.DeepCopyInto(&out.BaseMyceliumResourceStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MyceliumToolStatus.
func (in *MyceliumToolStatus) DeepCopy() *MyceliumToolStatus {
	if in == nil {
		return nil
	}
	out := new(MyceliumToolStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OAuthAuthorizationServerMetadata) DeepCopyInto(out *OAuthAuthorizationServerMetadata) {
	*out = *in
	if in.ResponseTypes != nil {
		in, out := &in.ResponseTypes, &out.ResponseTypes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.TokenEndpointAuthMethods != nil {
		in, out := &in.TokenEndpointAuthMethods, &out.TokenEndpointAuthMethods
		*out = make([]TokenEndpointAuthMethod, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OAuthAuthorizationServerMetadata.
func (in *OAuthAuthorizationServerMetadata) DeepCopy() *OAuthAuthorizationServerMetadata {
	if in == nil {
		return nil
	}
	out := new(OAuthAuthorizationServerMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OAuthCredentialProviderBinding) DeepCopyInto(out *OAuthCredentialProviderBinding) {
	*out = *in
	out.CredentialProviderRef = in.CredentialProviderRef
	if in.Scopes != nil {
		in, out := &in.Scopes, &out.Scopes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OAuthCredentialProviderBinding.
func (in *OAuthCredentialProviderBinding) DeepCopy() *OAuthCredentialProviderBinding {
	if in == nil {
		return nil
	}
	out := new(OAuthCredentialProviderBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OAuthCredentialProviderConfig) DeepCopyInto(out *OAuthCredentialProviderConfig) {
	*out = *in
	in.ClientSecretRef.DeepCopyInto(&out.ClientSecretRef)
	in.Discovery.DeepCopyInto(&out.Discovery)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OAuthCredentialProviderConfig.
func (in *OAuthCredentialProviderConfig) DeepCopy() *OAuthCredentialProviderConfig {
	if in == nil {
		return nil
	}
	out := new(OAuthCredentialProviderConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OAuthDiscoveryConfig) DeepCopyInto(out *OAuthDiscoveryConfig) {
	*out = *in
	if in.DiscoveryURL != nil {
		in, out := &in.DiscoveryURL, &out.DiscoveryURL
		*out = new(string)
		**out = **in
	}
	if in.AuthorizationServerMetadata != nil {
		in, out := &in.AuthorizationServerMetadata, &out.AuthorizationServerMetadata
		*out = new(OAuthAuthorizationServerMetadata)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OAuthDiscoveryConfig.
func (in *OAuthDiscoveryConfig) DeepCopy() *OAuthDiscoveryConfig {
	if in == nil {
		return nil
	}
	out := new(OAuthDiscoveryConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateLimitConfig) DeepCopyInto(out *RateLimitConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimitConfig.
func (in *RateLimitConfig) DeepCopy() *RateLimitConfig {
	if in == nil {
		return nil
	}
	out := new(RateLimitConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReferencedResourceStatus) DeepCopyInto(out *ReferencedResourceStatus) {
	*out = *in
	if in.ResourceRef != nil {
		in, out := &in.ResourceRef, &out.ResourceRef
		*out = new(corev1.TypedObjectReference)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReferencedResourceStatus.
func (in *ReferencedResourceStatus) DeepCopy() *ReferencedResourceStatus {
	if in == nil {
		return nil
	}
	out := new(ReferencedResourceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxPoolConfig) DeepCopyInto(out *SandboxPoolConfig) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxPoolConfig.
func (in *SandboxPoolConfig) DeepCopy() *SandboxPoolConfig {
	if in == nil {
		return nil
	}
	out := new(SandboxPoolConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolBinding) DeepCopyInto(out *ToolBinding) {
	*out = *in
	out.ToolRef = in.ToolRef
	if in.RateLimit != nil {
		in, out := &in.RateLimit, &out.RateLimit
		*out = new(RateLimitConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolBinding.
func (in *ToolBinding) DeepCopy() *ToolBinding {
	if in == nil {
		return nil
	}
	out := new(ToolBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolBindingStatus) DeepCopyInto(out *ToolBindingStatus) {
	*out = *in
	out.ToolRef = in.ToolRef
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolBindingStatus.
func (in *ToolBindingStatus) DeepCopy() *ToolBindingStatus {
	if in == nil {
		return nil
	}
	out := new(ToolBindingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolRef) DeepCopyInto(out *ToolRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolRef.
func (in *ToolRef) DeepCopy() *ToolRef {
	if in == nil {
		return nil
	}
	out := new(ToolRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkerPoolConfig) DeepCopyInto(out *WorkerPoolConfig) {
	*out = *in
	if in.MinReplicas != nil {
		in, out := &in.MinReplicas, &out.MinReplicas
		*out = new(int32)
		**out = **in
	}
	if in.MaxReplicas != nil {
		in, out := &in.MaxReplicas, &out.MaxReplicas
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkerPoolConfig.
func (in *WorkerPoolConfig) DeepCopy() *WorkerPoolConfig {
	if in == nil {
		return nil
	}
	out := new(WorkerPoolConfig)
	in.DeepCopyInto(out)
	return out
}
