---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mycelium-controller
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - agentgateway.dev
  resources:
  - agentgatewaybackends
  - agentgatewaypolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - httproutes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mycelium.io
  resources:
  - agents
  - credentialproviders
  - projects
  - tools
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mycelium.io
  resources:
  - agents/finalizers
  - credentialproviders/finalizers
  - projects/finalizers
  - tools/finalizers
  verbs:
  - update
- apiGroups:
  - mycelium.io
  resources:
  - agents/status
  - credentialproviders/status
  - projects/status
  - tools/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - serving.knative.dev
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
