// Code generated by applyconfiguration-gen. DO NOT EDIT.

package agentgateway

import (
	shared "github.com/agentgateway/agentgateway/controller/api/v1alpha1/shared"
)

// AccessLogApplyConfiguration represents a declarative configuration of the AccessLog type for use
// with apply.
//
// AccessLog specifies how per-request access logs are emitted.
type AccessLogApplyConfiguration struct {
	// `filter` specifies a CEL expression that is used to filter logs. A log
	// will only be emitted if the expression evaluates to `true`.
	Filter *shared.CELExpression `json:"filter,omitempty"`
	// `attributes` specifies customizations to the key-value pairs that are
	// logged.
	Attributes *LogTracingAttributesApplyConfiguration `json:"attributes,omitempty"`
	// `otlp` configures OTLP access log export to an
	// OpenTelemetry-compatible backend.
	Otlp *OtlpAccessLogApplyConfiguration `json:"otlp,omitempty"`
}

// AccessLogApplyConfiguration constructs a declarative configuration of the AccessLog type for use with
// apply.
func AccessLog() *AccessLogApplyConfiguration {
	return &AccessLogApplyConfiguration{}
}

// WithFilter sets the Filter field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Filter field is set to the value of the last call.
func (b *AccessLogApplyConfiguration) WithFilter(value shared.CELExpression) *AccessLogApplyConfiguration {
	b.Filter = &value
	return b
}

// WithAttributes sets the Attributes field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Attributes field is set to the value of the last call.
func (b *AccessLogApplyConfiguration) WithAttributes(value *LogTracingAttributesApplyConfiguration) *AccessLogApplyConfiguration {
	b.Attributes = value
	return b
}

// WithOtlp sets the Otlp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Otlp field is set to the value of the last call.
func (b *AccessLogApplyConfiguration) WithOtlp(value *OtlpAccessLogApplyConfiguration) *AccessLogApplyConfiguration {
	b.Otlp = value
	return b
}
