// Code generated by applyconfiguration-gen. DO NOT EDIT.

package agentgateway

import (
	shared "github.com/agentgateway/agentgateway/controller/api/v1alpha1/shared"
)

// AgentgatewayParametersOverlaysApplyConfiguration represents a declarative configuration of the AgentgatewayParametersOverlays type for use
// with apply.
type AgentgatewayParametersOverlaysApplyConfiguration struct {
	// `deployment` allows specifying overrides for the generated
	// `Deployment` resource.
	Deployment *shared.KubernetesResourceOverlay `json:"deployment,omitempty"`
	// `service` allows specifying overrides for the generated `Service`
	// resource.
	Service *shared.KubernetesResourceOverlay `json:"service,omitempty"`
	// `serviceAccount` allows specifying overrides for the generated
	// `ServiceAccount` resource.
	ServiceAccount *shared.KubernetesResourceOverlay `json:"serviceAccount,omitempty"`
	// `podDisruptionBudget` allows creating a `PodDisruptionBudget` for the
	// agentgateway proxy. If absent, no PDB is created. If present, a PDB is
	// created with its selector automatically configured to target the
	// agentgateway proxy `Deployment`. The `metadata` and `spec` fields from
	// this overlay are applied to the generated PDB.
	PodDisruptionBudget *shared.KubernetesResourceOverlay `json:"podDisruptionBudget,omitempty"`
	// `horizontalPodAutoscaler` allows creating a `HorizontalPodAutoscaler`
	// for the agentgateway proxy. If absent, no HPA is created. If present, an
	// HPA is created with its `scaleTargetRef` automatically configured to
	// target the agentgateway proxy `Deployment`. The `metadata` and `spec`
	// fields from this overlay are applied to the generated HPA.
	HorizontalPodAutoscaler *shared.KubernetesResourceOverlay `json:"horizontalPodAutoscaler,omitempty"`
}

// AgentgatewayParametersOverlaysApplyConfiguration constructs a declarative configuration of the AgentgatewayParametersOverlays type for use with
// apply.
func AgentgatewayParametersOverlays() *AgentgatewayParametersOverlaysApplyConfiguration {
	return &AgentgatewayParametersOverlaysApplyConfiguration{}
}

// WithDeployment sets the Deployment field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Deployment field is set to the value of the last call.
func (b *AgentgatewayParametersOverlaysApplyConfiguration) WithDeployment(value shared.KubernetesResourceOverlay) *AgentgatewayParametersOverlaysApplyConfiguration {
	b.Deployment = &value
	return b
}

// WithService sets the Service field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Service field is set to the value of the last call.
func (b *AgentgatewayParametersOverlaysApplyConfiguration) WithService(value shared.KubernetesResourceOverlay) *AgentgatewayParametersOverlaysApplyConfiguration {
	b.Service = &value
	return b
}

// WithServiceAccount sets the ServiceAccount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServiceAccount field is set to the value of the last call.
func (b *AgentgatewayParametersOverlaysApplyConfiguration) WithServiceAccount(value shared.KubernetesResourceOverlay) *AgentgatewayParametersOverlaysApplyConfiguration {
	b.ServiceAccount = &value
	return b
}

// WithPodDisruptionBudget sets the PodDisruptionBudget field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PodDisruptionBudget field is set to the value of the last call.
func (b *AgentgatewayParametersOverlaysApplyConfiguration) WithPodDisruptionBudget(value shared.KubernetesResourceOverlay) *AgentgatewayParametersOverlaysApplyConfiguration {
	b.PodDisruptionBudget = &value
	return b
}

// WithHorizontalPodAutoscaler sets the HorizontalPodAutoscaler field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HorizontalPodAutoscaler field is set to the value of the last call.
func (b *AgentgatewayParametersOverlaysApplyConfiguration) WithHorizontalPodAutoscaler(value shared.KubernetesResourceOverlay) *AgentgatewayParametersOverlaysApplyConfiguration {
	b.HorizontalPodAutoscaler = &value
	return b
}
