// Code generated by applyconfiguration-gen. DO NOT EDIT.

package agentgateway

import (
	shared "github.com/agentgateway/agentgateway/controller/api/v1alpha1/shared"
)

// AgentgatewayPolicySpecApplyConfiguration represents a declarative configuration of the AgentgatewayPolicySpec type for use
// with apply.
type AgentgatewayPolicySpecApplyConfiguration struct {
	// `targetRefs` specifies the target resources by reference to attach the
	// policy to.
	TargetRefs []shared.LocalPolicyTargetReferenceWithSectionName `json:"targetRefs,omitempty"`
	// `targetSelectors` specifies the target selectors used to select resources
	// to attach the policy to.
	TargetSelectors []shared.LocalPolicyTargetSelectorWithSectionName `json:"targetSelectors,omitempty"`
	// frontend defines settings for how to handle incoming traffic.
	//
	// A frontend policy can only target a `Gateway`. `Listener` and
	// `ListenerSet` are not valid targets.
	//
	// When multiple policies are selected for a given request, they are merged on a field-level basis, but not a deep
	// merge. For example, policy A sets `tcp` and `tls`, and policy B sets
	// `tls`; the effective policy would be `tcp` from policy A, and `tls` from
	// policy B.
	Frontend *FrontendApplyConfiguration `json:"frontend,omitempty"`
	// traffic defines settings for how process traffic.
	//
	// A traffic policy can target a `Gateway` (optionally, with a
	// `sectionName` indicating the listener), `ListenerSet`, or `Route`
	// (optionally, with a `sectionName` indicating the route rule).
	//
	// When multiple policies are selected for a given request, they are merged on a field-level basis, but not a deep
	// merge. Precedence is given to more precise policies: `Gateway` <
	// `Listener` < `Route` < `Route Rule`. For example, policy A sets
	// `timeouts` and `retries`, and policy B sets `retries`; the effective
	// policy would be `timeouts` from policy A, and `retries` from policy B.
	Traffic *TrafficApplyConfiguration `json:"traffic,omitempty"`
	// backend defines settings for how to connect to destination backends.
	//
	// A backend policy can target a `Gateway` (optionally, with a
	// `sectionName` indicating the listener), `ListenerSet`, `Route`
	// (optionally, with a `sectionName` indicating the route rule), or a
	// `Service` or `Backend` (optionally, with a `sectionName` indicating the
	// port for `Service`, or sub-backend for `Backend`).
	//
	// Note that a backend policy applies when connecting to a specific destination backend. Targeting a higher level
	// resource, like `Gateway`, is just a way to easily apply a policy to a
	// group of backends.
	//
	// When multiple policies are selected for a given request, they are merged on a field-level basis, but not a deep
	// merge. Precedence is given to more precise policies: `Gateway` <
	// `Listener` < `Route` < `Route Rule` < `Backend` or `Service`. For
	// example, if a `Gateway` policy sets `tcp` and `tls`, and a `Backend`
	// policy sets `tls`, the effective policy would be `tcp` from the
	// `Gateway`, and `tls` from the `Backend`.
	Backend *BackendFullApplyConfiguration `json:"backend,omitempty"`
}

// AgentgatewayPolicySpecApplyConfiguration constructs a declarative configuration of the AgentgatewayPolicySpec type for use with
// apply.
func AgentgatewayPolicySpec() *AgentgatewayPolicySpecApplyConfiguration {
	return &AgentgatewayPolicySpecApplyConfiguration{}
}

// WithTargetRefs adds the given value to the TargetRefs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the TargetRefs field.
func (b *AgentgatewayPolicySpecApplyConfiguration) WithTargetRefs(values ...shared.LocalPolicyTargetReferenceWithSectionName) *AgentgatewayPolicySpecApplyConfiguration {
	for i := range values {
		b.TargetRefs = append(b.TargetRefs, values[i])
	}
	return b
}

// WithTargetSelectors adds the given value to the TargetSelectors field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the TargetSelectors field.
func (b *AgentgatewayPolicySpecApplyConfiguration) WithTargetSelectors(values ...shared.LocalPolicyTargetSelectorWithSectionName) *AgentgatewayPolicySpecApplyConfiguration {
	for i := range values {
		b.TargetSelectors = append(b.TargetSelectors, values[i])
	}
	return b
}

// WithFrontend sets the Frontend field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Frontend field is set to the value of the last call.
func (b *AgentgatewayPolicySpecApplyConfiguration) WithFrontend(value *FrontendApplyConfiguration) *AgentgatewayPolicySpecApplyConfiguration {
	b.Frontend = value
	return b
}

// WithTraffic sets the Traffic field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Traffic field is set to the value of the last call.
func (b *AgentgatewayPolicySpecApplyConfiguration) WithTraffic(value *TrafficApplyConfiguration) *AgentgatewayPolicySpecApplyConfiguration {
	b.Traffic = value
	return b
}

// WithBackend sets the Backend field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Backend field is set to the value of the last call.
func (b *AgentgatewayPolicySpecApplyConfiguration) WithBackend(value *BackendFullApplyConfiguration) *AgentgatewayPolicySpecApplyConfiguration {
	b.Backend = value
	return b
}
