// Code generated by applyconfiguration-gen. DO NOT EDIT.

package agentgateway

import (
	shared "github.com/agentgateway/agentgateway/controller/api/v1alpha1/shared"
	corev1 "k8s.io/api/core/v1"
	v1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
)

// AgentgatewayParametersSpecApplyConfiguration represents a declarative configuration of the AgentgatewayParametersSpec type for use
// with apply.
type AgentgatewayParametersSpecApplyConfiguration struct {
	AgentgatewayParametersConfigsApplyConfiguration  `json:",inline"`
	AgentgatewayParametersOverlaysApplyConfiguration `json:",inline"`
}

// AgentgatewayParametersSpecApplyConfiguration constructs a declarative configuration of the AgentgatewayParametersSpec type for use with
// apply.
func AgentgatewayParametersSpec() *AgentgatewayParametersSpecApplyConfiguration {
	return &AgentgatewayParametersSpecApplyConfiguration{}
}

// WithLogging sets the Logging field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Logging field is set to the value of the last call.
func (b *AgentgatewayParametersSpecApplyConfiguration) WithLogging(value *AgentgatewayParametersLoggingApplyConfiguration) *AgentgatewayParametersSpecApplyConfiguration {
	b.AgentgatewayParametersConfigsApplyConfiguration.Logging = value
	return b
}

// WithRawConfig sets the RawConfig field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RawConfig field is set to the value of the last call.
func (b *AgentgatewayParametersSpecApplyConfiguration) WithRawConfig(value v1.JSON) *AgentgatewayParametersSpecApplyConfiguration {
	b.AgentgatewayParametersConfigsApplyConfiguration.RawConfig = &value
	return b
}

// WithImage sets the Image field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Image field is set to the value of the last call.
func (b *AgentgatewayParametersSpecApplyConfiguration) WithImage(value *ImageApplyConfiguration) *AgentgatewayParametersSpecApplyConfiguration {
	b.AgentgatewayParametersConfigsApplyConfiguration.Image = value
	return b
}

// WithEnv adds the given value to the Env field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Env field.
func (b *AgentgatewayParametersSpecApplyConfiguration) WithEnv(values ...corev1.EnvVar) *AgentgatewayParametersSpecApplyConfiguration {
	for i := range values {
		b.AgentgatewayParametersConfigsApplyConfiguration.Env = append(b.AgentgatewayParametersConfigsApplyConfiguration.Env, values[i])
	}
	return b
}

// WithResources sets the Resources field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Resources field is set to the value of the last call.
func (b *AgentgatewayParametersSpecApplyConfiguration) WithResources(value corev1.ResourceRequirements) *AgentgatewayParametersSpecApplyConfiguration {
	b.AgentgatewayParametersConfigsApplyConfiguration.Resources = &value
	return b
}

// WithShutdown sets the Shutdown field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Shutdown field is set to the value of the last call.
func (b *AgentgatewayParametersSpecApplyConfiguration) WithShutdown(value *ShutdownSpecApplyConfiguration) *AgentgatewayParametersSpecApplyConfiguration {
	b.AgentgatewayParametersConfigsApplyConfiguration.Shutdown = value
	return b
}

// WithIstio sets the Istio field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Istio field is set to the value of the last call.
func (b *AgentgatewayParametersSpecApplyConfiguration) WithIstio(value *IstioSpecApplyConfiguration) *AgentgatewayParametersSpecApplyConfiguration {
	b.AgentgatewayParametersConfigsApplyConfiguration.Istio = value
	return b
}

// WithDeployment sets the Deployment field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Deployment field is set to the value of the last call.
func (b *AgentgatewayParametersSpecApplyConfiguration) WithDeployment(value shared.KubernetesResourceOverlay) *AgentgatewayParametersSpecApplyConfiguration {
	b.AgentgatewayParametersOverlaysApplyConfiguration.Deployment = &value
	return b
}

// WithService sets the Service field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Service field is set to the value of the last call.
func (b *AgentgatewayParametersSpecApplyConfiguration) WithService(value shared.KubernetesResourceOverlay) *AgentgatewayParametersSpecApplyConfiguration {
	b.AgentgatewayParametersOverlaysApplyConfiguration.Service = &value
	return b
}

// WithServiceAccount sets the ServiceAccount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServiceAccount field is set to the value of the last call.
func (b *AgentgatewayParametersSpecApplyConfiguration) WithServiceAccount(value shared.KubernetesResourceOverlay) *AgentgatewayParametersSpecApplyConfiguration {
	b.AgentgatewayParametersOverlaysApplyConfiguration.ServiceAccount = &value
	return b
}

// WithPodDisruptionBudget sets the PodDisruptionBudget field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PodDisruptionBudget field is set to the value of the last call.
func (b *AgentgatewayParametersSpecApplyConfiguration) WithPodDisruptionBudget(value shared.KubernetesResourceOverlay) *AgentgatewayParametersSpecApplyConfiguration {
	b.AgentgatewayParametersOverlaysApplyConfiguration.PodDisruptionBudget = &value
	return b
}

// WithHorizontalPodAutoscaler sets the HorizontalPodAutoscaler field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HorizontalPodAutoscaler field is set to the value of the last call.
func (b *AgentgatewayParametersSpecApplyConfiguration) WithHorizontalPodAutoscaler(value shared.KubernetesResourceOverlay) *AgentgatewayParametersSpecApplyConfiguration {
	b.AgentgatewayParametersOverlaysApplyConfiguration.HorizontalPodAutoscaler = &value
	return b
}
