// Code generated by applyconfiguration-gen. DO NOT EDIT.

package agentgateway

import (
	shared "github.com/agentgateway/agentgateway/controller/api/v1alpha1/shared"
)

// AgentExtAuthHTTPApplyConfiguration represents a declarative configuration of the AgentExtAuthHTTP type for use
// with apply.
type AgentExtAuthHTTPApplyConfiguration struct {
	// `path` specifies the path to send to the authorization server. If
	// unset, this defaults to the original request path.
	// This is a CEL expression, which allows customizing the path based on the
	// incoming request. For example, to add a prefix, use
	// `"/prefix/" + request.path`.
	Path *shared.CELExpression `json:"path,omitempty"`
	// `redirect` defines an optional expression to determine a path to
	// redirect to on authorization failure. This is useful to redirect to a
	// sign-in page.
	Redirect *shared.CELExpression `json:"redirect,omitempty"`
	// `allowedRequestHeaders` specifies what additional headers from the client request
	// will be sent to the authorization server.
	//
	// If unset, the following headers are sent by default: `Authorization`.
	AllowedRequestHeaders []string `json:"allowedRequestHeaders,omitempty"`
	// `addRequestHeaders` specifies what additional headers to add to the
	// request to the authorization server. While `allowedRequestHeaders` just
	// passes the original headers through, `addRequestHeaders` allows defining
	// custom headers based on CEL expressions.
	AddRequestHeaders map[string]shared.CELExpression `json:"addRequestHeaders,omitempty"`
	// `allowedResponseHeaders` specifies what headers from the authorization response
	// will be copied into the request to the backend.
	AllowedResponseHeaders []string `json:"allowedResponseHeaders,omitempty"`
	// `responseMetadata` specifies what metadata fields should be constructed
	// from the authorization response. These will be included under the
	// `extauthz` variable in future CEL expressions. Setting this is useful
	// for things like logging usernames, without needing to include them as
	// headers to the backend, as `allowedResponseHeaders` would.
	ResponseMetadata map[string]shared.CELExpression `json:"responseMetadata,omitempty"`
}

// AgentExtAuthHTTPApplyConfiguration constructs a declarative configuration of the AgentExtAuthHTTP type for use with
// apply.
func AgentExtAuthHTTP() *AgentExtAuthHTTPApplyConfiguration {
	return &AgentExtAuthHTTPApplyConfiguration{}
}

// WithPath sets the Path field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Path field is set to the value of the last call.
func (b *AgentExtAuthHTTPApplyConfiguration) WithPath(value shared.CELExpression) *AgentExtAuthHTTPApplyConfiguration {
	b.Path = &value
	return b
}

// WithRedirect sets the Redirect field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Redirect field is set to the value of the last call.
func (b *AgentExtAuthHTTPApplyConfiguration) WithRedirect(value shared.CELExpression) *AgentExtAuthHTTPApplyConfiguration {
	b.Redirect = &value
	return b
}

// WithAllowedRequestHeaders adds the given value to the AllowedRequestHeaders field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AllowedRequestHeaders field.
func (b *AgentExtAuthHTTPApplyConfiguration) WithAllowedRequestHeaders(values ...string) *AgentExtAuthHTTPApplyConfiguration {
	for i := range values {
		b.AllowedRequestHeaders = append(b.AllowedRequestHeaders, values[i])
	}
	return b
}

// WithAddRequestHeaders puts the entries into the AddRequestHeaders field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the AddRequestHeaders field,
// overwriting an existing map entries in AddRequestHeaders field with the same key.
func (b *AgentExtAuthHTTPApplyConfiguration) WithAddRequestHeaders(entries map[string]shared.CELExpression) *AgentExtAuthHTTPApplyConfiguration {
	if b.AddRequestHeaders == nil && len(entries) > 0 {
		b.AddRequestHeaders = make(map[string]shared.CELExpression, len(entries))
	}
	for k, v := range entries {
		b.AddRequestHeaders[k] = v
	}
	return b
}

// WithAllowedResponseHeaders adds the given value to the AllowedResponseHeaders field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AllowedResponseHeaders field.
func (b *AgentExtAuthHTTPApplyConfiguration) WithAllowedResponseHeaders(values ...string) *AgentExtAuthHTTPApplyConfiguration {
	for i := range values {
		b.AllowedResponseHeaders = append(b.AllowedResponseHeaders, values[i])
	}
	return b
}

// WithResponseMetadata puts the entries into the ResponseMetadata field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the ResponseMetadata field,
// overwriting an existing map entries in ResponseMetadata field with the same key.
func (b *AgentExtAuthHTTPApplyConfiguration) WithResponseMetadata(entries map[string]shared.CELExpression) *AgentExtAuthHTTPApplyConfiguration {
	if b.ResponseMetadata == nil && len(entries) > 0 {
		b.ResponseMetadata = make(map[string]shared.CELExpression, len(entries))
	}
	for k, v := range entries {
		b.ResponseMetadata[k] = v
	}
	return b
}
