// Code generated by applyconfiguration-gen. DO NOT EDIT.

package agentgateway

import (
	shared "github.com/agentgateway/agentgateway/controller/api/v1alpha1/shared"
)

// AgentExtAuthGRPCApplyConfiguration represents a declarative configuration of the AgentExtAuthGRPC type for use
// with apply.
type AgentExtAuthGRPCApplyConfiguration struct {
	// `contextExtensions` specifies additional arbitrary key-value pairs to
	// send to the authorization server in the `context_extensions` field.
	ContextExtensions map[string]string `json:"contextExtensions,omitempty"`
	// `requestMetadata` specifies metadata to be sent to the authorization
	// server. This maps to the `metadata_context.filter_metadata` field of the
	// request, and allows dynamic CEL expressions. If unset, by default the
	// `envoy.filters.http.jwt_authn` key is set if the JWT policy is used as
	// well, for compatibility.
	RequestMetadata map[string]shared.CELExpression `json:"requestMetadata,omitempty"`
}

// AgentExtAuthGRPCApplyConfiguration constructs a declarative configuration of the AgentExtAuthGRPC type for use with
// apply.
func AgentExtAuthGRPC() *AgentExtAuthGRPCApplyConfiguration {
	return &AgentExtAuthGRPCApplyConfiguration{}
}

// WithContextExtensions puts the entries into the ContextExtensions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the ContextExtensions field,
// overwriting an existing map entries in ContextExtensions field with the same key.
func (b *AgentExtAuthGRPCApplyConfiguration) WithContextExtensions(entries map[string]string) *AgentExtAuthGRPCApplyConfiguration {
	if b.ContextExtensions == nil && len(entries) > 0 {
		b.ContextExtensions = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ContextExtensions[k] = v
	}
	return b
}

// WithRequestMetadata puts the entries into the RequestMetadata field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the RequestMetadata field,
// overwriting an existing map entries in RequestMetadata field with the same key.
func (b *AgentExtAuthGRPCApplyConfiguration) WithRequestMetadata(entries map[string]shared.CELExpression) *AgentExtAuthGRPCApplyConfiguration {
	if b.RequestMetadata == nil && len(entries) > 0 {
		b.RequestMetadata = make(map[string]shared.CELExpression, len(entries))
	}
	for k, v := range entries {
		b.RequestMetadata[k] = v
	}
	return b
}
