// Code generated by applyconfiguration-gen. DO NOT EDIT.

package agentgateway

import (
	corev1 "k8s.io/api/core/v1"
	v1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
)

// AgentgatewayParametersConfigsApplyConfiguration represents a declarative configuration of the AgentgatewayParametersConfigs type for use
// with apply.
type AgentgatewayParametersConfigsApplyConfiguration struct {
	// `logging` configuration for Agentgateway. By default, all logs are set to
	// `info` level.
	Logging *AgentgatewayParametersLoggingApplyConfiguration `json:"logging,omitempty"`
	// `rawConfig` provides an opaque mechanism to configure the `agentgateway`
	// config file. The `agentgateway` binary has a `-f` option to specify a
	// config file, and this field supplies that file. This will be merged with
	// configuration derived from typed fields like `logging.format`, and those
	// typed fields will take precedence.
	//
	// Example:
	//
	// rawConfig:
	// binds:
	// - port: 3000
	// listeners:
	// - routes:
	// - policies:
	// cors:
	// allowOrigins:
	// - "*"
	// allowHeaders:
	// - mcp-protocol-version
	// - content-type
	// - cache-control
	// backends:
	// - mcp:
	// targets:
	// - name: everything
	// stdio:
	// cmd: npx
	// args: ["@modelcontextprotocol/server-everything"]
	RawConfig *v1.JSON `json:"rawConfig,omitempty"`
	// The agentgateway container image. See
	// https://kubernetes.io/docs/concepts/containers/images
	// for details.
	//
	// Default values, which may be overridden individually:
	//
	// registry: cr.agentgateway.dev
	// repository: agentgateway
	// tag: <agentgateway version>
	// pullPolicy: <omitted, relying on Kubernetes defaults which depend on the tag>
	Image *ImageApplyConfiguration `json:"image,omitempty"`
	// The container environment variables. These override any existing
	// values. If you want to delete an environment variable entirely, use
	// `$patch: delete` with `AgentgatewayParametersOverlays` instead. Note that
	// [variable
	// expansion](https://kubernetes.io/docs/tasks/inject-data-application/define-interdependent-environment-variables/)
	// does apply, but is highly discouraged -- to set dependent environment
	// variables, you can use `$(VAR_NAME)`, but it's highly discouraged.
	// `$$(VAR_NAME)` avoids expansion and results in a literal
	// `$(VAR_NAME)`.
	//
	// If `SESSION_KEY` is specified, it takes precedence over the
	// controller-managed per-`Gateway` session key `Secret`.
	Env []corev1.EnvVar `json:"env,omitempty"`
	// The compute resources required by this container. See
	// https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
	// for details.
	Resources *corev1.ResourceRequirements `json:"resources,omitempty"`
	// Shutdown delay configuration. How graceful planned or unplanned data
	// plane changes happen is in tension with how quickly rollouts of the data
	// plane complete. How long a data plane pod must wait for shutdown to be
	// perfectly graceful depends on how you have configured your `Gateway`
	// resources.
	Shutdown *ShutdownSpecApplyConfiguration `json:"shutdown,omitempty"`
	// Configure Istio integration. If enabled, Agentgateway can natively connect to Istio enabled pods with mTLS.
	Istio *IstioSpecApplyConfiguration `json:"istio,omitempty"`
}

// AgentgatewayParametersConfigsApplyConfiguration constructs a declarative configuration of the AgentgatewayParametersConfigs type for use with
// apply.
func AgentgatewayParametersConfigs() *AgentgatewayParametersConfigsApplyConfiguration {
	return &AgentgatewayParametersConfigsApplyConfiguration{}
}

// WithLogging sets the Logging field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Logging field is set to the value of the last call.
func (b *AgentgatewayParametersConfigsApplyConfiguration) WithLogging(value *AgentgatewayParametersLoggingApplyConfiguration) *AgentgatewayParametersConfigsApplyConfiguration {
	b.Logging = value
	return b
}

// WithRawConfig sets the RawConfig field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RawConfig field is set to the value of the last call.
func (b *AgentgatewayParametersConfigsApplyConfiguration) WithRawConfig(value v1.JSON) *AgentgatewayParametersConfigsApplyConfiguration {
	b.RawConfig = &value
	return b
}

// WithImage sets the Image field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Image field is set to the value of the last call.
func (b *AgentgatewayParametersConfigsApplyConfiguration) WithImage(value *ImageApplyConfiguration) *AgentgatewayParametersConfigsApplyConfiguration {
	b.Image = value
	return b
}

// WithEnv adds the given value to the Env field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Env field.
func (b *AgentgatewayParametersConfigsApplyConfiguration) WithEnv(values ...corev1.EnvVar) *AgentgatewayParametersConfigsApplyConfiguration {
	for i := range values {
		b.Env = append(b.Env, values[i])
	}
	return b
}

// WithResources sets the Resources field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Resources field is set to the value of the last call.
func (b *AgentgatewayParametersConfigsApplyConfiguration) WithResources(value corev1.ResourceRequirements) *AgentgatewayParametersConfigsApplyConfiguration {
	b.Resources = &value
	return b
}

// WithShutdown sets the Shutdown field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Shutdown field is set to the value of the last call.
func (b *AgentgatewayParametersConfigsApplyConfiguration) WithShutdown(value *ShutdownSpecApplyConfiguration) *AgentgatewayParametersConfigsApplyConfiguration {
	b.Shutdown = value
	return b
}

// WithIstio sets the Istio field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Istio field is set to the value of the last call.
func (b *AgentgatewayParametersConfigsApplyConfiguration) WithIstio(value *IstioSpecApplyConfiguration) *AgentgatewayParametersConfigsApplyConfiguration {
	b.Istio = value
	return b
}
