// Code generated by applyconfiguration-gen. DO NOT EDIT.

package agentgateway

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// AgentgatewayBackendStatusApplyConfiguration represents a declarative configuration of the AgentgatewayBackendStatus type for use
// with apply.
//
// AgentgatewayBackend defines the observed state of AgentgatewayBackend.
type AgentgatewayBackendStatusApplyConfiguration struct {
	// Conditions is the list of conditions for the backend.
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// AgentgatewayBackendStatusApplyConfiguration constructs a declarative configuration of the AgentgatewayBackendStatus type for use with
// apply.
func AgentgatewayBackendStatus() *AgentgatewayBackendStatusApplyConfiguration {
	return &AgentgatewayBackendStatusApplyConfiguration{}
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *AgentgatewayBackendStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *AgentgatewayBackendStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
