// Code generated by applyconfiguration-gen. DO NOT EDIT.

package agentgateway

import (
	v1alpha1agentgateway "github.com/agentgateway/agentgateway/controller/api/v1alpha1/agentgateway"
)

// AgentgatewayBackendSpecApplyConfiguration represents a declarative configuration of the AgentgatewayBackendSpec type for use
// with apply.
type AgentgatewayBackendSpecApplyConfiguration struct {
	// static represents a static hostname.
	Static *StaticBackendApplyConfiguration `json:"static,omitempty"`
	// ai represents a LLM backend.
	AI *AIBackendApplyConfiguration `json:"ai,omitempty"`
	// mcp represents an MCP backend
	MCP *MCPBackendApplyConfiguration `json:"mcp,omitempty"`
	// dynamicForwardProxy configures the proxy to dynamically send requests to the destination based on the incoming
	// request HTTP host header, or TLS SNI for TLS traffic.
	//
	// Note: this Backend type enables users to send trigger the proxy to send requests to arbitrary destinations. Proper
	// access controls must be put in place when using this backend type.
	DynamicForwardProxy *v1alpha1agentgateway.DynamicForwardProxyBackend `json:"dynamicForwardProxy,omitempty"`
	// aws represents an AWS service backend (AgentCore, etc.).
	Aws *AwsBackendApplyConfiguration `json:"aws,omitempty"`
	// policies controls policies for communicating with this backend. Policies may also be set in AgentgatewayPolicy;
	// policies are merged on a field-level basis, with policies on the Backend (this field) taking precedence.
	Policies *BackendFullApplyConfiguration `json:"policies,omitempty"`
}

// AgentgatewayBackendSpecApplyConfiguration constructs a declarative configuration of the AgentgatewayBackendSpec type for use with
// apply.
func AgentgatewayBackendSpec() *AgentgatewayBackendSpecApplyConfiguration {
	return &AgentgatewayBackendSpecApplyConfiguration{}
}

// WithStatic sets the Static field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Static field is set to the value of the last call.
func (b *AgentgatewayBackendSpecApplyConfiguration) WithStatic(value *StaticBackendApplyConfiguration) *AgentgatewayBackendSpecApplyConfiguration {
	b.Static = value
	return b
}

// WithAI sets the AI field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AI field is set to the value of the last call.
func (b *AgentgatewayBackendSpecApplyConfiguration) WithAI(value *AIBackendApplyConfiguration) *AgentgatewayBackendSpecApplyConfiguration {
	b.AI = value
	return b
}

// WithMCP sets the MCP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MCP field is set to the value of the last call.
func (b *AgentgatewayBackendSpecApplyConfiguration) WithMCP(value *MCPBackendApplyConfiguration) *AgentgatewayBackendSpecApplyConfiguration {
	b.MCP = value
	return b
}

// WithDynamicForwardProxy sets the DynamicForwardProxy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DynamicForwardProxy field is set to the value of the last call.
func (b *AgentgatewayBackendSpecApplyConfiguration) WithDynamicForwardProxy(value v1alpha1agentgateway.DynamicForwardProxyBackend) *AgentgatewayBackendSpecApplyConfiguration {
	b.DynamicForwardProxy = &value
	return b
}

// WithAws sets the Aws field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Aws field is set to the value of the last call.
func (b *AgentgatewayBackendSpecApplyConfiguration) WithAws(value *AwsBackendApplyConfiguration) *AgentgatewayBackendSpecApplyConfiguration {
	b.Aws = value
	return b
}

// WithPolicies sets the Policies field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Policies field is set to the value of the last call.
func (b *AgentgatewayBackendSpecApplyConfiguration) WithPolicies(value *BackendFullApplyConfiguration) *AgentgatewayBackendSpecApplyConfiguration {
	b.Policies = value
	return b
}
