// Code generated by applyconfiguration-gen. DO NOT EDIT.

package agentgateway

import (
	v1alpha1agentgateway "github.com/agentgateway/agentgateway/controller/api/v1alpha1/agentgateway"
)

// AgentgatewayParametersLoggingApplyConfiguration represents a declarative configuration of the AgentgatewayParametersLogging type for use
// with apply.
type AgentgatewayParametersLoggingApplyConfiguration struct {
	// Logging level in standard `RUST_LOG` syntax, for example `info` (the
	// default), or a comma-separated per-module setting such as
	// `rmcp=warn,hickory_server::server::server_future=off,typespec_client_core::http::policies::logging=warn`.
	Level  *string                                                   `json:"level,omitempty"`
	Format *v1alpha1agentgateway.AgentgatewayParametersLoggingFormat `json:"format,omitempty"`
}

// AgentgatewayParametersLoggingApplyConfiguration constructs a declarative configuration of the AgentgatewayParametersLogging type for use with
// apply.
func AgentgatewayParametersLogging() *AgentgatewayParametersLoggingApplyConfiguration {
	return &AgentgatewayParametersLoggingApplyConfiguration{}
}

// WithLevel sets the Level field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Level field is set to the value of the last call.
func (b *AgentgatewayParametersLoggingApplyConfiguration) WithLevel(value string) *AgentgatewayParametersLoggingApplyConfiguration {
	b.Level = &value
	return b
}

// WithFormat sets the Format field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Format field is set to the value of the last call.
func (b *AgentgatewayParametersLoggingApplyConfiguration) WithFormat(value v1alpha1agentgateway.AgentgatewayParametersLoggingFormat) *AgentgatewayParametersLoggingApplyConfiguration {
	b.Format = &value
	return b
}
