// Code generated by applyconfiguration-gen. DO NOT EDIT.

package agentgateway

// AIPromptGuardApplyConfiguration represents a declarative configuration of the AIPromptGuard type for use
// with apply.
//
// AIPromptGuard configures a prompt guards to block unwanted requests to the LLM provider and mask sensitive data.
// Prompt guards can be used to reject requests based on the content of the prompt, as well as
// mask responses based on the content of the response.
//
// This example rejects any request prompts that contain
// the string "credit card", and masks any credit card numbers in the response.
//
// promptGuard:
// request:
// - response:
// message: "Rejected due to inappropriate content"
// regex:
// action: REJECT
// matches:
// - pattern: "credit card"
// name: "CC"
// response:
// - regex:
// builtins:
// - CREDIT_CARD
// action: MASK
type AIPromptGuardApplyConfiguration struct {
	// Prompt guards to apply to requests sent by the client.
	Request []PromptguardRequestApplyConfiguration `json:"request,omitempty"`
	// Prompt guards to apply to responses returned by the LLM provider.
	Response []PromptguardResponseApplyConfiguration `json:"response,omitempty"`
}

// AIPromptGuardApplyConfiguration constructs a declarative configuration of the AIPromptGuard type for use with
// apply.
func AIPromptGuard() *AIPromptGuardApplyConfiguration {
	return &AIPromptGuardApplyConfiguration{}
}

// WithRequest adds the given value to the Request field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Request field.
func (b *AIPromptGuardApplyConfiguration) WithRequest(values ...*PromptguardRequestApplyConfiguration) *AIPromptGuardApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithRequest")
		}
		b.Request = append(b.Request, *values[i])
	}
	return b
}

// WithResponse adds the given value to the Response field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Response field.
func (b *AIPromptGuardApplyConfiguration) WithResponse(values ...*PromptguardResponseApplyConfiguration) *AIPromptGuardApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithResponse")
		}
		b.Response = append(b.Response, *values[i])
	}
	return b
}
