// Code generated by applyconfiguration-gen. DO NOT EDIT.

package agentgateway

// AnthropicConfigApplyConfiguration represents a declarative configuration of the AnthropicConfig type for use
// with apply.
//
// AnthropicConfig settings for the [Anthropic](https://platform.claude.com/docs/en/release-notes/overview) LLM provider.
type AnthropicConfigApplyConfiguration struct {
	// Optional: Override the model name, such as `gpt-4o-mini`.
	// If unset, the model name is taken from the request.
	Model *string `json:"model,omitempty"`
}

// AnthropicConfigApplyConfiguration constructs a declarative configuration of the AnthropicConfig type for use with
// apply.
func AnthropicConfig() *AnthropicConfigApplyConfiguration {
	return &AnthropicConfigApplyConfiguration{}
}

// WithModel sets the Model field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Model field is set to the value of the last call.
func (b *AnthropicConfigApplyConfiguration) WithModel(value string) *AnthropicConfigApplyConfiguration {
	b.Model = &value
	return b
}
