// Code generated by applyconfiguration-gen. DO NOT EDIT.

package agentgateway

import (
	v1alpha1agentgateway "github.com/agentgateway/agentgateway/controller/api/v1alpha1/agentgateway"
	v1 "k8s.io/api/core/v1"
)

// APIKeyAuthenticationApplyConfiguration represents a declarative configuration of the APIKeyAuthentication type for use
// with apply.
type APIKeyAuthenticationApplyConfiguration struct {
	// `mode` is the validation mode for API key authentication.
	Mode *v1alpha1agentgateway.APIKeyAuthenticationMode `json:"mode,omitempty"`
	// `secretRef` references a Kubernetes `Secret` storing a set of API keys.
	// If there are many keys, `secretSelector` can be used instead.
	//
	// Each entry in the `Secret` represents one API key. The key is an
	// arbitrary identifier. The value can either be:
	// * A string representing the API key.
	// * A JSON object with two fields, `key` and `metadata`. `key` contains
	// the API key. `metadata` contains arbitrary JSON metadata associated
	// with the key, which may be used by other policies. For example, you
	// may write an authorization policy allowing `apiKey.group == 'sales'`.
	//
	// Example:
	//
	// apiVersion: v1
	// kind: Secret
	// metadata:
	// name: api-key
	// stringData:
	// client1: |
	// {
	// "key": "k-123",
	// "metadata": {
	// "group": "sales",
	// "created_at": "2024-10-01T12:00:00Z"
	// }
	// }
	// client2: "k-456"
	SecretRef *v1.LocalObjectReference `json:"secretRef,omitempty"`
	// `secretSelector` selects multiple `Secret` resources containing API
	// keys. If the same key is defined in multiple secrets, the behavior is
	// undefined.
	//
	// Each entry in the `Secret` represents one API key. The key is an
	// arbitrary identifier. The value can either be:
	// * A string representing the API key.
	// * A JSON object with two fields, `key` and `metadata`. `key` contains
	// the API key. `metadata` contains arbitrary JSON metadata associated
	// with the key, which may be used by other policies. For example, you
	// may write an authorization policy allowing `apiKey.group == 'sales'`.
	//
	// Example:
	//
	// apiVersion: v1
	// kind: Secret
	// metadata:
	// name: api-key
	// stringData:
	// client1: |
	// {
	// "key": "k-123",
	// "metadata": {
	// "group": "sales",
	// "created_at": "2024-10-01T12:00:00Z"
	// }
	// }
	// client2: "k-456"
	SecretSelector *SecretSelectorApplyConfiguration `json:"secretSelector,omitempty"`
}

// APIKeyAuthenticationApplyConfiguration constructs a declarative configuration of the APIKeyAuthentication type for use with
// apply.
func APIKeyAuthentication() *APIKeyAuthenticationApplyConfiguration {
	return &APIKeyAuthenticationApplyConfiguration{}
}

// WithMode sets the Mode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Mode field is set to the value of the last call.
func (b *APIKeyAuthenticationApplyConfiguration) WithMode(value v1alpha1agentgateway.APIKeyAuthenticationMode) *APIKeyAuthenticationApplyConfiguration {
	b.Mode = &value
	return b
}

// WithSecretRef sets the SecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecretRef field is set to the value of the last call.
func (b *APIKeyAuthenticationApplyConfiguration) WithSecretRef(value v1.LocalObjectReference) *APIKeyAuthenticationApplyConfiguration {
	b.SecretRef = &value
	return b
}

// WithSecretSelector sets the SecretSelector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecretSelector field is set to the value of the last call.
func (b *APIKeyAuthenticationApplyConfiguration) WithSecretSelector(value *SecretSelectorApplyConfiguration) *APIKeyAuthenticationApplyConfiguration {
	b.SecretSelector = value
	return b
}
