// Code generated by applyconfiguration-gen. DO NOT EDIT.

package agentgateway

import (
	shared "github.com/agentgateway/agentgateway/controller/api/v1alpha1/shared"
)

// AttributeAddApplyConfiguration represents a declarative configuration of the AttributeAdd type for use
// with apply.
type AttributeAddApplyConfiguration struct {
	Name       *string               `json:"name,omitempty"`
	Expression *shared.CELExpression `json:"expression,omitempty"`
}

// AttributeAddApplyConfiguration constructs a declarative configuration of the AttributeAdd type for use with
// apply.
func AttributeAdd() *AttributeAddApplyConfiguration {
	return &AttributeAddApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *AttributeAddApplyConfiguration) WithName(value string) *AttributeAddApplyConfiguration {
	b.Name = &value
	return b
}

// WithExpression sets the Expression field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Expression field is set to the value of the last call.
func (b *AttributeAddApplyConfiguration) WithExpression(value shared.CELExpression) *AttributeAddApplyConfiguration {
	b.Expression = &value
	return b
}
