// Code generated by applyconfiguration-gen. DO NOT EDIT.

package agentgateway

// AwsAgentCoreBackendApplyConfiguration represents a declarative configuration of the AwsAgentCoreBackend type for use
// with apply.
//
// AwsAgentCoreBackend configures Amazon Bedrock AgentCore.
type AwsAgentCoreBackendApplyConfiguration struct {
	// agentRuntimeArn is the ARN of the AgentCore runtime.
	AgentRuntimeArn *string `json:"agentRuntimeArn,omitempty"`
	// qualifier optionally specifies the alias or version qualifier.
	Qualifier *string `json:"qualifier,omitempty"`
}

// AwsAgentCoreBackendApplyConfiguration constructs a declarative configuration of the AwsAgentCoreBackend type for use with
// apply.
func AwsAgentCoreBackend() *AwsAgentCoreBackendApplyConfiguration {
	return &AwsAgentCoreBackendApplyConfiguration{}
}

// WithAgentRuntimeArn sets the AgentRuntimeArn field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AgentRuntimeArn field is set to the value of the last call.
func (b *AwsAgentCoreBackendApplyConfiguration) WithAgentRuntimeArn(value string) *AwsAgentCoreBackendApplyConfiguration {
	b.AgentRuntimeArn = &value
	return b
}

// WithQualifier sets the Qualifier field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Qualifier field is set to the value of the last call.
func (b *AwsAgentCoreBackendApplyConfiguration) WithQualifier(value string) *AwsAgentCoreBackendApplyConfiguration {
	b.Qualifier = &value
	return b
}
