// Code generated by applyconfiguration-gen. DO NOT EDIT.

package agentgateway

// AwsBackendApplyConfiguration represents a declarative configuration of the AwsBackend type for use
// with apply.
//
// AwsBackend configures an AWS service backend.
type AwsBackendApplyConfiguration struct {
	// agentCore configures Amazon Bedrock AgentCore as a backend.
	AgentCore *AwsAgentCoreBackendApplyConfiguration `json:"agentCore,omitempty"`
}

// AwsBackendApplyConfiguration constructs a declarative configuration of the AwsBackend type for use with
// apply.
func AwsBackend() *AwsBackendApplyConfiguration {
	return &AwsBackendApplyConfiguration{}
}

// WithAgentCore sets the AgentCore field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AgentCore field is set to the value of the last call.
func (b *AwsBackendApplyConfiguration) WithAgentCore(value *AwsAgentCoreBackendApplyConfiguration) *AwsBackendApplyConfiguration {
	b.AgentCore = value
	return b
}
