// Code generated by applyconfiguration-gen. DO NOT EDIT.

package agentgateway

// AzureManagedIdentityApplyConfiguration represents a declarative configuration of the AzureManagedIdentity type for use
// with apply.
type AzureManagedIdentityApplyConfiguration struct {
	ClientID   *string `json:"clientId,omitempty"`
	ObjectID   *string `json:"objectId,omitempty"`
	ResourceID *string `json:"resourceId,omitempty"`
}

// AzureManagedIdentityApplyConfiguration constructs a declarative configuration of the AzureManagedIdentity type for use with
// apply.
func AzureManagedIdentity() *AzureManagedIdentityApplyConfiguration {
	return &AzureManagedIdentityApplyConfiguration{}
}

// WithClientID sets the ClientID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClientID field is set to the value of the last call.
func (b *AzureManagedIdentityApplyConfiguration) WithClientID(value string) *AzureManagedIdentityApplyConfiguration {
	b.ClientID = &value
	return b
}

// WithObjectID sets the ObjectID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObjectID field is set to the value of the last call.
func (b *AzureManagedIdentityApplyConfiguration) WithObjectID(value string) *AzureManagedIdentityApplyConfiguration {
	b.ObjectID = &value
	return b
}

// WithResourceID sets the ResourceID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ResourceID field is set to the value of the last call.
func (b *AzureManagedIdentityApplyConfiguration) WithResourceID(value string) *AzureManagedIdentityApplyConfiguration {
	b.ResourceID = &value
	return b
}
