// Code generated by applyconfiguration-gen. DO NOT EDIT.

package agentgateway

import (
	v1alpha1agentgateway "github.com/agentgateway/agentgateway/controller/api/v1alpha1/agentgateway"
)

// AzureConfigApplyConfiguration represents a declarative configuration of the AzureConfig type for use
// with apply.
//
// AzureConfig settings for Azure AI backends, supporting both Azure OpenAI and Azure AI Foundry.
type AzureConfigApplyConfiguration struct {
	// The Azure resource name used to construct the endpoint host.
	// For OpenAI: {resourceName}.openai.azure.com
	// For Foundry: {resourceName}-resource.services.ai.azure.com
	ResourceName *string `json:"resourceName,omitempty"`
	// The type of Azure endpoint. Determines the host suffix.
	ResourceType *v1alpha1agentgateway.AzureResourceType `json:"resourceType,omitempty"`
	// Optional: Override the model name, such as `gpt-4o-mini`.
	// If unset, the model name is taken from the request.
	Model *string `json:"model,omitempty"`
	// The version of the Azure OpenAI API to use.
	// If unset, defaults to `v1`.
	ApiVersion *string `json:"apiVersion,omitempty"`
	// The Foundry project name, required when `resourceType` is `Foundry`.
	// Used to construct paths: /api/projects/{projectName}/openai/v1/...
	ProjectName *string `json:"projectName,omitempty"`
}

// AzureConfigApplyConfiguration constructs a declarative configuration of the AzureConfig type for use with
// apply.
func AzureConfig() *AzureConfigApplyConfiguration {
	return &AzureConfigApplyConfiguration{}
}

// WithResourceName sets the ResourceName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ResourceName field is set to the value of the last call.
func (b *AzureConfigApplyConfiguration) WithResourceName(value string) *AzureConfigApplyConfiguration {
	b.ResourceName = &value
	return b
}

// WithResourceType sets the ResourceType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ResourceType field is set to the value of the last call.
func (b *AzureConfigApplyConfiguration) WithResourceType(value v1alpha1agentgateway.AzureResourceType) *AzureConfigApplyConfiguration {
	b.ResourceType = &value
	return b
}

// WithModel sets the Model field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Model field is set to the value of the last call.
func (b *AzureConfigApplyConfiguration) WithModel(value string) *AzureConfigApplyConfiguration {
	b.Model = &value
	return b
}

// WithApiVersion sets the ApiVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ApiVersion field is set to the value of the last call.
func (b *AzureConfigApplyConfiguration) WithApiVersion(value string) *AzureConfigApplyConfiguration {
	b.ApiVersion = &value
	return b
}

// WithProjectName sets the ProjectName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProjectName field is set to the value of the last call.
func (b *AzureConfigApplyConfiguration) WithProjectName(value string) *AzureConfigApplyConfiguration {
	b.ProjectName = &value
	return b
}
