// Code generated by applyconfiguration-gen. DO NOT EDIT.

package agentgateway

import (
	v1 "k8s.io/api/core/v1"
)

// AzureAuthApplyConfiguration represents a declarative configuration of the AzureAuth type for use
// with apply.
type AzureAuthApplyConfiguration struct {
	// `secretRef` references a Kubernetes `Secret` containing the Azure
	// credentials. The `Secret` must have keys `clientId`, `tenantId`, and
	// `clientSecret`.
	SecretRef *v1.LocalObjectReference `json:"secretRef,omitempty"`
	// Details for managed identity authentication
	ManagedIdentity *AzureManagedIdentityApplyConfiguration `json:"managedIdentity,omitempty"`
}

// AzureAuthApplyConfiguration constructs a declarative configuration of the AzureAuth type for use with
// apply.
func AzureAuth() *AzureAuthApplyConfiguration {
	return &AzureAuthApplyConfiguration{}
}

// WithSecretRef sets the SecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecretRef field is set to the value of the last call.
func (b *AzureAuthApplyConfiguration) WithSecretRef(value v1.LocalObjectReference) *AzureAuthApplyConfiguration {
	b.SecretRef = &value
	return b
}

// WithManagedIdentity sets the ManagedIdentity field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ManagedIdentity field is set to the value of the last call.
func (b *AzureAuthApplyConfiguration) WithManagedIdentity(value *AzureManagedIdentityApplyConfiguration) *AzureAuthApplyConfiguration {
	b.ManagedIdentity = value
	return b
}
