// Code generated by applyconfiguration-gen. DO NOT EDIT.

package agentgateway

// AzureOpenAIConfigApplyConfiguration represents a declarative configuration of the AzureOpenAIConfig type for use
// with apply.
//
// AzureOpenAIConfig settings for the [Azure OpenAI](https://learn.microsoft.com/en-us/azure/foundry/?view=foundry-classic) LLM provider.
type AzureOpenAIConfigApplyConfiguration struct {
	// The endpoint for the Azure OpenAI API to use, such as `my-endpoint.openai.azure.com`.
	// If the scheme is included, it is stripped.
	Endpoint *string `json:"endpoint,omitempty"`
	// The name of the Azure OpenAI model deployment to use.
	// For more information, see the [Azure OpenAI model docs](https://learn.microsoft.com/en-us/azure/foundry/foundry-models/concepts/models-sold-directly-by-azure?view=foundry-classic).
	// This is required if `apiVersion` is not `v1`. For `v1`, the model can be
	// set in the request.
	DeploymentName *string `json:"deploymentName,omitempty"`
	// The version of the Azure OpenAI API to use.
	// For more information, see the [Azure OpenAI API version reference](https://learn.microsoft.com/en-us/azure/foundry/openai/reference).
	// If unset, defaults to `v1`.
	ApiVersion *string `json:"apiVersion,omitempty"`
}

// AzureOpenAIConfigApplyConfiguration constructs a declarative configuration of the AzureOpenAIConfig type for use with
// apply.
func AzureOpenAIConfig() *AzureOpenAIConfigApplyConfiguration {
	return &AzureOpenAIConfigApplyConfiguration{}
}

// WithEndpoint sets the Endpoint field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Endpoint field is set to the value of the last call.
func (b *AzureOpenAIConfigApplyConfiguration) WithEndpoint(value string) *AzureOpenAIConfigApplyConfiguration {
	b.Endpoint = &value
	return b
}

// WithDeploymentName sets the DeploymentName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeploymentName field is set to the value of the last call.
func (b *AzureOpenAIConfigApplyConfiguration) WithDeploymentName(value string) *AzureOpenAIConfigApplyConfiguration {
	b.DeploymentName = &value
	return b
}

// WithApiVersion sets the ApiVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ApiVersion field is set to the value of the last call.
func (b *AzureOpenAIConfigApplyConfiguration) WithApiVersion(value string) *AzureOpenAIConfigApplyConfiguration {
	b.ApiVersion = &value
	return b
}
