// Code generated by applyconfiguration-gen. DO NOT EDIT.

package agentgateway

// BackendFullApplyConfiguration represents a declarative configuration of the BackendFull type for use
// with apply.
type BackendFullApplyConfiguration struct {
	BackendSimpleApplyConfiguration `json:",inline"`
	// `ai` specifies settings for AI workloads. This is only applicable when
	// connecting to a `Backend` of type `ai`.
	AI *BackendAIApplyConfiguration `json:"ai,omitempty"`
	// `mcp` specifies settings for MCP workloads. This is only applicable when
	// connecting to a `Backend` of type `mcp`.
	//
	// This field is deprecated; prefer to use traffic policy `jwtAuthentication.mcp`, which ensures authentication runs before
	// other policies such as transformation and rate limiting.
	MCP *BackendMCPApplyConfiguration `json:"mcp,omitempty"`
}

// BackendFullApplyConfiguration constructs a declarative configuration of the BackendFull type for use with
// apply.
func BackendFull() *BackendFullApplyConfiguration {
	return &BackendFullApplyConfiguration{}
}

// WithTCP sets the TCP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TCP field is set to the value of the last call.
func (b *BackendFullApplyConfiguration) WithTCP(value *BackendTCPApplyConfiguration) *BackendFullApplyConfiguration {
	b.BackendSimpleApplyConfiguration.TCP = value
	return b
}

// WithTLS sets the TLS field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TLS field is set to the value of the last call.
func (b *BackendFullApplyConfiguration) WithTLS(value *BackendTLSApplyConfiguration) *BackendFullApplyConfiguration {
	b.BackendSimpleApplyConfiguration.TLS = value
	return b
}

// WithHTTP sets the HTTP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HTTP field is set to the value of the last call.
func (b *BackendFullApplyConfiguration) WithHTTP(value *BackendHTTPApplyConfiguration) *BackendFullApplyConfiguration {
	b.BackendSimpleApplyConfiguration.HTTP = value
	return b
}

// WithTunnel sets the Tunnel field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Tunnel field is set to the value of the last call.
func (b *BackendFullApplyConfiguration) WithTunnel(value *BackendTunnelApplyConfiguration) *BackendFullApplyConfiguration {
	b.BackendSimpleApplyConfiguration.Tunnel = value
	return b
}

// WithTransformation sets the Transformation field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Transformation field is set to the value of the last call.
func (b *BackendFullApplyConfiguration) WithTransformation(value *TransformationApplyConfiguration) *BackendFullApplyConfiguration {
	b.BackendSimpleApplyConfiguration.Transformation = value
	return b
}

// WithAuth sets the Auth field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Auth field is set to the value of the last call.
func (b *BackendFullApplyConfiguration) WithAuth(value *BackendAuthApplyConfiguration) *BackendFullApplyConfiguration {
	b.BackendSimpleApplyConfiguration.Auth = value
	return b
}

// WithHealth sets the Health field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Health field is set to the value of the last call.
func (b *BackendFullApplyConfiguration) WithHealth(value *HealthApplyConfiguration) *BackendFullApplyConfiguration {
	b.BackendSimpleApplyConfiguration.Health = value
	return b
}

// WithAI sets the AI field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AI field is set to the value of the last call.
func (b *BackendFullApplyConfiguration) WithAI(value *BackendAIApplyConfiguration) *BackendFullApplyConfiguration {
	b.AI = value
	return b
}

// WithMCP sets the MCP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MCP field is set to the value of the last call.
func (b *BackendFullApplyConfiguration) WithMCP(value *BackendMCPApplyConfiguration) *BackendFullApplyConfiguration {
	b.MCP = value
	return b
}
