// Code generated by applyconfiguration-gen. DO NOT EDIT.

package agentgateway

import (
	v1alpha1agentgateway "github.com/agentgateway/agentgateway/controller/api/v1alpha1/agentgateway"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// BackendHTTPApplyConfiguration represents a declarative configuration of the BackendHTTP type for use
// with apply.
type BackendHTTPApplyConfiguration struct {
	// `version` specifies the HTTP protocol version to use when connecting to
	// the backend.
	// If not specified, the version is automatically determined:
	// * `Service` types can specify it with `appProtocol` on the `Service`
	// port.
	// * If traffic is identified as gRPC, `HTTP2` is used.
	// * If the incoming traffic was plaintext HTTP, the original protocol will
	// be used.
	// * If the incoming traffic was HTTPS, `HTTP1` will be used. This is
	// because most clients will transparently upgrade HTTPS traffic to
	// `HTTP2`, even if the backend doesn't support it.
	Version *v1alpha1agentgateway.HTTPVersion `json:"version,omitempty"`
	// requestTimeout specifies the deadline for receiving a response from the backend.
	RequestTimeout *v1.Duration `json:"requestTimeout,omitempty"`
}

// BackendHTTPApplyConfiguration constructs a declarative configuration of the BackendHTTP type for use with
// apply.
func BackendHTTP() *BackendHTTPApplyConfiguration {
	return &BackendHTTPApplyConfiguration{}
}

// WithVersion sets the Version field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Version field is set to the value of the last call.
func (b *BackendHTTPApplyConfiguration) WithVersion(value v1alpha1agentgateway.HTTPVersion) *BackendHTTPApplyConfiguration {
	b.Version = &value
	return b
}

// WithRequestTimeout sets the RequestTimeout field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RequestTimeout field is set to the value of the last call.
func (b *BackendHTTPApplyConfiguration) WithRequestTimeout(value v1.Duration) *BackendHTTPApplyConfiguration {
	b.RequestTimeout = &value
	return b
}
