// Code generated by applyconfiguration-gen. DO NOT EDIT.

package agentgateway

import (
	v1 "sigs.k8s.io/gateway-api/apis/v1"
)

// BackendTunnelApplyConfiguration represents a declarative configuration of the BackendTunnel type for use
// with apply.
type BackendTunnelApplyConfiguration struct {
	// `backendRef` references the proxy server to reach.
	// Supported types: `Service` and `Backend`.
	BackendRef *v1.BackendObjectReference `json:"backendRef,omitempty"`
}

// BackendTunnelApplyConfiguration constructs a declarative configuration of the BackendTunnel type for use with
// apply.
func BackendTunnel() *BackendTunnelApplyConfiguration {
	return &BackendTunnelApplyConfiguration{}
}

// WithBackendRef sets the BackendRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BackendRef field is set to the value of the last call.
func (b *BackendTunnelApplyConfiguration) WithBackendRef(value v1.BackendObjectReference) *BackendTunnelApplyConfiguration {
	b.BackendRef = &value
	return b
}
