// Code generated by applyconfiguration-gen. DO NOT EDIT.

package agentgateway

// BackendSimpleApplyConfiguration represents a declarative configuration of the BackendSimple type for use
// with apply.
type BackendSimpleApplyConfiguration struct {
	// tcp defines settings for managing TCP connections to the backend.
	TCP *BackendTCPApplyConfiguration `json:"tcp,omitempty"`
	// tls defines settings for managing TLS connections to the backend.
	//
	// If this field is set, TLS will be initiated to the backend; the system trusted CA certificates will be used to
	// validate the server, and the SNI will automatically be set based on the destination.
	TLS *BackendTLSApplyConfiguration `json:"tls,omitempty"`
	// http defines settings for managing HTTP requests to the backend.
	HTTP *BackendHTTPApplyConfiguration `json:"http,omitempty"`
	// `tunnel` defines settings for managing tunnel connections (with behavior like `HTTPS_PROXY`) to the backend.
	Tunnel *BackendTunnelApplyConfiguration `json:"tunnel,omitempty"`
	// transformation is used to mutate and transform requests and responses sent to and from the backend.
	Transformation *TransformationApplyConfiguration `json:"transformation,omitempty"`
	// `auth` defines settings for managing authentication to the backend.
	Auth *BackendAuthApplyConfiguration `json:"auth,omitempty"`
	// health defines settings for passive and active health checking.
	Health *HealthApplyConfiguration `json:"health,omitempty"`
}

// BackendSimpleApplyConfiguration constructs a declarative configuration of the BackendSimple type for use with
// apply.
func BackendSimple() *BackendSimpleApplyConfiguration {
	return &BackendSimpleApplyConfiguration{}
}

// WithTCP sets the TCP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TCP field is set to the value of the last call.
func (b *BackendSimpleApplyConfiguration) WithTCP(value *BackendTCPApplyConfiguration) *BackendSimpleApplyConfiguration {
	b.TCP = value
	return b
}

// WithTLS sets the TLS field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TLS field is set to the value of the last call.
func (b *BackendSimpleApplyConfiguration) WithTLS(value *BackendTLSApplyConfiguration) *BackendSimpleApplyConfiguration {
	b.TLS = value
	return b
}

// WithHTTP sets the HTTP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HTTP field is set to the value of the last call.
func (b *BackendSimpleApplyConfiguration) WithHTTP(value *BackendHTTPApplyConfiguration) *BackendSimpleApplyConfiguration {
	b.HTTP = value
	return b
}

// WithTunnel sets the Tunnel field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Tunnel field is set to the value of the last call.
func (b *BackendSimpleApplyConfiguration) WithTunnel(value *BackendTunnelApplyConfiguration) *BackendSimpleApplyConfiguration {
	b.Tunnel = value
	return b
}

// WithTransformation sets the Transformation field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Transformation field is set to the value of the last call.
func (b *BackendSimpleApplyConfiguration) WithTransformation(value *TransformationApplyConfiguration) *BackendSimpleApplyConfiguration {
	b.Transformation = value
	return b
}

// WithAuth sets the Auth field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Auth field is set to the value of the last call.
func (b *BackendSimpleApplyConfiguration) WithAuth(value *BackendAuthApplyConfiguration) *BackendSimpleApplyConfiguration {
	b.Auth = value
	return b
}

// WithHealth sets the Health field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Health field is set to the value of the last call.
func (b *BackendSimpleApplyConfiguration) WithHealth(value *HealthApplyConfiguration) *BackendSimpleApplyConfiguration {
	b.Health = value
	return b
}
