// Code generated by applyconfiguration-gen. DO NOT EDIT.

package agentgateway

import (
	v1alpha1agentgateway "github.com/agentgateway/agentgateway/controller/api/v1alpha1/agentgateway"
	v1 "k8s.io/api/core/v1"
)

// BackendAuthApplyConfiguration represents a declarative configuration of the BackendAuth type for use
// with apply.
type BackendAuthApplyConfiguration struct {
	// `key` provides an inline key to use as the value of the
	// `Authorization` header. This option is the least secure; usage of a
	// `Secret` is preferred.
	InlineKey *string `json:"key,omitempty"`
	// `secretRef` references a Kubernetes `Secret` storing the key to use as
	// the authorization value. This must be stored in the `Authorization` key.
	SecretRef *v1.LocalObjectReference `json:"secretRef,omitempty"`
	// `passthrough` passes through an existing token that has been sent by the
	// client and validated. Other policies, like JWT and API key
	// authentication, will strip the original client credentials. Passthrough backend authentication
	// causes the original token to be added back into the request. If there are no client authentication policies on the
	// request, the original token would be unchanged, so this would have no effect.
	Passthrough *v1alpha1agentgateway.BackendAuthPassthrough `json:"passthrough,omitempty"`
	// Auth specifies an explicit AWS authentication method for the backend.
	// When omitted, we will try to use the default AWS SDK authentication methods.
	AWS *AwsAuthApplyConfiguration `json:"aws,omitempty"`
	// Azure specifies an Azure authentication method for the backend.
	Azure *AzureAuthApplyConfiguration `json:"azure,omitempty"`
	// Auth specifies to use a Google  authentication method for the backend.
	// When omitted, we will try to use the default AWS SDK authentication methods.
	GCP *GcpAuthApplyConfiguration `json:"gcp,omitempty"`
}

// BackendAuthApplyConfiguration constructs a declarative configuration of the BackendAuth type for use with
// apply.
func BackendAuth() *BackendAuthApplyConfiguration {
	return &BackendAuthApplyConfiguration{}
}

// WithInlineKey sets the InlineKey field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InlineKey field is set to the value of the last call.
func (b *BackendAuthApplyConfiguration) WithInlineKey(value string) *BackendAuthApplyConfiguration {
	b.InlineKey = &value
	return b
}

// WithSecretRef sets the SecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecretRef field is set to the value of the last call.
func (b *BackendAuthApplyConfiguration) WithSecretRef(value v1.LocalObjectReference) *BackendAuthApplyConfiguration {
	b.SecretRef = &value
	return b
}

// WithPassthrough sets the Passthrough field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Passthrough field is set to the value of the last call.
func (b *BackendAuthApplyConfiguration) WithPassthrough(value v1alpha1agentgateway.BackendAuthPassthrough) *BackendAuthApplyConfiguration {
	b.Passthrough = &value
	return b
}

// WithAWS sets the AWS field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AWS field is set to the value of the last call.
func (b *BackendAuthApplyConfiguration) WithAWS(value *AwsAuthApplyConfiguration) *BackendAuthApplyConfiguration {
	b.AWS = value
	return b
}

// WithAzure sets the Azure field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Azure field is set to the value of the last call.
func (b *BackendAuthApplyConfiguration) WithAzure(value *AzureAuthApplyConfiguration) *BackendAuthApplyConfiguration {
	b.Azure = value
	return b
}

// WithGCP sets the GCP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GCP field is set to the value of the last call.
func (b *BackendAuthApplyConfiguration) WithGCP(value *GcpAuthApplyConfiguration) *BackendAuthApplyConfiguration {
	b.GCP = value
	return b
}
