// Code generated by applyconfiguration-gen. DO NOT EDIT.

package agentgateway

import (
	v1alpha1agentgateway "github.com/agentgateway/agentgateway/controller/api/v1alpha1/agentgateway"
)

// BackendAIApplyConfiguration represents a declarative configuration of the BackendAI type for use
// with apply.
type BackendAIApplyConfiguration struct {
	// Enrich requests sent to the LLM provider by appending and prepending system prompts. This can be configured only for
	// LLM providers that use the `CHAT` or `CHAT_STREAMING` API route type.
	PromptEnrichment *AIPromptEnrichmentApplyConfiguration `json:"prompt,omitempty"`
	// `promptGuard` enables adding guardrails to LLM requests and responses.
	PromptGuard *AIPromptGuardApplyConfiguration `json:"promptGuard,omitempty"`
	// Provide defaults to merge with user input fields. If the field is already set, the field in the request is used.
	Defaults []FieldDefaultApplyConfiguration `json:"defaults,omitempty"`
	// Provide overrides to merge with user input fields. If the field is already set, the field will be overwritten.
	Overrides []FieldDefaultApplyConfiguration `json:"overrides,omitempty"`
	// Provide CEL transformations to compute and set fields in the request body.
	// The expression result overwrites any existing value for that field.
	// This has a higher priority than `overrides` if both are set for the same
	// key.
	Transformations []FieldTransformationApplyConfiguration `json:"transformations,omitempty"`
	// ModelAliases maps friendly model names to actual provider model names.
	// Example: `{"fast": "gpt-3.5-turbo", "smart": "gpt-4-turbo"}`.
	// Note: This field is only applicable when using the agentgateway data plane.
	ModelAliases map[string]string `json:"modelAliases,omitempty"`
	// `promptCaching` enables automatic prompt caching for supported
	// providers, currently AWS Bedrock.
	// Reduces API costs by caching static content like system prompts and tool definitions.
	// Only applicable for Bedrock Claude 3+ and Nova models.
	PromptCaching *PromptCachingConfigApplyConfiguration `json:"promptCaching,omitempty"`
	// `routes` defines how to identify the type of traffic to handle.
	// The keys are URL path suffixes matched using ends-with comparison, for
	// example `"/v1/chat/completions"`.
	// The special `*` wildcard matches any path.
	// If not specified, all traffic defaults to `completions` type.
	Routes map[string]v1alpha1agentgateway.RouteType `json:"routes,omitempty"`
}

// BackendAIApplyConfiguration constructs a declarative configuration of the BackendAI type for use with
// apply.
func BackendAI() *BackendAIApplyConfiguration {
	return &BackendAIApplyConfiguration{}
}

// WithPromptEnrichment sets the PromptEnrichment field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PromptEnrichment field is set to the value of the last call.
func (b *BackendAIApplyConfiguration) WithPromptEnrichment(value *AIPromptEnrichmentApplyConfiguration) *BackendAIApplyConfiguration {
	b.PromptEnrichment = value
	return b
}

// WithPromptGuard sets the PromptGuard field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PromptGuard field is set to the value of the last call.
func (b *BackendAIApplyConfiguration) WithPromptGuard(value *AIPromptGuardApplyConfiguration) *BackendAIApplyConfiguration {
	b.PromptGuard = value
	return b
}

// WithDefaults adds the given value to the Defaults field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Defaults field.
func (b *BackendAIApplyConfiguration) WithDefaults(values ...*FieldDefaultApplyConfiguration) *BackendAIApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithDefaults")
		}
		b.Defaults = append(b.Defaults, *values[i])
	}
	return b
}

// WithOverrides adds the given value to the Overrides field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Overrides field.
func (b *BackendAIApplyConfiguration) WithOverrides(values ...*FieldDefaultApplyConfiguration) *BackendAIApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithOverrides")
		}
		b.Overrides = append(b.Overrides, *values[i])
	}
	return b
}

// WithTransformations adds the given value to the Transformations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Transformations field.
func (b *BackendAIApplyConfiguration) WithTransformations(values ...*FieldTransformationApplyConfiguration) *BackendAIApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithTransformations")
		}
		b.Transformations = append(b.Transformations, *values[i])
	}
	return b
}

// WithModelAliases puts the entries into the ModelAliases field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the ModelAliases field,
// overwriting an existing map entries in ModelAliases field with the same key.
func (b *BackendAIApplyConfiguration) WithModelAliases(entries map[string]string) *BackendAIApplyConfiguration {
	if b.ModelAliases == nil && len(entries) > 0 {
		b.ModelAliases = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ModelAliases[k] = v
	}
	return b
}

// WithPromptCaching sets the PromptCaching field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PromptCaching field is set to the value of the last call.
func (b *BackendAIApplyConfiguration) WithPromptCaching(value *PromptCachingConfigApplyConfiguration) *BackendAIApplyConfiguration {
	b.PromptCaching = value
	return b
}

// WithRoutes puts the entries into the Routes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Routes field,
// overwriting an existing map entries in Routes field with the same key.
func (b *BackendAIApplyConfiguration) WithRoutes(entries map[string]v1alpha1agentgateway.RouteType) *BackendAIApplyConfiguration {
	if b.Routes == nil && len(entries) > 0 {
		b.Routes = make(map[string]v1alpha1agentgateway.RouteType, len(entries))
	}
	for k, v := range entries {
		b.Routes[k] = v
	}
	return b
}
