// Code generated by applyconfiguration-gen. DO NOT EDIT.

package agentgateway

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// BackendEvictionApplyConfiguration represents a declarative configuration of the BackendEviction type for use
// with apply.
//
// BackendEviction defines settings for evicting unhealthy backends.
type BackendEvictionApplyConfiguration struct {
	// Duration specifies the base time a backend should be evicted after being marked unhealthy.
	// Subsequent evictions use multiplicative backoff (duration * times_evicted).
	// If all endpoints are evicted, the load balancer falls back to returning evicted endpoints
	// rather than failing entirely.
	// If unset, defaults to `3s`.
	Duration *v1.Duration `json:"duration,omitempty"`
	// RestoreHealth is the health score (0–100) assigned to a backend when it returns from eviction.
	// For gradual recovery, set below 100; for full recovery immediately, set 100.
	// If unset, the backend resumes with the health it had when evicted.
	RestoreHealth *int32 `json:"restoreHealth,omitempty"`
	// ConsecutiveFailures is the number of consecutive unhealthy responses required before the backend is evicted.
	// For example, a value of 5 means the backend must receive 5 unhealthy responses in a row before being evicted.
	// When both consecutiveFailures and healthThreshold are set, the backend is evicted when either condition is met.
	// When neither is set, a single unhealthy response can trigger eviction.
	ConsecutiveFailures *int32 `json:"consecutiveFailures,omitempty"`
	// HealthThreshold is the EWMA (exponentially-weighted moving average) health score threshold, expressed as 0–100.
	// When set, a backend is only evicted if its computed health drops below this value after an unhealthy response.
	// For example, 50 means the backend is evicted when its EWMA health falls below 50% following failures.
	// Unlike consecutiveFailures (which counts consecutive failures), this uses a sliding-window average
	// so a single success in a stream of failures can delay eviction.
	// When both consecutiveFailures and healthThreshold are set, the backend is evicted when either condition is met.
	// When neither is set, a single unhealthy response triggers eviction.
	HealthThreshold *int32 `json:"healthThreshold,omitempty"`
}

// BackendEvictionApplyConfiguration constructs a declarative configuration of the BackendEviction type for use with
// apply.
func BackendEviction() *BackendEvictionApplyConfiguration {
	return &BackendEvictionApplyConfiguration{}
}

// WithDuration sets the Duration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Duration field is set to the value of the last call.
func (b *BackendEvictionApplyConfiguration) WithDuration(value v1.Duration) *BackendEvictionApplyConfiguration {
	b.Duration = &value
	return b
}

// WithRestoreHealth sets the RestoreHealth field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RestoreHealth field is set to the value of the last call.
func (b *BackendEvictionApplyConfiguration) WithRestoreHealth(value int32) *BackendEvictionApplyConfiguration {
	b.RestoreHealth = &value
	return b
}

// WithConsecutiveFailures sets the ConsecutiveFailures field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ConsecutiveFailures field is set to the value of the last call.
func (b *BackendEvictionApplyConfiguration) WithConsecutiveFailures(value int32) *BackendEvictionApplyConfiguration {
	b.ConsecutiveFailures = &value
	return b
}

// WithHealthThreshold sets the HealthThreshold field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HealthThreshold field is set to the value of the last call.
func (b *BackendEvictionApplyConfiguration) WithHealthThreshold(value int32) *BackendEvictionApplyConfiguration {
	b.HealthThreshold = &value
	return b
}
