// Code generated by applyconfiguration-gen. DO NOT EDIT.

package agentgateway

import (
	shared "github.com/agentgateway/agentgateway/controller/api/v1alpha1/shared"
)

// BackendMCPApplyConfiguration represents a declarative configuration of the BackendMCP type for use
// with apply.
type BackendMCPApplyConfiguration struct {
	// authorization defines MCPBackend level authorization. Unlike authorization at the HTTP level, which will reject
	// unauthorized requests with a `403` error, this policy works at the
	// `MCPBackend` level.
	//
	// List operations, such as `list_tools`, will have each item evaluated.
	// Items that do not meet the rule will be filtered.
	//
	// Get or call operations, such as `call_tool`, will evaluate the specific
	// item and reject requests that do not meet the rule.
	Authorization *shared.Authorization `json:"authorization,omitempty"`
	// `authentication` defines `MCPBackend`-specific authentication rules.
	Authentication *MCPAuthenticationApplyConfiguration `json:"authentication,omitempty"`
}

// BackendMCPApplyConfiguration constructs a declarative configuration of the BackendMCP type for use with
// apply.
func BackendMCP() *BackendMCPApplyConfiguration {
	return &BackendMCPApplyConfiguration{}
}

// WithAuthorization sets the Authorization field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Authorization field is set to the value of the last call.
func (b *BackendMCPApplyConfiguration) WithAuthorization(value shared.Authorization) *BackendMCPApplyConfiguration {
	b.Authorization = &value
	return b
}

// WithAuthentication sets the Authentication field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Authentication field is set to the value of the last call.
func (b *BackendMCPApplyConfiguration) WithAuthentication(value *MCPAuthenticationApplyConfiguration) *BackendMCPApplyConfiguration {
	b.Authentication = value
	return b
}
