// Code generated by applyconfiguration-gen. DO NOT EDIT.

package agentgateway

// BackendWithAIApplyConfiguration represents a declarative configuration of the BackendWithAI type for use
// with apply.
type BackendWithAIApplyConfiguration struct {
	BackendSimpleApplyConfiguration `json:",inline"`
	// `ai` specifies settings for AI workloads. This is only applicable when
	// connecting to a `Backend` of type `ai`.
	AI *BackendAIApplyConfiguration `json:"ai,omitempty"`
}

// BackendWithAIApplyConfiguration constructs a declarative configuration of the BackendWithAI type for use with
// apply.
func BackendWithAI() *BackendWithAIApplyConfiguration {
	return &BackendWithAIApplyConfiguration{}
}

// WithTCP sets the TCP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TCP field is set to the value of the last call.
func (b *BackendWithAIApplyConfiguration) WithTCP(value *BackendTCPApplyConfiguration) *BackendWithAIApplyConfiguration {
	b.BackendSimpleApplyConfiguration.TCP = value
	return b
}

// WithTLS sets the TLS field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TLS field is set to the value of the last call.
func (b *BackendWithAIApplyConfiguration) WithTLS(value *BackendTLSApplyConfiguration) *BackendWithAIApplyConfiguration {
	b.BackendSimpleApplyConfiguration.TLS = value
	return b
}

// WithHTTP sets the HTTP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HTTP field is set to the value of the last call.
func (b *BackendWithAIApplyConfiguration) WithHTTP(value *BackendHTTPApplyConfiguration) *BackendWithAIApplyConfiguration {
	b.BackendSimpleApplyConfiguration.HTTP = value
	return b
}

// WithTunnel sets the Tunnel field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Tunnel field is set to the value of the last call.
func (b *BackendWithAIApplyConfiguration) WithTunnel(value *BackendTunnelApplyConfiguration) *BackendWithAIApplyConfiguration {
	b.BackendSimpleApplyConfiguration.Tunnel = value
	return b
}

// WithTransformation sets the Transformation field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Transformation field is set to the value of the last call.
func (b *BackendWithAIApplyConfiguration) WithTransformation(value *TransformationApplyConfiguration) *BackendWithAIApplyConfiguration {
	b.BackendSimpleApplyConfiguration.Transformation = value
	return b
}

// WithAuth sets the Auth field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Auth field is set to the value of the last call.
func (b *BackendWithAIApplyConfiguration) WithAuth(value *BackendAuthApplyConfiguration) *BackendWithAIApplyConfiguration {
	b.BackendSimpleApplyConfiguration.Auth = value
	return b
}

// WithHealth sets the Health field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Health field is set to the value of the last call.
func (b *BackendWithAIApplyConfiguration) WithHealth(value *HealthApplyConfiguration) *BackendWithAIApplyConfiguration {
	b.BackendSimpleApplyConfiguration.Health = value
	return b
}

// WithAI sets the AI field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AI field is set to the value of the last call.
func (b *BackendWithAIApplyConfiguration) WithAI(value *BackendAIApplyConfiguration) *BackendWithAIApplyConfiguration {
	b.AI = value
	return b
}
