// Code generated by applyconfiguration-gen. DO NOT EDIT.

package agentgateway

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// BackendTCPApplyConfiguration represents a declarative configuration of the BackendTCP type for use
// with apply.
type BackendTCPApplyConfiguration struct {
	// `keepAlive` defines settings for enabling TCP keepalives on the
	// connection.
	Keepalive *KeepaliveApplyConfiguration `json:"keepalive,omitempty"`
	// `connectTimeout` defines the deadline for establishing a connection to
	// the destination.
	ConnectTimeout *v1.Duration `json:"connectTimeout,omitempty"`
}

// BackendTCPApplyConfiguration constructs a declarative configuration of the BackendTCP type for use with
// apply.
func BackendTCP() *BackendTCPApplyConfiguration {
	return &BackendTCPApplyConfiguration{}
}

// WithKeepalive sets the Keepalive field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Keepalive field is set to the value of the last call.
func (b *BackendTCPApplyConfiguration) WithKeepalive(value *KeepaliveApplyConfiguration) *BackendTCPApplyConfiguration {
	b.Keepalive = value
	return b
}

// WithConnectTimeout sets the ConnectTimeout field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ConnectTimeout field is set to the value of the last call.
func (b *BackendTCPApplyConfiguration) WithConnectTimeout(value v1.Duration) *BackendTCPApplyConfiguration {
	b.ConnectTimeout = &value
	return b
}
