// Code generated by applyconfiguration-gen. DO NOT EDIT.

package agentgateway

import (
	v1alpha1agentgateway "github.com/agentgateway/agentgateway/controller/api/v1alpha1/agentgateway"
	v1 "k8s.io/api/core/v1"
)

// BackendTLSApplyConfiguration represents a declarative configuration of the BackendTLS type for use
// with apply.
type BackendTLSApplyConfiguration struct {
	// `mtlsCertificateRef` enables mutual TLS to the backend, using the
	// specified key (`tls.key`) and cert (`tls.crt`) from the referenced
	// `Secret`.
	//
	// An optional `ca.cert` field, if present, will be used to verify the
	// server certificate. If `caCertificateRefs` is also specified, the
	// `caCertificateRefs` field takes priority.
	//
	// If unspecified, no client certificate will be used.
	MtlsCertificateRef []v1.LocalObjectReference `json:"mtlsCertificateRef,omitempty"`
	// `caCertificateRefs` defines the CA certificate `ConfigMap` to use to
	// verify the server certificate.
	// If unset, the system's trusted certificates are used.
	CACertificateRefs []v1.LocalObjectReference `json:"caCertificateRefs,omitempty"`
	// insecureSkipVerify originates TLS but skips verification of the backend's certificate.
	// WARNING: This is an insecure option that should only be used if the risks are understood.
	//
	// There are two modes:
	// * `All` disables all TLS verification.
	// * `Hostname` verifies the CA certificate is trusted, but ignores any
	// mismatch of hostname or SANs. Note that this method is still insecure;
	// prefer setting `verifySubjectAltNames` to customize the valid hostnames
	// if possible.
	InsecureSkipVerify *v1alpha1agentgateway.InsecureTLSMode `json:"insecureSkipVerify,omitempty"`
	// `sni` specifies the Server Name Indicator (`SNI`) to be used in the TLS
	// handshake. If unset, the `SNI` is automatically set based on the
	// destination hostname.
	Sni *string `json:"sni,omitempty"`
	// `verifySubjectAltNames` specifies the Subject Alternative Names (`SAN`)
	// to verify in the server certificate.
	// If not present, the destination hostname is automatically used.
	VerifySubjectAltNames []string `json:"verifySubjectAltNames,omitempty"`
	// `alpnProtocols` sets the Application-Layer Protocol Negotiation (`ALPN`)
	// value to use in the TLS handshake.
	//
	// If not present, defaults to `["h2", "http/1.1"]`.
	AlpnProtocols *[]string `json:"alpnProtocols,omitempty"`
}

// BackendTLSApplyConfiguration constructs a declarative configuration of the BackendTLS type for use with
// apply.
func BackendTLS() *BackendTLSApplyConfiguration {
	return &BackendTLSApplyConfiguration{}
}

// WithMtlsCertificateRef adds the given value to the MtlsCertificateRef field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the MtlsCertificateRef field.
func (b *BackendTLSApplyConfiguration) WithMtlsCertificateRef(values ...v1.LocalObjectReference) *BackendTLSApplyConfiguration {
	for i := range values {
		b.MtlsCertificateRef = append(b.MtlsCertificateRef, values[i])
	}
	return b
}

// WithCACertificateRefs adds the given value to the CACertificateRefs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the CACertificateRefs field.
func (b *BackendTLSApplyConfiguration) WithCACertificateRefs(values ...v1.LocalObjectReference) *BackendTLSApplyConfiguration {
	for i := range values {
		b.CACertificateRefs = append(b.CACertificateRefs, values[i])
	}
	return b
}

// WithInsecureSkipVerify sets the InsecureSkipVerify field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InsecureSkipVerify field is set to the value of the last call.
func (b *BackendTLSApplyConfiguration) WithInsecureSkipVerify(value v1alpha1agentgateway.InsecureTLSMode) *BackendTLSApplyConfiguration {
	b.InsecureSkipVerify = &value
	return b
}

// WithSni sets the Sni field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Sni field is set to the value of the last call.
func (b *BackendTLSApplyConfiguration) WithSni(value string) *BackendTLSApplyConfiguration {
	b.Sni = &value
	return b
}

// WithVerifySubjectAltNames adds the given value to the VerifySubjectAltNames field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the VerifySubjectAltNames field.
func (b *BackendTLSApplyConfiguration) WithVerifySubjectAltNames(values ...string) *BackendTLSApplyConfiguration {
	for i := range values {
		b.VerifySubjectAltNames = append(b.VerifySubjectAltNames, values[i])
	}
	return b
}

// WithAlpnProtocols sets the AlpnProtocols field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AlpnProtocols field is set to the value of the last call.
func (b *BackendTLSApplyConfiguration) WithAlpnProtocols(value []string) *BackendTLSApplyConfiguration {
	b.AlpnProtocols = &value
	return b
}
