// Code generated by applyconfiguration-gen. DO NOT EDIT.

package agentgateway

import (
	v1alpha1agentgateway "github.com/agentgateway/agentgateway/controller/api/v1alpha1/agentgateway"
	v1 "k8s.io/api/core/v1"
)

// BasicAuthenticationApplyConfiguration represents a declarative configuration of the BasicAuthentication type for use
// with apply.
type BasicAuthenticationApplyConfiguration struct {
	// `mode` is the validation mode for basic auth authentication.
	Mode *v1alpha1agentgateway.BasicAuthenticationMode `json:"mode,omitempty"`
	// `realm` specifies the `realm` to return in the `WWW-Authenticate`
	// header for failed authentication requests. If unset, `Restricted` will
	// be used.
	Realm *string `json:"realm,omitempty"`
	// `users` provides an inline list of username and password pairs that will
	// be accepted. Each entry represents one line of the `htpasswd` format:
	// https://httpd.apache.org/docs/2.4/programs/htpasswd.html.
	//
	// Note: passwords should be the hash of the password, not the raw password. Use the `htpasswd` or similar commands
	// to generate a hash. MD5, bcrypt, crypt, and SHA-1 are supported.
	//
	// Example:
	//
	// users:
	// - "user1:$apr1$ivPt0D4C$DmRhnewfHRSrb3DQC.WHC."
	// - "user2:$2y$05$r3J4d3VepzFkedkd/q1vI.pBYIpSqjfN0qOARV3ScUHysatnS0cL2"
	Users []string `json:"users,omitempty"`
	// `secretRef` references a Kubernetes `Secret` storing the `.htaccess`
	// file. The `Secret` must have a key named `.htaccess`, and should contain
	// the complete `.htaccess` file.
	//
	// Note: passwords should be the hash of the password, not the raw password. Use the `htpasswd` or similar commands
	// to generate a hash. MD5, bcrypt, crypt, and SHA-1 are supported.
	//
	// Example:
	//
	// apiVersion: v1
	// kind: Secret
	// metadata:
	// name: basic-auth
	// stringData:
	// .htaccess: |
	// alice:$apr1$3zSE0Abt$IuETi4l5yO87MuOrbSE4V.
	// bob:$apr1$Ukb5LgRD$EPY2lIfY.A54jzLELNIId/
	SecretRef *v1.LocalObjectReference `json:"secretRef,omitempty"`
}

// BasicAuthenticationApplyConfiguration constructs a declarative configuration of the BasicAuthentication type for use with
// apply.
func BasicAuthentication() *BasicAuthenticationApplyConfiguration {
	return &BasicAuthenticationApplyConfiguration{}
}

// WithMode sets the Mode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Mode field is set to the value of the last call.
func (b *BasicAuthenticationApplyConfiguration) WithMode(value v1alpha1agentgateway.BasicAuthenticationMode) *BasicAuthenticationApplyConfiguration {
	b.Mode = &value
	return b
}

// WithRealm sets the Realm field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Realm field is set to the value of the last call.
func (b *BasicAuthenticationApplyConfiguration) WithRealm(value string) *BasicAuthenticationApplyConfiguration {
	b.Realm = &value
	return b
}

// WithUsers adds the given value to the Users field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Users field.
func (b *BasicAuthenticationApplyConfiguration) WithUsers(values ...string) *BasicAuthenticationApplyConfiguration {
	for i := range values {
		b.Users = append(b.Users, values[i])
	}
	return b
}

// WithSecretRef sets the SecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecretRef field is set to the value of the last call.
func (b *BasicAuthenticationApplyConfiguration) WithSecretRef(value v1.LocalObjectReference) *BasicAuthenticationApplyConfiguration {
	b.SecretRef = &value
	return b
}
