// Code generated by applyconfiguration-gen. DO NOT EDIT.

package agentgateway

// BedrockGuardrailsApplyConfiguration represents a declarative configuration of the BedrockGuardrails type for use
// with apply.
type BedrockGuardrailsApplyConfiguration struct {
	// GuardrailIdentifier is the identifier of the Guardrail policy to use for the backend.
	GuardrailIdentifier *string `json:"identifier,omitempty"`
	// GuardrailVersion is the version of the Guardrail policy to use for the backend.
	GuardrailVersion *string `json:"version,omitempty"`
	// Region is the AWS region where the guardrail is deployed (for example,
	// `us-west-2`).
	Region *string `json:"region,omitempty"`
	// policies controls policies for communicating with AWS Bedrock Guardrails.
	Policies *BackendSimpleApplyConfiguration `json:"policies,omitempty"`
}

// BedrockGuardrailsApplyConfiguration constructs a declarative configuration of the BedrockGuardrails type for use with
// apply.
func BedrockGuardrails() *BedrockGuardrailsApplyConfiguration {
	return &BedrockGuardrailsApplyConfiguration{}
}

// WithGuardrailIdentifier sets the GuardrailIdentifier field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GuardrailIdentifier field is set to the value of the last call.
func (b *BedrockGuardrailsApplyConfiguration) WithGuardrailIdentifier(value string) *BedrockGuardrailsApplyConfiguration {
	b.GuardrailIdentifier = &value
	return b
}

// WithGuardrailVersion sets the GuardrailVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GuardrailVersion field is set to the value of the last call.
func (b *BedrockGuardrailsApplyConfiguration) WithGuardrailVersion(value string) *BedrockGuardrailsApplyConfiguration {
	b.GuardrailVersion = &value
	return b
}

// WithRegion sets the Region field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Region field is set to the value of the last call.
func (b *BedrockGuardrailsApplyConfiguration) WithRegion(value string) *BedrockGuardrailsApplyConfiguration {
	b.Region = &value
	return b
}

// WithPolicies sets the Policies field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Policies field is set to the value of the last call.
func (b *BedrockGuardrailsApplyConfiguration) WithPolicies(value *BackendSimpleApplyConfiguration) *BedrockGuardrailsApplyConfiguration {
	b.Policies = value
	return b
}
