// Code generated by applyconfiguration-gen. DO NOT EDIT.

package agentgateway

// BedrockConfigApplyConfiguration represents a declarative configuration of the BedrockConfig type for use
// with apply.
type BedrockConfigApplyConfiguration struct {
	// Region is the AWS region to use for the backend.
	// Defaults to `us-east-1` if not specified.
	Region *string `json:"region,omitempty"`
	// Optional: Override the model name, such as `gpt-4o-mini`.
	// If unset, the model name is taken from the request.
	Model *string `json:"model,omitempty"`
	// `guardrail` configures the Guardrail policy to use for the backend. See
	// <https://docs.aws.amazon.com/bedrock/latest/userguide/guardrails.html>.
	// If not specified, the AWS Guardrail policy will not be used.
	Guardrail *AWSGuardrailConfigApplyConfiguration `json:"guardrail,omitempty"`
}

// BedrockConfigApplyConfiguration constructs a declarative configuration of the BedrockConfig type for use with
// apply.
func BedrockConfig() *BedrockConfigApplyConfiguration {
	return &BedrockConfigApplyConfiguration{}
}

// WithRegion sets the Region field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Region field is set to the value of the last call.
func (b *BedrockConfigApplyConfiguration) WithRegion(value string) *BedrockConfigApplyConfiguration {
	b.Region = &value
	return b
}

// WithModel sets the Model field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Model field is set to the value of the last call.
func (b *BedrockConfigApplyConfiguration) WithModel(value string) *BedrockConfigApplyConfiguration {
	b.Model = &value
	return b
}

// WithGuardrail sets the Guardrail field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Guardrail field is set to the value of the last call.
func (b *BedrockConfigApplyConfiguration) WithGuardrail(value *AWSGuardrailConfigApplyConfiguration) *BedrockConfigApplyConfiguration {
	b.Guardrail = value
	return b
}
