// Code generated by applyconfiguration-gen. DO NOT EDIT.

package agentgateway

import (
	v1 "sigs.k8s.io/gateway-api/apis/v1"
)

// CORSApplyConfiguration represents a declarative configuration of the CORS type for use
// with apply.
type CORSApplyConfiguration struct {
	v1.HTTPCORSFilter `json:",inline"`
}

// CORSApplyConfiguration constructs a declarative configuration of the CORS type for use with
// apply.
func CORS() *CORSApplyConfiguration {
	return &CORSApplyConfiguration{}
}
