// Code generated by applyconfiguration-gen. DO NOT EDIT.

package agentgateway

// CSRFApplyConfiguration represents a declarative configuration of the CSRF type for use
// with apply.
type CSRFApplyConfiguration struct {
	// `additionalOrigins` specifies additional source origins that will be
	// allowed in addition to the destination origin. The `Origin` consists of
	// a scheme and a host, with an optional port, and takes the form
	// `<scheme>://<host>(:<port>)`.
	AdditionalOrigins []string `json:"additionalOrigins,omitempty"`
}

// CSRFApplyConfiguration constructs a declarative configuration of the CSRF type for use with
// apply.
func CSRF() *CSRFApplyConfiguration {
	return &CSRFApplyConfiguration{}
}

// WithAdditionalOrigins adds the given value to the AdditionalOrigins field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AdditionalOrigins field.
func (b *CSRFApplyConfiguration) WithAdditionalOrigins(values ...string) *CSRFApplyConfiguration {
	for i := range values {
		b.AdditionalOrigins = append(b.AdditionalOrigins, values[i])
	}
	return b
}
