// Code generated by applyconfiguration-gen. DO NOT EDIT.

package agentgateway

// CustomResponseApplyConfiguration represents a declarative configuration of the CustomResponse type for use
// with apply.
//
// CustomResponse configures a response to return to the client if request content
// is matched against a regex pattern and the action is `REJECT`.
type CustomResponseApplyConfiguration struct {
	// A custom response message to return to the client. If not specified, defaults to
	// `The request was rejected due to inappropriate content`.
	Message *string `json:"message,omitempty"`
	// The status code to return to the client. Defaults to 403.
	StatusCode *int32 `json:"statusCode,omitempty"`
}

// CustomResponseApplyConfiguration constructs a declarative configuration of the CustomResponse type for use with
// apply.
func CustomResponse() *CustomResponseApplyConfiguration {
	return &CustomResponseApplyConfiguration{}
}

// WithMessage sets the Message field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Message field is set to the value of the last call.
func (b *CustomResponseApplyConfiguration) WithMessage(value string) *CustomResponseApplyConfiguration {
	b.Message = &value
	return b
}

// WithStatusCode sets the StatusCode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StatusCode field is set to the value of the last call.
func (b *CustomResponseApplyConfiguration) WithStatusCode(value int32) *CustomResponseApplyConfiguration {
	b.StatusCode = &value
	return b
}
