// Code generated by applyconfiguration-gen. DO NOT EDIT.

package agentgateway

// ExtAuthBodyApplyConfiguration represents a declarative configuration of the ExtAuthBody type for use
// with apply.
type ExtAuthBodyApplyConfiguration struct {
	// `maxSize` specifies, in bytes, the largest body that will be buffered
	// and sent to the authorization server. If the body size is larger than
	// `maxSize`, then the request will be rejected with a response.
	MaxSize *int32 `json:"maxSize,omitempty"`
}

// ExtAuthBodyApplyConfiguration constructs a declarative configuration of the ExtAuthBody type for use with
// apply.
func ExtAuthBody() *ExtAuthBodyApplyConfiguration {
	return &ExtAuthBodyApplyConfiguration{}
}

// WithMaxSize sets the MaxSize field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxSize field is set to the value of the last call.
func (b *ExtAuthBodyApplyConfiguration) WithMaxSize(value int32) *ExtAuthBodyApplyConfiguration {
	b.MaxSize = &value
	return b
}
