// Code generated by applyconfiguration-gen. DO NOT EDIT.

package agentgateway

import (
	v1alpha1agentgateway "github.com/agentgateway/agentgateway/controller/api/v1alpha1/agentgateway"
	v1 "sigs.k8s.io/gateway-api/apis/v1"
)

// ExtAuthApplyConfiguration represents a declarative configuration of the ExtAuth type for use
// with apply.
type ExtAuthApplyConfiguration struct {
	// `backendRef` references the External Authorization server to reach.
	//
	// Supported types: `Service` and `Backend`.
	BackendRef *v1.BackendObjectReference `json:"backendRef,omitempty"`
	// FailureMode controls behavior when the external authorization service is
	// unavailable or returns an error. "FailOpen" allows the request to continue.
	// "FailClosed" (default) denies the request.
	FailureMode *v1alpha1agentgateway.FailureMode `json:"failureMode,omitempty"`
	// grpc specifies that the gRPC External Authorization
	// [protocol](https://www.envoyproxy.io/docs/envoy/latest/api-v3/service/auth/v3/external_auth.proto) should be used.
	GRPC *AgentExtAuthGRPCApplyConfiguration `json:"grpc,omitempty"`
	// `http` specifies that the HTTP protocol should be used for connecting to
	// the authorization server. The authorization server must return a `200`
	// status code, otherwise the request is considered an authorization
	// failure.
	HTTP *AgentExtAuthHTTPApplyConfiguration `json:"http,omitempty"`
	// `forwardBody` configures whether to include the HTTP body in the request.
	// If enabled, the request body will be buffered.
	ForwardBody *ExtAuthBodyApplyConfiguration `json:"forwardBody,omitempty"`
}

// ExtAuthApplyConfiguration constructs a declarative configuration of the ExtAuth type for use with
// apply.
func ExtAuth() *ExtAuthApplyConfiguration {
	return &ExtAuthApplyConfiguration{}
}

// WithBackendRef sets the BackendRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BackendRef field is set to the value of the last call.
func (b *ExtAuthApplyConfiguration) WithBackendRef(value v1.BackendObjectReference) *ExtAuthApplyConfiguration {
	b.BackendRef = &value
	return b
}

// WithFailureMode sets the FailureMode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FailureMode field is set to the value of the last call.
func (b *ExtAuthApplyConfiguration) WithFailureMode(value v1alpha1agentgateway.FailureMode) *ExtAuthApplyConfiguration {
	b.FailureMode = &value
	return b
}

// WithGRPC sets the GRPC field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GRPC field is set to the value of the last call.
func (b *ExtAuthApplyConfiguration) WithGRPC(value *AgentExtAuthGRPCApplyConfiguration) *ExtAuthApplyConfiguration {
	b.GRPC = value
	return b
}

// WithHTTP sets the HTTP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HTTP field is set to the value of the last call.
func (b *ExtAuthApplyConfiguration) WithHTTP(value *AgentExtAuthHTTPApplyConfiguration) *ExtAuthApplyConfiguration {
	b.HTTP = value
	return b
}

// WithForwardBody sets the ForwardBody field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ForwardBody field is set to the value of the last call.
func (b *ExtAuthApplyConfiguration) WithForwardBody(value *ExtAuthBodyApplyConfiguration) *ExtAuthApplyConfiguration {
	b.ForwardBody = value
	return b
}
