// Code generated by applyconfiguration-gen. DO NOT EDIT.

package agentgateway

import (
	v1 "sigs.k8s.io/gateway-api/apis/v1"
)

// ExtProcApplyConfiguration represents a declarative configuration of the ExtProc type for use
// with apply.
type ExtProcApplyConfiguration struct {
	// `backendRef` references the External Processor server to reach.
	// Supported types: `Service` and `Backend`.
	BackendRef *v1.BackendObjectReference `json:"backendRef,omitempty"`
}

// ExtProcApplyConfiguration constructs a declarative configuration of the ExtProc type for use with
// apply.
func ExtProc() *ExtProcApplyConfiguration {
	return &ExtProcApplyConfiguration{}
}

// WithBackendRef sets the BackendRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BackendRef field is set to the value of the last call.
func (b *ExtProcApplyConfiguration) WithBackendRef(value v1.BackendObjectReference) *ExtProcApplyConfiguration {
	b.BackendRef = &value
	return b
}
