// Code generated by applyconfiguration-gen. DO NOT EDIT.

package agentgateway

import (
	shared "github.com/agentgateway/agentgateway/controller/api/v1alpha1/shared"
)

// FieldTransformationApplyConfiguration represents a declarative configuration of the FieldTransformation type for use
// with apply.
//
// FieldTransformation maps a request JSON field to a CEL expression string.
// The expression is evaluated against the current request body and its result
// is assigned to the configured field.
type FieldTransformationApplyConfiguration struct {
	// The name of the field to set.
	Field *string `json:"field,omitempty"`
	// CEL expression used to compute the field value.
	Expression *shared.CELExpression `json:"expression,omitempty"`
}

// FieldTransformationApplyConfiguration constructs a declarative configuration of the FieldTransformation type for use with
// apply.
func FieldTransformation() *FieldTransformationApplyConfiguration {
	return &FieldTransformationApplyConfiguration{}
}

// WithField sets the Field field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Field field is set to the value of the last call.
func (b *FieldTransformationApplyConfiguration) WithField(value string) *FieldTransformationApplyConfiguration {
	b.Field = &value
	return b
}

// WithExpression sets the Expression field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Expression field is set to the value of the last call.
func (b *FieldTransformationApplyConfiguration) WithExpression(value shared.CELExpression) *FieldTransformationApplyConfiguration {
	b.Expression = &value
	return b
}
