// Code generated by applyconfiguration-gen. DO NOT EDIT.

package agentgateway

import (
	v1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
)

// FieldDefaultApplyConfiguration represents a declarative configuration of the FieldDefault type for use
// with apply.
//
// FieldDefault provides default values for specific fields in the JSON request body sent to the LLM provider.
// These defaults are merged with the user-provided request to ensure missing fields are populated.
//
// User input fields here refer to the fields in the JSON request body that a client sends when making a request to the LLM provider.
// Defaults set here do _not_ override those user-provided values unless you explicitly set `override` to `true`.
//
// Example: Setting a default system field for Anthropic, which does not support system role messages:
//
// defaults:
// - field: "system"
// value: "answer all questions in French"
//
// Example: Setting a default temperature and overriding `max_tokens`:
//
// defaults:
// - field: "temperature"
// value: "0.5"
// - field: "max_tokens"
// value: "100"
// override: true
//
// Example: Setting custom lists fields:
//
// defaults:
// - field: "custom_integer_list"
// value: [1,2,3]
//
// overrides:
// - field: "custom_string_list"
// value: ["one","two","three"]
//
// Note: The `field` values correspond to keys in the JSON request body, not fields in this CRD.
type FieldDefaultApplyConfiguration struct {
	// The name of the field.
	Field *string `json:"field,omitempty"`
	// The field default value, which can be any JSON Data Type.
	Value *v1.JSON `json:"value,omitempty"`
}

// FieldDefaultApplyConfiguration constructs a declarative configuration of the FieldDefault type for use with
// apply.
func FieldDefault() *FieldDefaultApplyConfiguration {
	return &FieldDefaultApplyConfiguration{}
}

// WithField sets the Field field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Field field is set to the value of the last call.
func (b *FieldDefaultApplyConfiguration) WithField(value string) *FieldDefaultApplyConfiguration {
	b.Field = &value
	return b
}

// WithValue sets the Value field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Value field is set to the value of the last call.
func (b *FieldDefaultApplyConfiguration) WithValue(value v1.JSON) *FieldDefaultApplyConfiguration {
	b.Value = &value
	return b
}
