// Code generated by applyconfiguration-gen. DO NOT EDIT.

package agentgateway

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// FrontendHTTPApplyConfiguration represents a declarative configuration of the FrontendHTTP type for use
// with apply.
type FrontendHTTPApplyConfiguration struct {
	// `maxBufferSize` defines the maximum HTTP body size that will be buffered
	// into memory.
	// Bodies will only be buffered for policies which require buffering.
	// If unset, this defaults to `2mb`.
	MaxBufferSize *int32 `json:"maxBufferSize,omitempty"`
	// `http1MaxHeaders` defines the maximum number of headers that are allowed
	// in `HTTP/1.1` requests.
	// If unset, this defaults to 100.
	HTTP1MaxHeaders *int32 `json:"http1MaxHeaders,omitempty"`
	// `http1IdleTimeout` defines the timeout before an unused connection is
	// closed.
	// If unset, this defaults to 10 minutes.
	HTTP1IdleTimeout *v1.Duration `json:"http1IdleTimeout,omitempty"`
	// `http2WindowSize` indicates the initial window size for stream-level flow
	// control for received data.
	HTTP2WindowSize *int32 `json:"http2WindowSize,omitempty"`
	// `http2ConnectionWindowSize` indicates the initial window size for
	// connection-level flow control for received data.
	HTTP2ConnectionWindowSize *int32 `json:"http2ConnectionWindowSize,omitempty"`
	// `http2FrameSize` sets the maximum frame size to use.
	// If unset, this defaults to `16kb`.
	HTTP2FrameSize         *int32       `json:"http2FrameSize,omitempty"`
	HTTP2KeepaliveInterval *v1.Duration `json:"http2KeepaliveInterval,omitempty"`
	HTTP2KeepaliveTimeout  *v1.Duration `json:"http2KeepaliveTimeout,omitempty"`
}

// FrontendHTTPApplyConfiguration constructs a declarative configuration of the FrontendHTTP type for use with
// apply.
func FrontendHTTP() *FrontendHTTPApplyConfiguration {
	return &FrontendHTTPApplyConfiguration{}
}

// WithMaxBufferSize sets the MaxBufferSize field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxBufferSize field is set to the value of the last call.
func (b *FrontendHTTPApplyConfiguration) WithMaxBufferSize(value int32) *FrontendHTTPApplyConfiguration {
	b.MaxBufferSize = &value
	return b
}

// WithHTTP1MaxHeaders sets the HTTP1MaxHeaders field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HTTP1MaxHeaders field is set to the value of the last call.
func (b *FrontendHTTPApplyConfiguration) WithHTTP1MaxHeaders(value int32) *FrontendHTTPApplyConfiguration {
	b.HTTP1MaxHeaders = &value
	return b
}

// WithHTTP1IdleTimeout sets the HTTP1IdleTimeout field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HTTP1IdleTimeout field is set to the value of the last call.
func (b *FrontendHTTPApplyConfiguration) WithHTTP1IdleTimeout(value v1.Duration) *FrontendHTTPApplyConfiguration {
	b.HTTP1IdleTimeout = &value
	return b
}

// WithHTTP2WindowSize sets the HTTP2WindowSize field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HTTP2WindowSize field is set to the value of the last call.
func (b *FrontendHTTPApplyConfiguration) WithHTTP2WindowSize(value int32) *FrontendHTTPApplyConfiguration {
	b.HTTP2WindowSize = &value
	return b
}

// WithHTTP2ConnectionWindowSize sets the HTTP2ConnectionWindowSize field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HTTP2ConnectionWindowSize field is set to the value of the last call.
func (b *FrontendHTTPApplyConfiguration) WithHTTP2ConnectionWindowSize(value int32) *FrontendHTTPApplyConfiguration {
	b.HTTP2ConnectionWindowSize = &value
	return b
}

// WithHTTP2FrameSize sets the HTTP2FrameSize field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HTTP2FrameSize field is set to the value of the last call.
func (b *FrontendHTTPApplyConfiguration) WithHTTP2FrameSize(value int32) *FrontendHTTPApplyConfiguration {
	b.HTTP2FrameSize = &value
	return b
}

// WithHTTP2KeepaliveInterval sets the HTTP2KeepaliveInterval field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HTTP2KeepaliveInterval field is set to the value of the last call.
func (b *FrontendHTTPApplyConfiguration) WithHTTP2KeepaliveInterval(value v1.Duration) *FrontendHTTPApplyConfiguration {
	b.HTTP2KeepaliveInterval = &value
	return b
}

// WithHTTP2KeepaliveTimeout sets the HTTP2KeepaliveTimeout field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HTTP2KeepaliveTimeout field is set to the value of the last call.
func (b *FrontendHTTPApplyConfiguration) WithHTTP2KeepaliveTimeout(value v1.Duration) *FrontendHTTPApplyConfiguration {
	b.HTTP2KeepaliveTimeout = &value
	return b
}
