// Code generated by applyconfiguration-gen. DO NOT EDIT.

package agentgateway

import (
	shared "github.com/agentgateway/agentgateway/controller/api/v1alpha1/shared"
)

// FrontendApplyConfiguration represents a declarative configuration of the Frontend type for use
// with apply.
type FrontendApplyConfiguration struct {
	// tcp defines settings on managing incoming TCP connections.
	TCP *FrontendTCPApplyConfiguration `json:"tcp,omitempty"`
	// networkAuthorization defines CEL authorization on downstream network connections.
	//
	// This runs before protocol handling and is intended for L4 access control,
	// for example using `source.address` with `cidr(...).containsIP(...)`.
	NetworkAuthorization *shared.Authorization `json:"networkAuthorization,omitempty"`
	// tls defines settings on managing incoming TLS connections.
	TLS *FrontendTLSApplyConfiguration `json:"tls,omitempty"`
	// http defines settings on managing incoming HTTP requests.
	HTTP *FrontendHTTPApplyConfiguration `json:"http,omitempty"`
	// `accessLog` contains access logging configuration.
	AccessLog *AccessLogApplyConfiguration `json:"accessLog,omitempty"`
	// `tracing` contains various settings for the OpenTelemetry tracer.
	Tracing *TracingApplyConfiguration `json:"tracing,omitempty"`
}

// FrontendApplyConfiguration constructs a declarative configuration of the Frontend type for use with
// apply.
func Frontend() *FrontendApplyConfiguration {
	return &FrontendApplyConfiguration{}
}

// WithTCP sets the TCP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TCP field is set to the value of the last call.
func (b *FrontendApplyConfiguration) WithTCP(value *FrontendTCPApplyConfiguration) *FrontendApplyConfiguration {
	b.TCP = value
	return b
}

// WithNetworkAuthorization sets the NetworkAuthorization field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NetworkAuthorization field is set to the value of the last call.
func (b *FrontendApplyConfiguration) WithNetworkAuthorization(value shared.Authorization) *FrontendApplyConfiguration {
	b.NetworkAuthorization = &value
	return b
}

// WithTLS sets the TLS field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TLS field is set to the value of the last call.
func (b *FrontendApplyConfiguration) WithTLS(value *FrontendTLSApplyConfiguration) *FrontendApplyConfiguration {
	b.TLS = value
	return b
}

// WithHTTP sets the HTTP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HTTP field is set to the value of the last call.
func (b *FrontendApplyConfiguration) WithHTTP(value *FrontendHTTPApplyConfiguration) *FrontendApplyConfiguration {
	b.HTTP = value
	return b
}

// WithAccessLog sets the AccessLog field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AccessLog field is set to the value of the last call.
func (b *FrontendApplyConfiguration) WithAccessLog(value *AccessLogApplyConfiguration) *FrontendApplyConfiguration {
	b.AccessLog = value
	return b
}

// WithTracing sets the Tracing field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Tracing field is set to the value of the last call.
func (b *FrontendApplyConfiguration) WithTracing(value *TracingApplyConfiguration) *FrontendApplyConfiguration {
	b.Tracing = value
	return b
}
