// Code generated by applyconfiguration-gen. DO NOT EDIT.

package agentgateway

import (
	v1alpha1agentgateway "github.com/agentgateway/agentgateway/controller/api/v1alpha1/agentgateway"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// FrontendTLSApplyConfiguration represents a declarative configuration of the FrontendTLS type for use
// with apply.
type FrontendTLSApplyConfiguration struct {
	// `handshakeTimeout` specifies the deadline for a TLS handshake to
	// complete. If unset, this defaults to `15s`.
	HandshakeTimeout *v1.Duration `json:"handshakeTimeout,omitempty"`
	// `alpnProtocols` sets the Application-Layer Protocol Negotiation (`ALPN`)
	// value to use in the TLS handshake.
	//
	// If not present, defaults to `["h2", "http/1.1"]`.
	AlpnProtocols *[]string `json:"alpnProtocols,omitempty"`
	// MinTLSVersion configures the minimum TLS version to support.
	MinTLSVersion *v1alpha1agentgateway.TLSVersion `json:"minProtocolVersion,omitempty"`
	// MaxTLSVersion configures the maximum TLS version to support.
	MaxTLSVersion *v1alpha1agentgateway.TLSVersion `json:"maxProtocolVersion,omitempty"`
	// CipherSuites configures the list of cipher suites for a TLS listener.
	// The value is a comma-separated list of cipher suites, for example
	// `TLS13_AES_256_GCM_SHA384,TLS13_AES_128_GCM_SHA256`.
	// Use this in the TLS options field of a TLS listener.
	CipherSuites []v1alpha1agentgateway.CipherSuite `json:"cipherSuites,omitempty"`
}

// FrontendTLSApplyConfiguration constructs a declarative configuration of the FrontendTLS type for use with
// apply.
func FrontendTLS() *FrontendTLSApplyConfiguration {
	return &FrontendTLSApplyConfiguration{}
}

// WithHandshakeTimeout sets the HandshakeTimeout field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HandshakeTimeout field is set to the value of the last call.
func (b *FrontendTLSApplyConfiguration) WithHandshakeTimeout(value v1.Duration) *FrontendTLSApplyConfiguration {
	b.HandshakeTimeout = &value
	return b
}

// WithAlpnProtocols sets the AlpnProtocols field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AlpnProtocols field is set to the value of the last call.
func (b *FrontendTLSApplyConfiguration) WithAlpnProtocols(value []string) *FrontendTLSApplyConfiguration {
	b.AlpnProtocols = &value
	return b
}

// WithMinTLSVersion sets the MinTLSVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MinTLSVersion field is set to the value of the last call.
func (b *FrontendTLSApplyConfiguration) WithMinTLSVersion(value v1alpha1agentgateway.TLSVersion) *FrontendTLSApplyConfiguration {
	b.MinTLSVersion = &value
	return b
}

// WithMaxTLSVersion sets the MaxTLSVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxTLSVersion field is set to the value of the last call.
func (b *FrontendTLSApplyConfiguration) WithMaxTLSVersion(value v1alpha1agentgateway.TLSVersion) *FrontendTLSApplyConfiguration {
	b.MaxTLSVersion = &value
	return b
}

// WithCipherSuites adds the given value to the CipherSuites field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the CipherSuites field.
func (b *FrontendTLSApplyConfiguration) WithCipherSuites(values ...v1alpha1agentgateway.CipherSuite) *FrontendTLSApplyConfiguration {
	for i := range values {
		b.CipherSuites = append(b.CipherSuites, values[i])
	}
	return b
}
