// Code generated by applyconfiguration-gen. DO NOT EDIT.

package agentgateway

import (
	v1alpha1agentgateway "github.com/agentgateway/agentgateway/controller/api/v1alpha1/agentgateway"
)

// GcpAuthApplyConfiguration represents a declarative configuration of the GcpAuth type for use
// with apply.
//
// GcpAuth specifies how to authenticate on Google Cloud Platform.
type GcpAuthApplyConfiguration struct {
	// The type of token to generate. To authenticate to GCP services,
	// generally an `AccessToken` is used. To authenticate to Cloud Run, an
	// `IdToken` is used.
	Type *v1alpha1agentgateway.GcpAuthType `json:"type,omitempty"`
	// `audience` allows explicitly configuring the `aud` of the ID token. Only
	// valid with `IdToken` type. If not set, the `aud` is automatically
	// derived from the backend hostname.
	Audience *string `json:"audience,omitempty"`
}

// GcpAuthApplyConfiguration constructs a declarative configuration of the GcpAuth type for use with
// apply.
func GcpAuth() *GcpAuthApplyConfiguration {
	return &GcpAuthApplyConfiguration{}
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *GcpAuthApplyConfiguration) WithType(value v1alpha1agentgateway.GcpAuthType) *GcpAuthApplyConfiguration {
	b.Type = &value
	return b
}

// WithAudience sets the Audience field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Audience field is set to the value of the last call.
func (b *GcpAuthApplyConfiguration) WithAudience(value string) *GcpAuthApplyConfiguration {
	b.Audience = &value
	return b
}
