// Code generated by applyconfiguration-gen. DO NOT EDIT.

package agentgateway

// GeminiConfigApplyConfiguration represents a declarative configuration of the GeminiConfig type for use
// with apply.
//
// GeminiConfig settings for the [Gemini](https://ai.google.dev/gemini-api/docs) LLM provider.
type GeminiConfigApplyConfiguration struct {
	// Optional: Override the model name, such as `gemini-2.5-pro`.
	// If unset, the model name is taken from the request.
	Model *string `json:"model,omitempty"`
}

// GeminiConfigApplyConfiguration constructs a declarative configuration of the GeminiConfig type for use with
// apply.
func GeminiConfig() *GeminiConfigApplyConfiguration {
	return &GeminiConfigApplyConfiguration{}
}

// WithModel sets the Model field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Model field is set to the value of the last call.
func (b *GeminiConfigApplyConfiguration) WithModel(value string) *GeminiConfigApplyConfiguration {
	b.Model = &value
	return b
}
