// Code generated by applyconfiguration-gen. DO NOT EDIT.

package agentgateway

import (
	v1alpha1agentgateway "github.com/agentgateway/agentgateway/controller/api/v1alpha1/agentgateway"
	v1 "sigs.k8s.io/gateway-api/apis/v1"
)

// GlobalRateLimitApplyConfiguration represents a declarative configuration of the GlobalRateLimit type for use
// with apply.
type GlobalRateLimitApplyConfiguration struct {
	// `backendRef` references the rate limit server to reach.
	// Supported types: `Service` and `Backend`.
	BackendRef *v1.BackendObjectReference `json:"backendRef,omitempty"`
	// `failureMode` controls behavior when the remote rate limit service is
	// unavailable or returns an error. `FailOpen` allows the request to continue.
	// `FailClosed` (default) denies the request.
	FailureMode *v1alpha1agentgateway.FailureMode `json:"failureMode,omitempty"`
	// `domain` specifies the domain under which this limit should apply.
	// This is an arbitrary string that enables a rate limit server to distinguish between different applications.
	Domain *string `json:"domain,omitempty"`
	// `descriptors` define the dimensions for rate limiting. These values are
	// passed to the rate limit service which applies configured limits based
	// on them. Each descriptor represents a single rate limit rule with one or
	// more entries.
	Descriptors []RateLimitDescriptorApplyConfiguration `json:"descriptors,omitempty"`
}

// GlobalRateLimitApplyConfiguration constructs a declarative configuration of the GlobalRateLimit type for use with
// apply.
func GlobalRateLimit() *GlobalRateLimitApplyConfiguration {
	return &GlobalRateLimitApplyConfiguration{}
}

// WithBackendRef sets the BackendRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BackendRef field is set to the value of the last call.
func (b *GlobalRateLimitApplyConfiguration) WithBackendRef(value v1.BackendObjectReference) *GlobalRateLimitApplyConfiguration {
	b.BackendRef = &value
	return b
}

// WithFailureMode sets the FailureMode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FailureMode field is set to the value of the last call.
func (b *GlobalRateLimitApplyConfiguration) WithFailureMode(value v1alpha1agentgateway.FailureMode) *GlobalRateLimitApplyConfiguration {
	b.FailureMode = &value
	return b
}

// WithDomain sets the Domain field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Domain field is set to the value of the last call.
func (b *GlobalRateLimitApplyConfiguration) WithDomain(value string) *GlobalRateLimitApplyConfiguration {
	b.Domain = &value
	return b
}

// WithDescriptors adds the given value to the Descriptors field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Descriptors field.
func (b *GlobalRateLimitApplyConfiguration) WithDescriptors(values ...*RateLimitDescriptorApplyConfiguration) *GlobalRateLimitApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithDescriptors")
		}
		b.Descriptors = append(b.Descriptors, *values[i])
	}
	return b
}
