// Code generated by applyconfiguration-gen. DO NOT EDIT.

package agentgateway

// GoogleModelArmorApplyConfiguration represents a declarative configuration of the GoogleModelArmor type for use
// with apply.
type GoogleModelArmorApplyConfiguration struct {
	// TemplateID is the template ID for Google Model Armor.
	TemplateID *string `json:"templateId,omitempty"`
	// ProjectID is the Google Cloud project ID.
	ProjectID *string `json:"projectId,omitempty"`
	// Location is the Google Cloud location (for example, `us-central1`).
	// Defaults to `us-central1` if not specified.
	Location *string `json:"location,omitempty"`
	// policies controls policies for communicating with Google Model Armor.
	Policies *BackendSimpleApplyConfiguration `json:"policies,omitempty"`
}

// GoogleModelArmorApplyConfiguration constructs a declarative configuration of the GoogleModelArmor type for use with
// apply.
func GoogleModelArmor() *GoogleModelArmorApplyConfiguration {
	return &GoogleModelArmorApplyConfiguration{}
}

// WithTemplateID sets the TemplateID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TemplateID field is set to the value of the last call.
func (b *GoogleModelArmorApplyConfiguration) WithTemplateID(value string) *GoogleModelArmorApplyConfiguration {
	b.TemplateID = &value
	return b
}

// WithProjectID sets the ProjectID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProjectID field is set to the value of the last call.
func (b *GoogleModelArmorApplyConfiguration) WithProjectID(value string) *GoogleModelArmorApplyConfiguration {
	b.ProjectID = &value
	return b
}

// WithLocation sets the Location field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Location field is set to the value of the last call.
func (b *GoogleModelArmorApplyConfiguration) WithLocation(value string) *GoogleModelArmorApplyConfiguration {
	b.Location = &value
	return b
}

// WithPolicies sets the Policies field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Policies field is set to the value of the last call.
func (b *GoogleModelArmorApplyConfiguration) WithPolicies(value *BackendSimpleApplyConfiguration) *GoogleModelArmorApplyConfiguration {
	b.Policies = value
	return b
}
