// Code generated by applyconfiguration-gen. DO NOT EDIT.

package agentgateway

import (
	v1alpha1agentgateway "github.com/agentgateway/agentgateway/controller/api/v1alpha1/agentgateway"
	shared "github.com/agentgateway/agentgateway/controller/api/v1alpha1/shared"
)

// HeaderTransformationApplyConfiguration represents a declarative configuration of the HeaderTransformation type for use
// with apply.
type HeaderTransformationApplyConfiguration struct {
	// The name of the header to add.
	Name *v1alpha1agentgateway.HeaderName `json:"name,omitempty"`
	// `value` is the CEL expression to apply to generate the output value for
	// the header.
	Value *shared.CELExpression `json:"value,omitempty"`
}

// HeaderTransformationApplyConfiguration constructs a declarative configuration of the HeaderTransformation type for use with
// apply.
func HeaderTransformation() *HeaderTransformationApplyConfiguration {
	return &HeaderTransformationApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *HeaderTransformationApplyConfiguration) WithName(value v1alpha1agentgateway.HeaderName) *HeaderTransformationApplyConfiguration {
	b.Name = &value
	return b
}

// WithValue sets the Value field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Value field is set to the value of the last call.
func (b *HeaderTransformationApplyConfiguration) WithValue(value shared.CELExpression) *HeaderTransformationApplyConfiguration {
	b.Value = &value
	return b
}
