// Code generated by applyconfiguration-gen. DO NOT EDIT.

package agentgateway

import (
	shared "github.com/agentgateway/agentgateway/controller/api/v1alpha1/shared"
)

// HealthApplyConfiguration represents a declarative configuration of the Health type for use
// with apply.
type HealthApplyConfiguration struct {
	// UnhealthyCondition is a CEL expression that determines whether a response indicates an unhealthy backend.
	// When the expression evaluates to true, the backend is considered unhealthy and may be evicted.
	//
	// For example, to evict on 5xx responses: `response.code >= 500`.
	//
	// When unset, any 5xx response, or a connection failure, is treated as unhealthy.
	// This default lowers the backend's health score but does not trigger eviction on its own.
	UnhealthyCondition *shared.CELExpression `json:"unhealthyCondition,omitempty"`
	// Eviction defines settings for evicting unhealthy backends.
	Eviction *BackendEvictionApplyConfiguration `json:"eviction,omitempty"`
}

// HealthApplyConfiguration constructs a declarative configuration of the Health type for use with
// apply.
func Health() *HealthApplyConfiguration {
	return &HealthApplyConfiguration{}
}

// WithUnhealthyCondition sets the UnhealthyCondition field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UnhealthyCondition field is set to the value of the last call.
func (b *HealthApplyConfiguration) WithUnhealthyCondition(value shared.CELExpression) *HealthApplyConfiguration {
	b.UnhealthyCondition = &value
	return b
}

// WithEviction sets the Eviction field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Eviction field is set to the value of the last call.
func (b *HealthApplyConfiguration) WithEviction(value *BackendEvictionApplyConfiguration) *HealthApplyConfiguration {
	b.Eviction = value
	return b
}
