// Code generated by applyconfiguration-gen. DO NOT EDIT.

package agentgateway

import (
	v1alpha1agentgateway "github.com/agentgateway/agentgateway/controller/api/v1alpha1/agentgateway"
)

// HostnameRewriteApplyConfiguration represents a declarative configuration of the HostnameRewrite type for use
// with apply.
type HostnameRewriteApplyConfiguration struct {
	// `mode` sets the hostname rewrite mode.
	//
	// The following may be specified:
	// * `Auto`: automatically set the `Host` header based on the destination.
	// * `None`: do not rewrite the `Host` header. The original `Host` header
	// will be passed through.
	//
	// This setting defaults to `Auto` when connecting to hostname-based
	// `Backend` types, and `None` otherwise, for `Service` or IP-based
	// backends.
	Mode *v1alpha1agentgateway.HostnameRewriteMode `json:"mode,omitempty"`
}

// HostnameRewriteApplyConfiguration constructs a declarative configuration of the HostnameRewrite type for use with
// apply.
func HostnameRewrite() *HostnameRewriteApplyConfiguration {
	return &HostnameRewriteApplyConfiguration{}
}

// WithMode sets the Mode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Mode field is set to the value of the last call.
func (b *HostnameRewriteApplyConfiguration) WithMode(value v1alpha1agentgateway.HostnameRewriteMode) *HostnameRewriteApplyConfiguration {
	b.Mode = &value
	return b
}
