// Code generated by applyconfiguration-gen. DO NOT EDIT.

package agentgateway

import (
	v1 "k8s.io/api/core/v1"
)

// ImageApplyConfiguration represents a declarative configuration of the Image type for use
// with apply.
//
// A container image. See https://kubernetes.io/docs/concepts/containers/images
// for details.
type ImageApplyConfiguration struct {
	// The image registry.
	Registry *string `json:"registry,omitempty"`
	// The image repository (name).
	Repository *string `json:"repository,omitempty"`
	// The image tag.
	Tag *string `json:"tag,omitempty"`
	// The hash digest of the image, e.g. `sha256:12345...`
	Digest *string `json:"digest,omitempty"`
	// The image pull policy for the container. See
	// https://kubernetes.io/docs/concepts/containers/images/#image-pull-policy
	// for details.
	PullPolicy *v1.PullPolicy `json:"pullPolicy,omitempty"`
}

// ImageApplyConfiguration constructs a declarative configuration of the Image type for use with
// apply.
func Image() *ImageApplyConfiguration {
	return &ImageApplyConfiguration{}
}

// WithRegistry sets the Registry field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Registry field is set to the value of the last call.
func (b *ImageApplyConfiguration) WithRegistry(value string) *ImageApplyConfiguration {
	b.Registry = &value
	return b
}

// WithRepository sets the Repository field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Repository field is set to the value of the last call.
func (b *ImageApplyConfiguration) WithRepository(value string) *ImageApplyConfiguration {
	b.Repository = &value
	return b
}

// WithTag sets the Tag field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Tag field is set to the value of the last call.
func (b *ImageApplyConfiguration) WithTag(value string) *ImageApplyConfiguration {
	b.Tag = &value
	return b
}

// WithDigest sets the Digest field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Digest field is set to the value of the last call.
func (b *ImageApplyConfiguration) WithDigest(value string) *ImageApplyConfiguration {
	b.Digest = &value
	return b
}

// WithPullPolicy sets the PullPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PullPolicy field is set to the value of the last call.
func (b *ImageApplyConfiguration) WithPullPolicy(value v1.PullPolicy) *ImageApplyConfiguration {
	b.PullPolicy = &value
	return b
}
