// Code generated by applyconfiguration-gen. DO NOT EDIT.

package agentgateway

// IstioSpecApplyConfiguration represents a declarative configuration of the IstioSpec type for use
// with apply.
type IstioSpecApplyConfiguration struct {
	// The address of the Istio CA. If unset, defaults to `https://istiod.istio-system.svc:15012`.
	CaAddress *string `json:"caAddress,omitempty"`
	// The Istio trust domain. If not set, defaults to `cluster.local`.
	TrustDomain *string `json:"trustDomain,omitempty"`
}

// IstioSpecApplyConfiguration constructs a declarative configuration of the IstioSpec type for use with
// apply.
func IstioSpec() *IstioSpecApplyConfiguration {
	return &IstioSpecApplyConfiguration{}
}

// WithCaAddress sets the CaAddress field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CaAddress field is set to the value of the last call.
func (b *IstioSpecApplyConfiguration) WithCaAddress(value string) *IstioSpecApplyConfiguration {
	b.CaAddress = &value
	return b
}

// WithTrustDomain sets the TrustDomain field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TrustDomain field is set to the value of the last call.
func (b *IstioSpecApplyConfiguration) WithTrustDomain(value string) *IstioSpecApplyConfiguration {
	b.TrustDomain = &value
	return b
}
