// Code generated by applyconfiguration-gen. DO NOT EDIT.

package agentgateway

// JWKSApplyConfiguration represents a declarative configuration of the JWKS type for use
// with apply.
type JWKSApplyConfiguration struct {
	// `remote` specifies how to reach the JSON Web Key Set from a remote
	// address.
	Remote *RemoteJWKSApplyConfiguration `json:"remote,omitempty"`
	// `inline` specifies an inline JSON Web Key Set used to validate the
	// signature of the JWT.
	Inline *string `json:"inline,omitempty"`
}

// JWKSApplyConfiguration constructs a declarative configuration of the JWKS type for use with
// apply.
func JWKS() *JWKSApplyConfiguration {
	return &JWKSApplyConfiguration{}
}

// WithRemote sets the Remote field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Remote field is set to the value of the last call.
func (b *JWKSApplyConfiguration) WithRemote(value *RemoteJWKSApplyConfiguration) *JWKSApplyConfiguration {
	b.Remote = value
	return b
}

// WithInline sets the Inline field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Inline field is set to the value of the last call.
func (b *JWKSApplyConfiguration) WithInline(value string) *JWKSApplyConfiguration {
	b.Inline = &value
	return b
}
