// Code generated by applyconfiguration-gen. DO NOT EDIT.

package agentgateway

import (
	v1alpha1agentgateway "github.com/agentgateway/agentgateway/controller/api/v1alpha1/agentgateway"
)

// JWTAuthenticationApplyConfiguration represents a declarative configuration of the JWTAuthentication type for use
// with apply.
type JWTAuthenticationApplyConfiguration struct {
	// `mode` is the validation mode for JWT authentication.
	Mode      *v1alpha1agentgateway.JWTAuthenticationMode `json:"mode,omitempty"`
	Providers []JWTProviderApplyConfiguration             `json:"providers,omitempty"`
	// `mcp` optionally enables MCP OAuth metadata endpoint handling
	// and MCP-specific authentication behavior on top of standard JWT validation.
	// When set, the gateway will serve the MCP OAuth metadata discovery endpoints.
	MCP *JWTMCPConfigApplyConfiguration `json:"mcp,omitempty"`
}

// JWTAuthenticationApplyConfiguration constructs a declarative configuration of the JWTAuthentication type for use with
// apply.
func JWTAuthentication() *JWTAuthenticationApplyConfiguration {
	return &JWTAuthenticationApplyConfiguration{}
}

// WithMode sets the Mode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Mode field is set to the value of the last call.
func (b *JWTAuthenticationApplyConfiguration) WithMode(value v1alpha1agentgateway.JWTAuthenticationMode) *JWTAuthenticationApplyConfiguration {
	b.Mode = &value
	return b
}

// WithProviders adds the given value to the Providers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Providers field.
func (b *JWTAuthenticationApplyConfiguration) WithProviders(values ...*JWTProviderApplyConfiguration) *JWTAuthenticationApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithProviders")
		}
		b.Providers = append(b.Providers, *values[i])
	}
	return b
}

// WithMCP sets the MCP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MCP field is set to the value of the last call.
func (b *JWTAuthenticationApplyConfiguration) WithMCP(value *JWTMCPConfigApplyConfiguration) *JWTAuthenticationApplyConfiguration {
	b.MCP = value
	return b
}
