// Code generated by applyconfiguration-gen. DO NOT EDIT.

package agentgateway

import (
	v1alpha1agentgateway "github.com/agentgateway/agentgateway/controller/api/v1alpha1/agentgateway"
	v1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
)

// JWTMCPConfigApplyConfiguration represents a declarative configuration of the JWTMCPConfig type for use
// with apply.
//
// JWTMCPConfig holds MCP-specific extensions for JWT authentication.
type JWTMCPConfigApplyConfiguration struct {
	// `resourceMetadata` defines the metadata to use for MCP resources,
	// served at the MCP OAuth metadata endpoints.
	ResourceMetadata map[string]v1.JSON `json:"resourceMetadata,omitempty"`
	// `provider` specifies the identity provider to use for MCP authentication flows.
	Provider *v1alpha1agentgateway.McpIDP `json:"provider,omitempty"`
}

// JWTMCPConfigApplyConfiguration constructs a declarative configuration of the JWTMCPConfig type for use with
// apply.
func JWTMCPConfig() *JWTMCPConfigApplyConfiguration {
	return &JWTMCPConfigApplyConfiguration{}
}

// WithResourceMetadata puts the entries into the ResourceMetadata field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the ResourceMetadata field,
// overwriting an existing map entries in ResourceMetadata field with the same key.
func (b *JWTMCPConfigApplyConfiguration) WithResourceMetadata(entries map[string]v1.JSON) *JWTMCPConfigApplyConfiguration {
	if b.ResourceMetadata == nil && len(entries) > 0 {
		b.ResourceMetadata = make(map[string]v1.JSON, len(entries))
	}
	for k, v := range entries {
		b.ResourceMetadata[k] = v
	}
	return b
}

// WithProvider sets the Provider field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Provider field is set to the value of the last call.
func (b *JWTMCPConfigApplyConfiguration) WithProvider(value v1alpha1agentgateway.McpIDP) *JWTMCPConfigApplyConfiguration {
	b.Provider = &value
	return b
}
