// Code generated by applyconfiguration-gen. DO NOT EDIT.

package agentgateway

// JWTProviderApplyConfiguration represents a declarative configuration of the JWTProvider type for use
// with apply.
type JWTProviderApplyConfiguration struct {
	// `issuer` identifies the IdP that issued the JWT. This corresponds to the
	// `iss` claim ([RFC 7519 §4.1.1](https://tools.ietf.org/html/rfc7519#section-4.1.1)).
	Issuer *string `json:"issuer,omitempty"`
	// `audiences` specifies the list of allowed audiences that are allowed
	// access. This corresponds to the `aud` claim
	// ([RFC 7519 §4.1.3](https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.3)).
	// If unset, any audience is allowed.
	Audiences []string `json:"audiences,omitempty"`
	// `jwks` defines the JSON Web Key Set used to validate the signature of the
	// JWT.
	JWKS *JWKSApplyConfiguration `json:"jwks,omitempty"`
}

// JWTProviderApplyConfiguration constructs a declarative configuration of the JWTProvider type for use with
// apply.
func JWTProvider() *JWTProviderApplyConfiguration {
	return &JWTProviderApplyConfiguration{}
}

// WithIssuer sets the Issuer field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Issuer field is set to the value of the last call.
func (b *JWTProviderApplyConfiguration) WithIssuer(value string) *JWTProviderApplyConfiguration {
	b.Issuer = &value
	return b
}

// WithAudiences adds the given value to the Audiences field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Audiences field.
func (b *JWTProviderApplyConfiguration) WithAudiences(values ...string) *JWTProviderApplyConfiguration {
	for i := range values {
		b.Audiences = append(b.Audiences, values[i])
	}
	return b
}

// WithJWKS sets the JWKS field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the JWKS field is set to the value of the last call.
func (b *JWTProviderApplyConfiguration) WithJWKS(value *JWKSApplyConfiguration) *JWTProviderApplyConfiguration {
	b.JWKS = value
	return b
}
