// Code generated by applyconfiguration-gen. DO NOT EDIT.

package agentgateway

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// KeepaliveApplyConfiguration represents a declarative configuration of the Keepalive type for use
// with apply.
//
// TCP keepalive settings.
type KeepaliveApplyConfiguration struct {
	// retries specifies the maximum number of keep-alive probes to send before dropping the connection.
	// If unset, this defaults to 9.
	Retries *int32 `json:"retries,omitempty"`
	// time specifies the number of seconds a connection needs to be idle before keep-alive probes start being sent.
	// If unset, this defaults to 180s.
	Time *v1.Duration `json:"time,omitempty"`
	// interval specifies the number of seconds between keep-alive probes.
	// If unset, this defaults to 180s.
	Interval *v1.Duration `json:"interval,omitempty"`
}

// KeepaliveApplyConfiguration constructs a declarative configuration of the Keepalive type for use with
// apply.
func Keepalive() *KeepaliveApplyConfiguration {
	return &KeepaliveApplyConfiguration{}
}

// WithRetries sets the Retries field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Retries field is set to the value of the last call.
func (b *KeepaliveApplyConfiguration) WithRetries(value int32) *KeepaliveApplyConfiguration {
	b.Retries = &value
	return b
}

// WithTime sets the Time field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Time field is set to the value of the last call.
func (b *KeepaliveApplyConfiguration) WithTime(value v1.Duration) *KeepaliveApplyConfiguration {
	b.Time = &value
	return b
}

// WithInterval sets the Interval field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Interval field is set to the value of the last call.
func (b *KeepaliveApplyConfiguration) WithInterval(value v1.Duration) *KeepaliveApplyConfiguration {
	b.Interval = &value
	return b
}
