// Code generated by applyconfiguration-gen. DO NOT EDIT.

package agentgateway

import (
	v1alpha1agentgateway "github.com/agentgateway/agentgateway/controller/api/v1alpha1/agentgateway"
)

// LocalRateLimitApplyConfiguration represents a declarative configuration of the LocalRateLimit type for use
// with apply.
//
// Policy for local rate limiting. Local rate limits are handled locally on a per-proxy basis, without co-ordination
// between instances of the proxy.
type LocalRateLimitApplyConfiguration struct {
	// `requests` specifies the number of HTTP requests per unit of time that
	// are allowed. Requests exceeding this limit will fail with a `429`
	// error.
	Requests *int32 `json:"requests,omitempty"`
	// `tokens` specifies the number of LLM tokens per unit of time that are
	// allowed. Requests exceeding this limit will fail with a `429` error.
	//
	// Both input and output tokens are counted. However, token counts are not known until the request completes. As a
	// result, token-based rate limits will apply to future requests only.
	Tokens *int32 `json:"tokens,omitempty"`
	// `unit` specifies the unit of time that requests are limited on.
	Unit *v1alpha1agentgateway.LocalRateLimitUnit `json:"unit,omitempty"`
	// `burst` specifies an allowance of requests above the request-per-unit
	// that should be allowed within a short period of time.
	Burst *int32 `json:"burst,omitempty"`
}

// LocalRateLimitApplyConfiguration constructs a declarative configuration of the LocalRateLimit type for use with
// apply.
func LocalRateLimit() *LocalRateLimitApplyConfiguration {
	return &LocalRateLimitApplyConfiguration{}
}

// WithRequests sets the Requests field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Requests field is set to the value of the last call.
func (b *LocalRateLimitApplyConfiguration) WithRequests(value int32) *LocalRateLimitApplyConfiguration {
	b.Requests = &value
	return b
}

// WithTokens sets the Tokens field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Tokens field is set to the value of the last call.
func (b *LocalRateLimitApplyConfiguration) WithTokens(value int32) *LocalRateLimitApplyConfiguration {
	b.Tokens = &value
	return b
}

// WithUnit sets the Unit field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Unit field is set to the value of the last call.
func (b *LocalRateLimitApplyConfiguration) WithUnit(value v1alpha1agentgateway.LocalRateLimitUnit) *LocalRateLimitApplyConfiguration {
	b.Unit = &value
	return b
}

// WithBurst sets the Burst field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Burst field is set to the value of the last call.
func (b *LocalRateLimitApplyConfiguration) WithBurst(value int32) *LocalRateLimitApplyConfiguration {
	b.Burst = &value
	return b
}
