// Code generated by applyconfiguration-gen. DO NOT EDIT.

package agentgateway

// LogTracingAttributesApplyConfiguration represents a declarative configuration of the LogTracingAttributes type for use
// with apply.
type LogTracingAttributesApplyConfiguration struct {
	// `remove` lists the default fields that should be removed. For example,
	// `http.method`.
	Remove []string `json:"remove,omitempty"`
	// `add` specifies additional key-value pairs to be added to each entry.
	// The value is a CEL expression. If the CEL expression fails to evaluate,
	// the pair will be excluded.
	Add []AttributeAddApplyConfiguration `json:"add,omitempty"`
}

// LogTracingAttributesApplyConfiguration constructs a declarative configuration of the LogTracingAttributes type for use with
// apply.
func LogTracingAttributes() *LogTracingAttributesApplyConfiguration {
	return &LogTracingAttributesApplyConfiguration{}
}

// WithRemove adds the given value to the Remove field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Remove field.
func (b *LogTracingAttributesApplyConfiguration) WithRemove(values ...string) *LogTracingAttributesApplyConfiguration {
	for i := range values {
		b.Remove = append(b.Remove, values[i])
	}
	return b
}

// WithAdd adds the given value to the Add field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Add field.
func (b *LogTracingAttributesApplyConfiguration) WithAdd(values ...*AttributeAddApplyConfiguration) *LogTracingAttributesApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithAdd")
		}
		b.Add = append(b.Add, *values[i])
	}
	return b
}
