// Code generated by applyconfiguration-gen. DO NOT EDIT.

package agentgateway

import (
	v1alpha1agentgateway "github.com/agentgateway/agentgateway/controller/api/v1alpha1/agentgateway"
	v1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
)

// MCPAuthenticationApplyConfiguration represents a declarative configuration of the MCPAuthentication type for use
// with apply.
type MCPAuthenticationApplyConfiguration struct {
	// ResourceMetadata defines the metadata to use for MCP resources.
	ResourceMetadata map[string]v1.JSON `json:"resourceMetadata,omitempty"`
	// `provider` specifies the identity provider to use for authentication.
	McpIDP *v1alpha1agentgateway.McpIDP `json:"provider,omitempty"`
	// `issuer` identifies the IdP that issued the JWT. This corresponds to the
	// `iss` claim ([RFC 7519 §4.1.1](https://tools.ietf.org/html/rfc7519#section-4.1.1)).
	Issuer *string `json:"issuer,omitempty"`
	// `audiences` specifies the list of allowed audiences that are allowed
	// access. This corresponds to the `aud` claim
	// ([RFC 7519 §4.1.3](https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.3)).
	// If unset, any audience is allowed.
	Audiences []string `json:"audiences,omitempty"`
	// `jwks` defines the remote JSON Web Key used to validate the signature of
	// the JWT.
	JWKS *RemoteJWKSApplyConfiguration `json:"jwks,omitempty"`
	// `mode` is the validation mode for JWT authentication.
	Mode *v1alpha1agentgateway.JWTAuthenticationMode `json:"mode,omitempty"`
}

// MCPAuthenticationApplyConfiguration constructs a declarative configuration of the MCPAuthentication type for use with
// apply.
func MCPAuthentication() *MCPAuthenticationApplyConfiguration {
	return &MCPAuthenticationApplyConfiguration{}
}

// WithResourceMetadata puts the entries into the ResourceMetadata field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the ResourceMetadata field,
// overwriting an existing map entries in ResourceMetadata field with the same key.
func (b *MCPAuthenticationApplyConfiguration) WithResourceMetadata(entries map[string]v1.JSON) *MCPAuthenticationApplyConfiguration {
	if b.ResourceMetadata == nil && len(entries) > 0 {
		b.ResourceMetadata = make(map[string]v1.JSON, len(entries))
	}
	for k, v := range entries {
		b.ResourceMetadata[k] = v
	}
	return b
}

// WithMcpIDP sets the McpIDP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the McpIDP field is set to the value of the last call.
func (b *MCPAuthenticationApplyConfiguration) WithMcpIDP(value v1alpha1agentgateway.McpIDP) *MCPAuthenticationApplyConfiguration {
	b.McpIDP = &value
	return b
}

// WithIssuer sets the Issuer field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Issuer field is set to the value of the last call.
func (b *MCPAuthenticationApplyConfiguration) WithIssuer(value string) *MCPAuthenticationApplyConfiguration {
	b.Issuer = &value
	return b
}

// WithAudiences adds the given value to the Audiences field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Audiences field.
func (b *MCPAuthenticationApplyConfiguration) WithAudiences(values ...string) *MCPAuthenticationApplyConfiguration {
	for i := range values {
		b.Audiences = append(b.Audiences, values[i])
	}
	return b
}

// WithJWKS sets the JWKS field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the JWKS field is set to the value of the last call.
func (b *MCPAuthenticationApplyConfiguration) WithJWKS(value *RemoteJWKSApplyConfiguration) *MCPAuthenticationApplyConfiguration {
	b.JWKS = value
	return b
}

// WithMode sets the Mode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Mode field is set to the value of the last call.
func (b *MCPAuthenticationApplyConfiguration) WithMode(value v1alpha1agentgateway.JWTAuthenticationMode) *MCPAuthenticationApplyConfiguration {
	b.Mode = &value
	return b
}
