// Code generated by applyconfiguration-gen. DO NOT EDIT.

package agentgateway

import (
	v1alpha1agentgateway "github.com/agentgateway/agentgateway/controller/api/v1alpha1/agentgateway"
)

// MCPBackendApplyConfiguration represents a declarative configuration of the MCPBackend type for use
// with apply.
//
// MCPBackend configures `mcp` backends.
type MCPBackendApplyConfiguration struct {
	// `targets` is a list of MCP targets to use for this backend. Policies
	// targeting MCP targets must use `targetRefs[].sectionName` to select
	// the target by name.
	Targets []McpTargetSelectorApplyConfiguration `json:"targets,omitempty"`
	// `sessionRouting` configures MCP session behavior for requests.
	// Defaults to `Stateful` if not set.
	SessionRouting *v1alpha1agentgateway.SessionRouting `json:"sessionRouting,omitempty"`
	// `failureMode` controls behavior when MCP targets fail to initialize or
	// become unavailable at runtime. `FailOpen` skips failed targets and
	// continues serving from healthy ones. `FailClosed` (default) fails the
	// entire session if any target fails.
	FailureMode *v1alpha1agentgateway.FailureMode `json:"failureMode,omitempty"`
}

// MCPBackendApplyConfiguration constructs a declarative configuration of the MCPBackend type for use with
// apply.
func MCPBackend() *MCPBackendApplyConfiguration {
	return &MCPBackendApplyConfiguration{}
}

// WithTargets adds the given value to the Targets field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Targets field.
func (b *MCPBackendApplyConfiguration) WithTargets(values ...*McpTargetSelectorApplyConfiguration) *MCPBackendApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithTargets")
		}
		b.Targets = append(b.Targets, *values[i])
	}
	return b
}

// WithSessionRouting sets the SessionRouting field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SessionRouting field is set to the value of the last call.
func (b *MCPBackendApplyConfiguration) WithSessionRouting(value v1alpha1agentgateway.SessionRouting) *MCPBackendApplyConfiguration {
	b.SessionRouting = &value
	return b
}

// WithFailureMode sets the FailureMode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FailureMode field is set to the value of the last call.
func (b *MCPBackendApplyConfiguration) WithFailureMode(value v1alpha1agentgateway.FailureMode) *MCPBackendApplyConfiguration {
	b.FailureMode = &value
	return b
}
