// Code generated by applyconfiguration-gen. DO NOT EDIT.

package agentgateway

import (
	v1alpha1agentgateway "github.com/agentgateway/agentgateway/controller/api/v1alpha1/agentgateway"
	v1 "k8s.io/api/core/v1"
)

// McpTargetApplyConfiguration represents a declarative configuration of the McpTarget type for use
// with apply.
//
// McpTarget defines a single MCPBackend target configuration.
type McpTargetApplyConfiguration struct {
	// Host is the hostname or IP address of the MCP target.
	Host *string `json:"host,omitempty"`
	// `backendRef` references a namespace-local `Service` resource by name.
	// When set, this replaces `host` only; `port`, `path`, and `protocol`
	// remain configured on this target.
	BackendRef *v1.LocalObjectReference `json:"backendRef,omitempty"`
	// Port is the port number of the MCP target.
	Port *int32 `json:"port,omitempty"`
	// Path is the URL path of the MCP target endpoint.
	// Defaults to `"/sse"` for the `SSE` protocol or `"/mcp"` for the
	// `StreamableHTTP` protocol if not specified.
	Path *string `json:"path,omitempty"`
	// Protocol is the protocol to use for the connection to the MCP
	// target.
	Protocol *v1alpha1agentgateway.MCPProtocol `json:"protocol,omitempty"`
	// `policies` controls policies for communicating with this backend.
	// Policies may also be set in `AgentgatewayPolicy`, or in the top-level
	// `AgentgatewayBackend`. Policies are merged on a field-level basis, with
	// order: `AgentgatewayPolicy` < `AgentgatewayBackend` < `AgentgatewayBackend` MCP (this field).
	// This field may only be used with host-based static targets, not
	// `backendRef`.
	Policies *BackendSimpleApplyConfiguration `json:"policies,omitempty"`
}

// McpTargetApplyConfiguration constructs a declarative configuration of the McpTarget type for use with
// apply.
func McpTarget() *McpTargetApplyConfiguration {
	return &McpTargetApplyConfiguration{}
}

// WithHost sets the Host field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Host field is set to the value of the last call.
func (b *McpTargetApplyConfiguration) WithHost(value string) *McpTargetApplyConfiguration {
	b.Host = &value
	return b
}

// WithBackendRef sets the BackendRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BackendRef field is set to the value of the last call.
func (b *McpTargetApplyConfiguration) WithBackendRef(value v1.LocalObjectReference) *McpTargetApplyConfiguration {
	b.BackendRef = &value
	return b
}

// WithPort sets the Port field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Port field is set to the value of the last call.
func (b *McpTargetApplyConfiguration) WithPort(value int32) *McpTargetApplyConfiguration {
	b.Port = &value
	return b
}

// WithPath sets the Path field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Path field is set to the value of the last call.
func (b *McpTargetApplyConfiguration) WithPath(value string) *McpTargetApplyConfiguration {
	b.Path = &value
	return b
}

// WithProtocol sets the Protocol field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Protocol field is set to the value of the last call.
func (b *McpTargetApplyConfiguration) WithProtocol(value v1alpha1agentgateway.MCPProtocol) *McpTargetApplyConfiguration {
	b.Protocol = &value
	return b
}

// WithPolicies sets the Policies field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Policies field is set to the value of the last call.
func (b *McpTargetApplyConfiguration) WithPolicies(value *BackendSimpleApplyConfiguration) *McpTargetApplyConfiguration {
	b.Policies = value
	return b
}
