// Code generated by applyconfiguration-gen. DO NOT EDIT.

package agentgateway

// OpenAIModerationApplyConfiguration represents a declarative configuration of the OpenAIModeration type for use
// with apply.
type OpenAIModerationApplyConfiguration struct {
	// `model` specifies the moderation model to use. For example,
	// `omni-moderation`.
	Model *string `json:"model,omitempty"`
	// policies controls policies for communicating with OpenAI.
	Policies *BackendSimpleApplyConfiguration `json:"policies,omitempty"`
}

// OpenAIModerationApplyConfiguration constructs a declarative configuration of the OpenAIModeration type for use with
// apply.
func OpenAIModeration() *OpenAIModerationApplyConfiguration {
	return &OpenAIModerationApplyConfiguration{}
}

// WithModel sets the Model field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Model field is set to the value of the last call.
func (b *OpenAIModerationApplyConfiguration) WithModel(value string) *OpenAIModerationApplyConfiguration {
	b.Model = &value
	return b
}

// WithPolicies sets the Policies field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Policies field is set to the value of the last call.
func (b *OpenAIModerationApplyConfiguration) WithPolicies(value *BackendSimpleApplyConfiguration) *OpenAIModerationApplyConfiguration {
	b.Policies = value
	return b
}
