// Code generated by applyconfiguration-gen. DO NOT EDIT.

package agentgateway

// OpenAIConfigApplyConfiguration represents a declarative configuration of the OpenAIConfig type for use
// with apply.
//
// OpenAIConfig settings for the [OpenAI](https://developers.openai.com/api/docs/guides/streaming-responses) LLM provider.
type OpenAIConfigApplyConfiguration struct {
	// Optional: Override the model name, such as `gpt-4o-mini`.
	// If unset, the model name is taken from the request.
	Model *string `json:"model,omitempty"`
}

// OpenAIConfigApplyConfiguration constructs a declarative configuration of the OpenAIConfig type for use with
// apply.
func OpenAIConfig() *OpenAIConfigApplyConfiguration {
	return &OpenAIConfigApplyConfiguration{}
}

// WithModel sets the Model field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Model field is set to the value of the last call.
func (b *OpenAIConfigApplyConfiguration) WithModel(value string) *OpenAIConfigApplyConfiguration {
	b.Model = &value
	return b
}
