// Code generated by applyconfiguration-gen. DO NOT EDIT.

package agentgateway

import (
	v1alpha1agentgateway "github.com/agentgateway/agentgateway/controller/api/v1alpha1/agentgateway"
	v1 "sigs.k8s.io/gateway-api/apis/v1"
)

// OtlpAccessLogApplyConfiguration represents a declarative configuration of the OtlpAccessLog type for use
// with apply.
//
// OtlpAccessLog defines configuration for shipping access logs to an
// OpenTelemetry-compatible backend via OTLP.
type OtlpAccessLogApplyConfiguration struct {
	// `backendRef` references the OTLP server to send access logs to.
	// Supported types: `Service` and `AgentgatewayBackend`.
	BackendRef *v1.BackendObjectReference `json:"backendRef,omitempty"`
	// `protocol` specifies the OTLP protocol variant to use.
	Protocol *v1alpha1agentgateway.OTLPProtocol `json:"protocol,omitempty"`
	// `path` specifies the OTLP/HTTP path to use. This is only applicable
	// when `protocol` is `HTTP`. If unset, this defaults to `/v1/logs`.
	Path *string `json:"path,omitempty"`
}

// OtlpAccessLogApplyConfiguration constructs a declarative configuration of the OtlpAccessLog type for use with
// apply.
func OtlpAccessLog() *OtlpAccessLogApplyConfiguration {
	return &OtlpAccessLogApplyConfiguration{}
}

// WithBackendRef sets the BackendRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BackendRef field is set to the value of the last call.
func (b *OtlpAccessLogApplyConfiguration) WithBackendRef(value v1.BackendObjectReference) *OtlpAccessLogApplyConfiguration {
	b.BackendRef = &value
	return b
}

// WithProtocol sets the Protocol field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Protocol field is set to the value of the last call.
func (b *OtlpAccessLogApplyConfiguration) WithProtocol(value v1alpha1agentgateway.OTLPProtocol) *OtlpAccessLogApplyConfiguration {
	b.Protocol = &value
	return b
}

// WithPath sets the Path field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Path field is set to the value of the last call.
func (b *OtlpAccessLogApplyConfiguration) WithPath(value string) *OtlpAccessLogApplyConfiguration {
	b.Path = &value
	return b
}
