// Code generated by applyconfiguration-gen. DO NOT EDIT.

package agentgateway

// PromptguardRequestApplyConfiguration represents a declarative configuration of the PromptguardRequest type for use
// with apply.
//
// PromptguardRequest defines the prompt guards to apply to requests sent by the client.
type PromptguardRequestApplyConfiguration struct {
	// A custom response message to return to the client. If not specified, defaults to
	// `The request was rejected due to inappropriate content`.
	CustomResponse *CustomResponseApplyConfiguration `json:"response,omitempty"`
	// Regular expression (regex) matching for prompt guards and data masking.
	Regex *RegexApplyConfiguration `json:"regex,omitempty"`
	// Configure a webhook to forward requests to for prompt guarding.
	Webhook *WebhookApplyConfiguration `json:"webhook,omitempty"`
	// `openAIModeration` passes prompt data through the OpenAI Moderations
	// endpoint.
	// See https://developers.openai.com/api/reference/resources/moderations for more information.
	OpenAIModeration *OpenAIModerationApplyConfiguration `json:"openAIModeration,omitempty"`
	// `bedrockGuardrails` configures AWS Bedrock Guardrails for prompt
	// guarding.
	BedrockGuardrails *BedrockGuardrailsApplyConfiguration `json:"bedrockGuardrails,omitempty"`
	// `googleModelArmor` configures Google Model Armor for prompt guarding.
	GoogleModelArmor *GoogleModelArmorApplyConfiguration `json:"googleModelArmor,omitempty"`
}

// PromptguardRequestApplyConfiguration constructs a declarative configuration of the PromptguardRequest type for use with
// apply.
func PromptguardRequest() *PromptguardRequestApplyConfiguration {
	return &PromptguardRequestApplyConfiguration{}
}

// WithCustomResponse sets the CustomResponse field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CustomResponse field is set to the value of the last call.
func (b *PromptguardRequestApplyConfiguration) WithCustomResponse(value *CustomResponseApplyConfiguration) *PromptguardRequestApplyConfiguration {
	b.CustomResponse = value
	return b
}

// WithRegex sets the Regex field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Regex field is set to the value of the last call.
func (b *PromptguardRequestApplyConfiguration) WithRegex(value *RegexApplyConfiguration) *PromptguardRequestApplyConfiguration {
	b.Regex = value
	return b
}

// WithWebhook sets the Webhook field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Webhook field is set to the value of the last call.
func (b *PromptguardRequestApplyConfiguration) WithWebhook(value *WebhookApplyConfiguration) *PromptguardRequestApplyConfiguration {
	b.Webhook = value
	return b
}

// WithOpenAIModeration sets the OpenAIModeration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OpenAIModeration field is set to the value of the last call.
func (b *PromptguardRequestApplyConfiguration) WithOpenAIModeration(value *OpenAIModerationApplyConfiguration) *PromptguardRequestApplyConfiguration {
	b.OpenAIModeration = value
	return b
}

// WithBedrockGuardrails sets the BedrockGuardrails field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BedrockGuardrails field is set to the value of the last call.
func (b *PromptguardRequestApplyConfiguration) WithBedrockGuardrails(value *BedrockGuardrailsApplyConfiguration) *PromptguardRequestApplyConfiguration {
	b.BedrockGuardrails = value
	return b
}

// WithGoogleModelArmor sets the GoogleModelArmor field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GoogleModelArmor field is set to the value of the last call.
func (b *PromptguardRequestApplyConfiguration) WithGoogleModelArmor(value *GoogleModelArmorApplyConfiguration) *PromptguardRequestApplyConfiguration {
	b.GoogleModelArmor = value
	return b
}
