// Code generated by applyconfiguration-gen. DO NOT EDIT.

package agentgateway

// PromptguardResponseApplyConfiguration represents a declarative configuration of the PromptguardResponse type for use
// with apply.
//
// PromptguardResponse configures the response that the prompt guard applies to responses returned by the LLM provider.
type PromptguardResponseApplyConfiguration struct {
	// A custom response message to return to the client. If not specified, defaults to
	// `The response was rejected due to inappropriate content`.
	CustomResponse *CustomResponseApplyConfiguration `json:"response,omitempty"`
	// Regular expression (regex) matching for prompt guards and data masking.
	Regex *RegexApplyConfiguration `json:"regex,omitempty"`
	// Configure a webhook to forward responses to for prompt guarding.
	Webhook *WebhookApplyConfiguration `json:"webhook,omitempty"`
	// `bedrockGuardrails` configures AWS Bedrock Guardrails for prompt
	// guarding.
	BedrockGuardrails *BedrockGuardrailsApplyConfiguration `json:"bedrockGuardrails,omitempty"`
	// `googleModelArmor` configures Google Model Armor for prompt guarding.
	GoogleModelArmor *GoogleModelArmorApplyConfiguration `json:"googleModelArmor,omitempty"`
}

// PromptguardResponseApplyConfiguration constructs a declarative configuration of the PromptguardResponse type for use with
// apply.
func PromptguardResponse() *PromptguardResponseApplyConfiguration {
	return &PromptguardResponseApplyConfiguration{}
}

// WithCustomResponse sets the CustomResponse field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CustomResponse field is set to the value of the last call.
func (b *PromptguardResponseApplyConfiguration) WithCustomResponse(value *CustomResponseApplyConfiguration) *PromptguardResponseApplyConfiguration {
	b.CustomResponse = value
	return b
}

// WithRegex sets the Regex field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Regex field is set to the value of the last call.
func (b *PromptguardResponseApplyConfiguration) WithRegex(value *RegexApplyConfiguration) *PromptguardResponseApplyConfiguration {
	b.Regex = value
	return b
}

// WithWebhook sets the Webhook field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Webhook field is set to the value of the last call.
func (b *PromptguardResponseApplyConfiguration) WithWebhook(value *WebhookApplyConfiguration) *PromptguardResponseApplyConfiguration {
	b.Webhook = value
	return b
}

// WithBedrockGuardrails sets the BedrockGuardrails field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BedrockGuardrails field is set to the value of the last call.
func (b *PromptguardResponseApplyConfiguration) WithBedrockGuardrails(value *BedrockGuardrailsApplyConfiguration) *PromptguardResponseApplyConfiguration {
	b.BedrockGuardrails = value
	return b
}

// WithGoogleModelArmor sets the GoogleModelArmor field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GoogleModelArmor field is set to the value of the last call.
func (b *PromptguardResponseApplyConfiguration) WithGoogleModelArmor(value *GoogleModelArmorApplyConfiguration) *PromptguardResponseApplyConfiguration {
	b.GoogleModelArmor = value
	return b
}
