// Code generated by applyconfiguration-gen. DO NOT EDIT.

package agentgateway

// PromptCachingConfigApplyConfiguration represents a declarative configuration of the PromptCachingConfig type for use
// with apply.
//
// PromptCachingConfig configures automatic prompt caching for supported LLM providers.
// Currently only AWS Bedrock supports this feature (Claude 3+ and Nova models).
//
// When enabled, the gateway automatically inserts cache points at strategic locations
// to reduce API costs. Bedrock charges lower rates for cached tokens (90% discount).
//
// Example:
//
// promptCaching:
// cacheSystem: true
// cacheMessages: true
// cacheTools: false
//
// Cost savings example:
// - Without caching: 10,000 tokens × $3/MTok = $0.03
// - With caching (90% cached): 1,000 × $3/MTok + 9,000 × $0.30/MTok = $0.0057 (81% savings)
type PromptCachingConfigApplyConfiguration struct {
	// CacheSystem enables caching for system prompts.
	// Inserts a cache point after all system messages.
	CacheSystem *bool `json:"cacheSystem,omitempty"`
	// CacheMessages enables caching for conversation messages.
	// Caches all messages in the conversation for cost savings.
	CacheMessages *bool `json:"cacheMessages,omitempty"`
	// CacheTools enables caching for tool definitions.
	// Inserts a cache point after all tool specifications.
	CacheTools *bool `json:"cacheTools,omitempty"`
	// MinTokens specifies the minimum estimated token count
	// before caching is enabled. Uses rough heuristic (word count × 1.3) to estimate tokens.
	// Bedrock requires at least 1,024 tokens for caching to be effective.
	MinTokens *int `json:"minTokens,omitempty"`
	// CacheMessageOffset shifts the message cache point further back in the
	// conversation. 0 (default) places it at the second-to-last message.
	// Higher values move it N additional messages towards the start, clamped
	// to bounds.
	CacheMessageOffset *int `json:"cacheMessageOffset,omitempty"`
}

// PromptCachingConfigApplyConfiguration constructs a declarative configuration of the PromptCachingConfig type for use with
// apply.
func PromptCachingConfig() *PromptCachingConfigApplyConfiguration {
	return &PromptCachingConfigApplyConfiguration{}
}

// WithCacheSystem sets the CacheSystem field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CacheSystem field is set to the value of the last call.
func (b *PromptCachingConfigApplyConfiguration) WithCacheSystem(value bool) *PromptCachingConfigApplyConfiguration {
	b.CacheSystem = &value
	return b
}

// WithCacheMessages sets the CacheMessages field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CacheMessages field is set to the value of the last call.
func (b *PromptCachingConfigApplyConfiguration) WithCacheMessages(value bool) *PromptCachingConfigApplyConfiguration {
	b.CacheMessages = &value
	return b
}

// WithCacheTools sets the CacheTools field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CacheTools field is set to the value of the last call.
func (b *PromptCachingConfigApplyConfiguration) WithCacheTools(value bool) *PromptCachingConfigApplyConfiguration {
	b.CacheTools = &value
	return b
}

// WithMinTokens sets the MinTokens field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MinTokens field is set to the value of the last call.
func (b *PromptCachingConfigApplyConfiguration) WithMinTokens(value int) *PromptCachingConfigApplyConfiguration {
	b.MinTokens = &value
	return b
}

// WithCacheMessageOffset sets the CacheMessageOffset field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CacheMessageOffset field is set to the value of the last call.
func (b *PromptCachingConfigApplyConfiguration) WithCacheMessageOffset(value int) *PromptCachingConfigApplyConfiguration {
	b.CacheMessageOffset = &value
	return b
}
