// Code generated by applyconfiguration-gen. DO NOT EDIT.

package agentgateway

// RateLimitsApplyConfiguration represents a declarative configuration of the RateLimits type for use
// with apply.
type RateLimitsApplyConfiguration struct {
	// Local defines a local rate limiting policy.
	Local []LocalRateLimitApplyConfiguration `json:"local,omitempty"`
	// Global defines a global rate limiting policy using an external service.
	Global *GlobalRateLimitApplyConfiguration `json:"global,omitempty"`
}

// RateLimitsApplyConfiguration constructs a declarative configuration of the RateLimits type for use with
// apply.
func RateLimits() *RateLimitsApplyConfiguration {
	return &RateLimitsApplyConfiguration{}
}

// WithLocal adds the given value to the Local field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Local field.
func (b *RateLimitsApplyConfiguration) WithLocal(values ...*LocalRateLimitApplyConfiguration) *RateLimitsApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithLocal")
		}
		b.Local = append(b.Local, *values[i])
	}
	return b
}

// WithGlobal sets the Global field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Global field is set to the value of the last call.
func (b *RateLimitsApplyConfiguration) WithGlobal(value *GlobalRateLimitApplyConfiguration) *RateLimitsApplyConfiguration {
	b.Global = value
	return b
}
