// Code generated by applyconfiguration-gen. DO NOT EDIT.

package agentgateway

import (
	v1alpha1agentgateway "github.com/agentgateway/agentgateway/controller/api/v1alpha1/agentgateway"
)

// RateLimitDescriptorApplyConfiguration represents a declarative configuration of the RateLimitDescriptor type for use
// with apply.
type RateLimitDescriptorApplyConfiguration struct {
	// `entries` are the individual components that make up this descriptor.
	Entries []RateLimitDescriptorEntryApplyConfiguration `json:"entries,omitempty"`
	// `unit` defines what to use as the cost function. If unspecified,
	// `Requests` is used.
	Unit *v1alpha1agentgateway.RateLimitUnit `json:"unit,omitempty"`
}

// RateLimitDescriptorApplyConfiguration constructs a declarative configuration of the RateLimitDescriptor type for use with
// apply.
func RateLimitDescriptor() *RateLimitDescriptorApplyConfiguration {
	return &RateLimitDescriptorApplyConfiguration{}
}

// WithEntries adds the given value to the Entries field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Entries field.
func (b *RateLimitDescriptorApplyConfiguration) WithEntries(values ...*RateLimitDescriptorEntryApplyConfiguration) *RateLimitDescriptorApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithEntries")
		}
		b.Entries = append(b.Entries, *values[i])
	}
	return b
}

// WithUnit sets the Unit field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Unit field is set to the value of the last call.
func (b *RateLimitDescriptorApplyConfiguration) WithUnit(value v1alpha1agentgateway.RateLimitUnit) *RateLimitDescriptorApplyConfiguration {
	b.Unit = &value
	return b
}
