// Code generated by applyconfiguration-gen. DO NOT EDIT.

package agentgateway

import (
	shared "github.com/agentgateway/agentgateway/controller/api/v1alpha1/shared"
)

// RateLimitDescriptorEntryApplyConfiguration represents a declarative configuration of the RateLimitDescriptorEntry type for use
// with apply.
//
// A descriptor entry defines a single entry in a rate limit descriptor.
type RateLimitDescriptorEntryApplyConfiguration struct {
	// `name` specifies the name of the descriptor.
	Name *string `json:"name,omitempty"`
	// `expression` is a Common Expression Language (`CEL`) expression that
	// defines the value for the descriptor.
	//
	// For example, to rate limit based on the Client IP: `source.address`.
	//
	// See https://agentgateway.dev/docs/standalone/latest/reference/cel/ for more info.
	Expression *shared.CELExpression `json:"expression,omitempty"`
}

// RateLimitDescriptorEntryApplyConfiguration constructs a declarative configuration of the RateLimitDescriptorEntry type for use with
// apply.
func RateLimitDescriptorEntry() *RateLimitDescriptorEntryApplyConfiguration {
	return &RateLimitDescriptorEntryApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *RateLimitDescriptorEntryApplyConfiguration) WithName(value string) *RateLimitDescriptorEntryApplyConfiguration {
	b.Name = &value
	return b
}

// WithExpression sets the Expression field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Expression field is set to the value of the last call.
func (b *RateLimitDescriptorEntryApplyConfiguration) WithExpression(value shared.CELExpression) *RateLimitDescriptorEntryApplyConfiguration {
	b.Expression = &value
	return b
}
