// Code generated by applyconfiguration-gen. DO NOT EDIT.

package agentgateway

import (
	v1alpha1agentgateway "github.com/agentgateway/agentgateway/controller/api/v1alpha1/agentgateway"
)

// RegexApplyConfiguration represents a declarative configuration of the Regex type for use
// with apply.
//
// Regex configures the regular expression (regex) matching for prompt guards and data masking.
type RegexApplyConfiguration struct {
	// A list of regex patterns to match against the request or response.
	// Matches and built-ins are additive.
	Matches []string `json:"matches,omitempty"`
	// A list of built-in regex patterns to match against the request or response.
	// Matches and built-ins are additive.
	Builtins []v1alpha1agentgateway.BuiltIn `json:"builtins,omitempty"`
	// The action to take if a regex pattern is matched in a request or response.
	// This setting applies only to request matches. `PromptguardResponse`
	// matches are always masked by default.
	// Defaults to `Mask`.
	Action *v1alpha1agentgateway.Action `json:"action,omitempty"`
}

// RegexApplyConfiguration constructs a declarative configuration of the Regex type for use with
// apply.
func Regex() *RegexApplyConfiguration {
	return &RegexApplyConfiguration{}
}

// WithMatches adds the given value to the Matches field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Matches field.
func (b *RegexApplyConfiguration) WithMatches(values ...string) *RegexApplyConfiguration {
	for i := range values {
		b.Matches = append(b.Matches, values[i])
	}
	return b
}

// WithBuiltins adds the given value to the Builtins field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Builtins field.
func (b *RegexApplyConfiguration) WithBuiltins(values ...v1alpha1agentgateway.BuiltIn) *RegexApplyConfiguration {
	for i := range values {
		b.Builtins = append(b.Builtins, values[i])
	}
	return b
}

// WithAction sets the Action field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Action field is set to the value of the last call.
func (b *RegexApplyConfiguration) WithAction(value v1alpha1agentgateway.Action) *RegexApplyConfiguration {
	b.Action = &value
	return b
}
