// Code generated by applyconfiguration-gen. DO NOT EDIT.

package agentgateway

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	apisv1 "sigs.k8s.io/gateway-api/apis/v1"
)

// RemoteJWKSApplyConfiguration represents a declarative configuration of the RemoteJWKS type for use
// with apply.
type RemoteJWKSApplyConfiguration struct {
	// Path to the IdP `jwks` endpoint, relative to the root, commonly
	// `".well-known/jwks.json"`.
	JwksPath      *string      `json:"jwksPath,omitempty"`
	CacheDuration *v1.Duration `json:"cacheDuration,omitempty"`
	// `backendRef` references the remote JWKS server to reach.
	// Supported types are `Service` and static `Backend`. An
	// `AgentgatewayPolicy` containing backend TLS config can then be attached
	// to the `Service` or `Backend` in order to set TLS options for a
	// connection to the remote `jwks` source.
	BackendRef *apisv1.BackendObjectReference `json:"backendRef,omitempty"`
}

// RemoteJWKSApplyConfiguration constructs a declarative configuration of the RemoteJWKS type for use with
// apply.
func RemoteJWKS() *RemoteJWKSApplyConfiguration {
	return &RemoteJWKSApplyConfiguration{}
}

// WithJwksPath sets the JwksPath field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the JwksPath field is set to the value of the last call.
func (b *RemoteJWKSApplyConfiguration) WithJwksPath(value string) *RemoteJWKSApplyConfiguration {
	b.JwksPath = &value
	return b
}

// WithCacheDuration sets the CacheDuration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CacheDuration field is set to the value of the last call.
func (b *RemoteJWKSApplyConfiguration) WithCacheDuration(value v1.Duration) *RemoteJWKSApplyConfiguration {
	b.CacheDuration = &value
	return b
}

// WithBackendRef sets the BackendRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BackendRef field is set to the value of the last call.
func (b *RemoteJWKSApplyConfiguration) WithBackendRef(value apisv1.BackendObjectReference) *RemoteJWKSApplyConfiguration {
	b.BackendRef = &value
	return b
}
