// Code generated by applyconfiguration-gen. DO NOT EDIT.

package agentgateway

import (
	shared "github.com/agentgateway/agentgateway/controller/api/v1alpha1/shared"
)

// ResourceAddApplyConfiguration represents a declarative configuration of the ResourceAdd type for use
// with apply.
type ResourceAddApplyConfiguration struct {
	Name       *string               `json:"name,omitempty"`
	Expression *shared.CELExpression `json:"expression,omitempty"`
}

// ResourceAddApplyConfiguration constructs a declarative configuration of the ResourceAdd type for use with
// apply.
func ResourceAdd() *ResourceAddApplyConfiguration {
	return &ResourceAddApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ResourceAddApplyConfiguration) WithName(value string) *ResourceAddApplyConfiguration {
	b.Name = &value
	return b
}

// WithExpression sets the Expression field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Expression field is set to the value of the last call.
func (b *ResourceAddApplyConfiguration) WithExpression(value shared.CELExpression) *ResourceAddApplyConfiguration {
	b.Expression = &value
	return b
}
