// Code generated by applyconfiguration-gen. DO NOT EDIT.

package agentgateway

import (
	v1 "sigs.k8s.io/gateway-api/apis/v1"
)

// RetryApplyConfiguration represents a declarative configuration of the Retry type for use
// with apply.
//
// Retry defines the retry policy.
type RetryApplyConfiguration struct {
	v1.HTTPRouteRetry `json:",inline"`
}

// RetryApplyConfiguration constructs a declarative configuration of the Retry type for use with
// apply.
func Retry() *RetryApplyConfiguration {
	return &RetryApplyConfiguration{}
}
