// Code generated by applyconfiguration-gen. DO NOT EDIT.

package agentgateway

// SecretSelectorApplyConfiguration represents a declarative configuration of the SecretSelector type for use
// with apply.
type SecretSelectorApplyConfiguration struct {
	// Label selector to select the target resource.
	MatchLabels map[string]string `json:"matchLabels,omitempty"`
}

// SecretSelectorApplyConfiguration constructs a declarative configuration of the SecretSelector type for use with
// apply.
func SecretSelector() *SecretSelectorApplyConfiguration {
	return &SecretSelectorApplyConfiguration{}
}

// WithMatchLabels puts the entries into the MatchLabels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the MatchLabels field,
// overwriting an existing map entries in MatchLabels field with the same key.
func (b *SecretSelectorApplyConfiguration) WithMatchLabels(entries map[string]string) *SecretSelectorApplyConfiguration {
	if b.MatchLabels == nil && len(entries) > 0 {
		b.MatchLabels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.MatchLabels[k] = v
	}
	return b
}
