// Code generated by applyconfiguration-gen. DO NOT EDIT.

package agentgateway

// ShutdownSpecApplyConfiguration represents a declarative configuration of the ShutdownSpec type for use
// with apply.
type ShutdownSpecApplyConfiguration struct {
	// Minimum time (in seconds) to wait before allowing Agentgateway to
	// terminate. Refer to the `CONNECTION_MIN_TERMINATION_DEADLINE`
	// environment variable for details.
	Min *int64 `json:"min,omitempty"`
	// Maximum time (in seconds) to wait before allowing Agentgateway to
	// terminate. Refer to the `TERMINATION_GRACE_PERIOD_SECONDS`
	// environment variable for details.
	Max *int64 `json:"max,omitempty"`
}

// ShutdownSpecApplyConfiguration constructs a declarative configuration of the ShutdownSpec type for use with
// apply.
func ShutdownSpec() *ShutdownSpecApplyConfiguration {
	return &ShutdownSpecApplyConfiguration{}
}

// WithMin sets the Min field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Min field is set to the value of the last call.
func (b *ShutdownSpecApplyConfiguration) WithMin(value int64) *ShutdownSpecApplyConfiguration {
	b.Min = &value
	return b
}

// WithMax sets the Max field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Max field is set to the value of the last call.
func (b *ShutdownSpecApplyConfiguration) WithMax(value int64) *ShutdownSpecApplyConfiguration {
	b.Max = &value
	return b
}
