// Code generated by applyconfiguration-gen. DO NOT EDIT.

package agentgateway

// StaticBackendApplyConfiguration represents a declarative configuration of the StaticBackend type for use
// with apply.
//
// StaticBackend specifies a static backend endpoint — either TCP (host + port) or Unix Domain Socket.
type StaticBackendApplyConfiguration struct {
	// host to connect to (for TCP backends).
	Host *string `json:"host,omitempty"`
	// port to connect to (for TCP backends).
	Port *int32 `json:"port,omitempty"`
	// unixPath is the filesystem path to a Unix Domain Socket. The gateway pod
	// must share a volume with the target (e.g., via emptyDir sidecar pattern).
	// Mutually exclusive with host/port.
	UnixPath *string `json:"unixPath,omitempty"`
}

// StaticBackendApplyConfiguration constructs a declarative configuration of the StaticBackend type for use with
// apply.
func StaticBackend() *StaticBackendApplyConfiguration {
	return &StaticBackendApplyConfiguration{}
}

// WithHost sets the Host field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Host field is set to the value of the last call.
func (b *StaticBackendApplyConfiguration) WithHost(value string) *StaticBackendApplyConfiguration {
	b.Host = &value
	return b
}

// WithPort sets the Port field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Port field is set to the value of the last call.
func (b *StaticBackendApplyConfiguration) WithPort(value int32) *StaticBackendApplyConfiguration {
	b.Port = &value
	return b
}

// WithUnixPath sets the UnixPath field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UnixPath field is set to the value of the last call.
func (b *StaticBackendApplyConfiguration) WithUnixPath(value string) *StaticBackendApplyConfiguration {
	b.UnixPath = &value
	return b
}
