// Code generated by applyconfiguration-gen. DO NOT EDIT.

package agentgateway

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// TimeoutsApplyConfiguration represents a declarative configuration of the Timeouts type for use
// with apply.
type TimeoutsApplyConfiguration struct {
	// request specifies a timeout for an individual request from the gateway to a backend. This covers the time from when
	// the request first starts being sent from the gateway to when the full response has been received from the backend.
	Request *v1.Duration `json:"request,omitempty"`
}

// TimeoutsApplyConfiguration constructs a declarative configuration of the Timeouts type for use with
// apply.
func Timeouts() *TimeoutsApplyConfiguration {
	return &TimeoutsApplyConfiguration{}
}

// WithRequest sets the Request field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Request field is set to the value of the last call.
func (b *TimeoutsApplyConfiguration) WithRequest(value v1.Duration) *TimeoutsApplyConfiguration {
	b.Request = &value
	return b
}
