// Code generated by applyconfiguration-gen. DO NOT EDIT.

package agentgateway

import (
	v1alpha1agentgateway "github.com/agentgateway/agentgateway/controller/api/v1alpha1/agentgateway"
	shared "github.com/agentgateway/agentgateway/controller/api/v1alpha1/shared"
	v1 "sigs.k8s.io/gateway-api/apis/v1"
)

// TracingApplyConfiguration represents a declarative configuration of the Tracing type for use
// with apply.
type TracingApplyConfiguration struct {
	// `backendRef` references the OTLP server to reach.
	// Supported types: `Service` and `AgentgatewayBackend`.
	BackendRef *v1.BackendObjectReference `json:"backendRef,omitempty"`
	// `protocol` specifies the OTLP protocol variant to use.
	Protocol *v1alpha1agentgateway.OTLPProtocol `json:"protocol,omitempty"`
	// `path` specifies the OTLP path to use. This is only applicable when
	// `protocol` is `HTTP`. If unset, this defaults to `/v1/traces`.
	Path *string `json:"path,omitempty"`
	// `attributes` specifies customizations to the key-value pairs that are
	// included in the trace.
	Attributes *LogTracingAttributesApplyConfiguration `json:"attributes,omitempty"`
	// `resources` describes the entity producing telemetry and specifies the
	// resources to be included in the trace.
	Resources []ResourceAddApplyConfiguration `json:"resources,omitempty"`
	// `randomSampling` is an expression to determine the amount of random
	// sampling. Random sampling will initiate a new trace span if the incoming
	// request does not have a trace initiated already. This should evaluate to
	// a float between `0.0` and `1.0`, or a boolean (`true` or `false`). If
	// unspecified, random sampling is disabled.
	RandomSampling *shared.CELExpression `json:"randomSampling,omitempty"`
	// `clientSampling` is an expression to determine the amount of client
	// sampling. Client sampling determines whether to initiate a new trace
	// span if the incoming request does have a trace already. This should
	// evaluate to a float between `0.0` and `1.0`, or a boolean (`true` or
	// `false`). If unspecified, client sampling is `100%` enabled.
	ClientSampling *shared.CELExpression `json:"clientSampling,omitempty"`
}

// TracingApplyConfiguration constructs a declarative configuration of the Tracing type for use with
// apply.
func Tracing() *TracingApplyConfiguration {
	return &TracingApplyConfiguration{}
}

// WithBackendRef sets the BackendRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BackendRef field is set to the value of the last call.
func (b *TracingApplyConfiguration) WithBackendRef(value v1.BackendObjectReference) *TracingApplyConfiguration {
	b.BackendRef = &value
	return b
}

// WithProtocol sets the Protocol field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Protocol field is set to the value of the last call.
func (b *TracingApplyConfiguration) WithProtocol(value v1alpha1agentgateway.OTLPProtocol) *TracingApplyConfiguration {
	b.Protocol = &value
	return b
}

// WithPath sets the Path field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Path field is set to the value of the last call.
func (b *TracingApplyConfiguration) WithPath(value string) *TracingApplyConfiguration {
	b.Path = &value
	return b
}

// WithAttributes sets the Attributes field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Attributes field is set to the value of the last call.
func (b *TracingApplyConfiguration) WithAttributes(value *LogTracingAttributesApplyConfiguration) *TracingApplyConfiguration {
	b.Attributes = value
	return b
}

// WithResources adds the given value to the Resources field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Resources field.
func (b *TracingApplyConfiguration) WithResources(values ...*ResourceAddApplyConfiguration) *TracingApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithResources")
		}
		b.Resources = append(b.Resources, *values[i])
	}
	return b
}

// WithRandomSampling sets the RandomSampling field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RandomSampling field is set to the value of the last call.
func (b *TracingApplyConfiguration) WithRandomSampling(value shared.CELExpression) *TracingApplyConfiguration {
	b.RandomSampling = &value
	return b
}

// WithClientSampling sets the ClientSampling field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClientSampling field is set to the value of the last call.
func (b *TracingApplyConfiguration) WithClientSampling(value shared.CELExpression) *TracingApplyConfiguration {
	b.ClientSampling = &value
	return b
}
