// Code generated by applyconfiguration-gen. DO NOT EDIT.

package agentgateway

import (
	v1alpha1agentgateway "github.com/agentgateway/agentgateway/controller/api/v1alpha1/agentgateway"
	shared "github.com/agentgateway/agentgateway/controller/api/v1alpha1/shared"
)

// TrafficApplyConfiguration represents a declarative configuration of the Traffic type for use
// with apply.
type TrafficApplyConfiguration struct {
	// The phase to apply the traffic policy to. If the phase is `PreRouting`,
	// the `targetRef` must be a `Gateway` or a `Listener`. `PreRouting` is
	// typically used only when a policy needs to influence the routing
	// decision.
	//
	// Even when using `PostRouting` mode, the policy can target the
	// `Gateway` or `Listener`. This is a helper for applying the policy to all
	// routes under that `Gateway` or `Listener`, and follows the merging logic
	// described above.
	//
	// Note: `PreRouting` and `PostRouting` rules do not merge together. These
	// are independent execution phases. That is, all `PreRouting` rules will
	// merge and execute, then all `PostRouting` rules will merge and execute.
	//
	// If unset, this defaults to `PostRouting`.
	Phase *v1alpha1agentgateway.PolicyPhase `json:"phase,omitempty"`
	// transformation is used to mutate and transform requests and responses
	// before forwarding them to the destination.
	Transformation *TransformationApplyConfiguration `json:"transformation,omitempty"`
	// extProc specifies the external processing configuration for the policy.
	ExtProc *ExtProcApplyConfiguration `json:"extProc,omitempty"`
	// extAuth specifies the external authentication configuration for the policy.
	// This controls what external server to send requests to for authentication.
	ExtAuth *ExtAuthApplyConfiguration `json:"extAuth,omitempty"`
	// rateLimit specifies the rate limiting configuration for the policy.
	// This controls the rate at which requests are allowed to be processed.
	RateLimit *RateLimitsApplyConfiguration `json:"rateLimit,omitempty"`
	// cors specifies the CORS configuration for the policy.
	Cors *CORSApplyConfiguration `json:"cors,omitempty"`
	// csrf specifies the Cross-Site Request Forgery (CSRF) policy for this traffic policy.
	//
	// The CSRF policy has the following behavior:
	// * Safe methods (`GET`, `HEAD`, `OPTIONS`) are automatically allowed.
	// * Requests without `Sec-Fetch-Site` or `Origin` headers are assumed to
	// be same-origin or non-browser requests and are allowed.
	// * Otherwise, the `Sec-Fetch-Site` header is checked, with a fallback to
	// comparing the `Origin` header to the `Host` header.
	Csrf *CSRFApplyConfiguration `json:"csrf,omitempty"`
	// headerModifiers defines the policy to modify request and response headers.
	HeaderModifiers *shared.HeaderModifiers `json:"headerModifiers,omitempty"`
	// `hostRewrite` specifies how to rewrite the `Host` header for requests.
	//
	// If the `HTTPRoute` `urlRewrite` filter already specifies a host rewrite,
	// this setting is ignored.
	HostnameRewrite *HostnameRewriteApplyConfiguration `json:"hostRewrite,omitempty"`
	// `timeouts` defines the timeouts for requests.
	// It is applicable to `HTTPRoute` resources and ignored for other targeted
	// kinds.
	Timeouts *TimeoutsApplyConfiguration `json:"timeouts,omitempty"`
	// retry defines the policy for retrying requests.
	Retry *RetryApplyConfiguration `json:"retry,omitempty"`
	// `authorization` specifies the access rules based on roles and
	// permissions.
	// If multiple authorization rules are applied across different policies (at the same, or different, attahcment points),
	// all rules are merged.
	Authorization *shared.Authorization `json:"authorization,omitempty"`
	// `jwtAuthentication` authenticates users based on JWT tokens.
	JWTAuthentication *JWTAuthenticationApplyConfiguration `json:"jwtAuthentication,omitempty"`
	// `basicAuthentication` authenticates users based on the `Basic`
	// authentication scheme (RFC 7617), where a username and password are
	// encoded in the request.
	BasicAuthentication *BasicAuthenticationApplyConfiguration `json:"basicAuthentication,omitempty"`
	// `apiKeyAuthentication` authenticates users based on a configured API
	// key.
	APIKeyAuthentication *APIKeyAuthenticationApplyConfiguration `json:"apiKeyAuthentication,omitempty"`
	// `directResponse` configures the policy to send a direct response to the
	// client.
	DirectResponse *DirectResponseApplyConfiguration `json:"directResponse,omitempty"`
}

// TrafficApplyConfiguration constructs a declarative configuration of the Traffic type for use with
// apply.
func Traffic() *TrafficApplyConfiguration {
	return &TrafficApplyConfiguration{}
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *TrafficApplyConfiguration) WithPhase(value v1alpha1agentgateway.PolicyPhase) *TrafficApplyConfiguration {
	b.Phase = &value
	return b
}

// WithTransformation sets the Transformation field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Transformation field is set to the value of the last call.
func (b *TrafficApplyConfiguration) WithTransformation(value *TransformationApplyConfiguration) *TrafficApplyConfiguration {
	b.Transformation = value
	return b
}

// WithExtProc sets the ExtProc field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ExtProc field is set to the value of the last call.
func (b *TrafficApplyConfiguration) WithExtProc(value *ExtProcApplyConfiguration) *TrafficApplyConfiguration {
	b.ExtProc = value
	return b
}

// WithExtAuth sets the ExtAuth field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ExtAuth field is set to the value of the last call.
func (b *TrafficApplyConfiguration) WithExtAuth(value *ExtAuthApplyConfiguration) *TrafficApplyConfiguration {
	b.ExtAuth = value
	return b
}

// WithRateLimit sets the RateLimit field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RateLimit field is set to the value of the last call.
func (b *TrafficApplyConfiguration) WithRateLimit(value *RateLimitsApplyConfiguration) *TrafficApplyConfiguration {
	b.RateLimit = value
	return b
}

// WithCors sets the Cors field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Cors field is set to the value of the last call.
func (b *TrafficApplyConfiguration) WithCors(value *CORSApplyConfiguration) *TrafficApplyConfiguration {
	b.Cors = value
	return b
}

// WithCsrf sets the Csrf field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Csrf field is set to the value of the last call.
func (b *TrafficApplyConfiguration) WithCsrf(value *CSRFApplyConfiguration) *TrafficApplyConfiguration {
	b.Csrf = value
	return b
}

// WithHeaderModifiers sets the HeaderModifiers field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HeaderModifiers field is set to the value of the last call.
func (b *TrafficApplyConfiguration) WithHeaderModifiers(value shared.HeaderModifiers) *TrafficApplyConfiguration {
	b.HeaderModifiers = &value
	return b
}

// WithHostnameRewrite sets the HostnameRewrite field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HostnameRewrite field is set to the value of the last call.
func (b *TrafficApplyConfiguration) WithHostnameRewrite(value *HostnameRewriteApplyConfiguration) *TrafficApplyConfiguration {
	b.HostnameRewrite = value
	return b
}

// WithTimeouts sets the Timeouts field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Timeouts field is set to the value of the last call.
func (b *TrafficApplyConfiguration) WithTimeouts(value *TimeoutsApplyConfiguration) *TrafficApplyConfiguration {
	b.Timeouts = value
	return b
}

// WithRetry sets the Retry field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Retry field is set to the value of the last call.
func (b *TrafficApplyConfiguration) WithRetry(value *RetryApplyConfiguration) *TrafficApplyConfiguration {
	b.Retry = value
	return b
}

// WithAuthorization sets the Authorization field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Authorization field is set to the value of the last call.
func (b *TrafficApplyConfiguration) WithAuthorization(value shared.Authorization) *TrafficApplyConfiguration {
	b.Authorization = &value
	return b
}

// WithJWTAuthentication sets the JWTAuthentication field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the JWTAuthentication field is set to the value of the last call.
func (b *TrafficApplyConfiguration) WithJWTAuthentication(value *JWTAuthenticationApplyConfiguration) *TrafficApplyConfiguration {
	b.JWTAuthentication = value
	return b
}

// WithBasicAuthentication sets the BasicAuthentication field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BasicAuthentication field is set to the value of the last call.
func (b *TrafficApplyConfiguration) WithBasicAuthentication(value *BasicAuthenticationApplyConfiguration) *TrafficApplyConfiguration {
	b.BasicAuthentication = value
	return b
}

// WithAPIKeyAuthentication sets the APIKeyAuthentication field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the APIKeyAuthentication field is set to the value of the last call.
func (b *TrafficApplyConfiguration) WithAPIKeyAuthentication(value *APIKeyAuthenticationApplyConfiguration) *TrafficApplyConfiguration {
	b.APIKeyAuthentication = value
	return b
}

// WithDirectResponse sets the DirectResponse field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DirectResponse field is set to the value of the last call.
func (b *TrafficApplyConfiguration) WithDirectResponse(value *DirectResponseApplyConfiguration) *TrafficApplyConfiguration {
	b.DirectResponse = value
	return b
}
