// Code generated by applyconfiguration-gen. DO NOT EDIT.

package agentgateway

// TransformationApplyConfiguration represents a declarative configuration of the Transformation type for use
// with apply.
type TransformationApplyConfiguration struct {
	// `request` is used to modify the request path.
	Request *TransformApplyConfiguration `json:"request,omitempty"`
	// `response` is used to modify the response path.
	Response *TransformApplyConfiguration `json:"response,omitempty"`
}

// TransformationApplyConfiguration constructs a declarative configuration of the Transformation type for use with
// apply.
func Transformation() *TransformationApplyConfiguration {
	return &TransformationApplyConfiguration{}
}

// WithRequest sets the Request field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Request field is set to the value of the last call.
func (b *TransformationApplyConfiguration) WithRequest(value *TransformApplyConfiguration) *TransformationApplyConfiguration {
	b.Request = value
	return b
}

// WithResponse sets the Response field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Response field is set to the value of the last call.
func (b *TransformationApplyConfiguration) WithResponse(value *TransformApplyConfiguration) *TransformationApplyConfiguration {
	b.Response = value
	return b
}
