// Code generated by applyconfiguration-gen. DO NOT EDIT.

package agentgateway

import (
	v1alpha1agentgateway "github.com/agentgateway/agentgateway/controller/api/v1alpha1/agentgateway"
	shared "github.com/agentgateway/agentgateway/controller/api/v1alpha1/shared"
)

// TransformApplyConfiguration represents a declarative configuration of the Transform type for use
// with apply.
type TransformApplyConfiguration struct {
	// `set` is a list of headers and the value they should be set to.
	Set []HeaderTransformationApplyConfiguration `json:"set,omitempty"`
	// `add` is a list of headers to add to the request and what that value
	// should be set to. If there is already a header with these values then
	// append the value as an extra entry.
	Add []HeaderTransformationApplyConfiguration `json:"add,omitempty"`
	// `remove` is a list of header names to remove from the request or
	// response.
	Remove []v1alpha1agentgateway.HeaderName `json:"remove,omitempty"`
	// `body` controls manipulation of the HTTP body.
	Body *shared.CELExpression `json:"body,omitempty"`
	// `metadata` stores CEL-evaluated values under the `metadata` CEL variable
	// for subsequent policy evaluations. `metadata` is evaluated before header
	// or body transformations.
	Metadata map[string]shared.CELExpression `json:"metadata,omitempty"`
}

// TransformApplyConfiguration constructs a declarative configuration of the Transform type for use with
// apply.
func Transform() *TransformApplyConfiguration {
	return &TransformApplyConfiguration{}
}

// WithSet adds the given value to the Set field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Set field.
func (b *TransformApplyConfiguration) WithSet(values ...*HeaderTransformationApplyConfiguration) *TransformApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithSet")
		}
		b.Set = append(b.Set, *values[i])
	}
	return b
}

// WithAdd adds the given value to the Add field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Add field.
func (b *TransformApplyConfiguration) WithAdd(values ...*HeaderTransformationApplyConfiguration) *TransformApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithAdd")
		}
		b.Add = append(b.Add, *values[i])
	}
	return b
}

// WithRemove adds the given value to the Remove field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Remove field.
func (b *TransformApplyConfiguration) WithRemove(values ...v1alpha1agentgateway.HeaderName) *TransformApplyConfiguration {
	for i := range values {
		b.Remove = append(b.Remove, values[i])
	}
	return b
}

// WithBody sets the Body field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Body field is set to the value of the last call.
func (b *TransformApplyConfiguration) WithBody(value shared.CELExpression) *TransformApplyConfiguration {
	b.Body = &value
	return b
}

// WithMetadata puts the entries into the Metadata field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Metadata field,
// overwriting an existing map entries in Metadata field with the same key.
func (b *TransformApplyConfiguration) WithMetadata(entries map[string]shared.CELExpression) *TransformApplyConfiguration {
	if b.Metadata == nil && len(entries) > 0 {
		b.Metadata = make(map[string]shared.CELExpression, len(entries))
	}
	for k, v := range entries {
		b.Metadata[k] = v
	}
	return b
}
