// Code generated by applyconfiguration-gen. DO NOT EDIT.

package agentgateway

// VertexAIConfigApplyConfiguration represents a declarative configuration of the VertexAIConfig type for use
// with apply.
//
// VertexAIConfig settings for the [Vertex AI](https://docs.cloud.google.com/vertex-ai/docs) LLM provider.
type VertexAIConfigApplyConfiguration struct {
	// Optional: Override the model name, such as `gpt-4o-mini`.
	// If unset, the model name is taken from the request.
	Model *string `json:"model,omitempty"`
	// The ID of the Google Cloud Project that you use for the Vertex AI.
	ProjectId *string `json:"projectId,omitempty"`
	// The location of the Google Cloud Project that you use for the Vertex AI.
	// Defaults to `global` if not specified.
	Region *string `json:"region,omitempty"`
}

// VertexAIConfigApplyConfiguration constructs a declarative configuration of the VertexAIConfig type for use with
// apply.
func VertexAIConfig() *VertexAIConfigApplyConfiguration {
	return &VertexAIConfigApplyConfiguration{}
}

// WithModel sets the Model field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Model field is set to the value of the last call.
func (b *VertexAIConfigApplyConfiguration) WithModel(value string) *VertexAIConfigApplyConfiguration {
	b.Model = &value
	return b
}

// WithProjectId sets the ProjectId field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProjectId field is set to the value of the last call.
func (b *VertexAIConfigApplyConfiguration) WithProjectId(value string) *VertexAIConfigApplyConfiguration {
	b.ProjectId = &value
	return b
}

// WithRegion sets the Region field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Region field is set to the value of the last call.
func (b *VertexAIConfigApplyConfiguration) WithRegion(value string) *VertexAIConfigApplyConfiguration {
	b.Region = &value
	return b
}
