apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vmauth-tls-cert
  namespace: monitoring
spec:
  secretName: vmauth-tls-cert
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
  dnsNames:
    - vmauth.monitoring.svc
    - vmauth-external.monitoring.svc
    - vmauth.monitoring.svc.cluster.local
    - vmauth-external.monitoring.svc.cluster.local
  duration: 8760h
  renewBefore: 720h
