apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAuth
metadata:
  name: vmauth
  namespace: monitoring
spec:
  selectAllByDefault: true
  extraArgs:
    tls: "true"
    tlsCertFile: /etc/vmauth-tls/tls.crt
    tlsKeyFile: /etc/vmauth-tls/tls.key
  volumes:
    - name: tls
      secret:
        secretName: vmauth-tls-cert
  volumeMounts:
    - name: tls
      mountPath: /etc/vmauth-tls
      readOnly: true
